### ISSUE TITLE
gitlab_project_protected_environment resource does not adding multiple allowed users, roles, or groups

### ISSUE THREAD

**Issue by dschaaff** [gitlabhq/terraform-provider-gitlab#1000]
### GitLab Provider version

3.13.0

### GitLab version

gitlab.com

### Terraform version

1.1.7

### Relevant Terraform Configuration

```hcl
resource "gitlab_project_protected_environment" "staging" {
  project     = gitlab_project.this.id
  environment = "staging"
  deploy_access_levels {
    access_level = "maintainer"
    group_id = my_group_id
  }
}
```

### Relevant log output

```shell
It shows the bellow diff every time and never actually applies.

-/+ resource "gitlab_project_protected_environment" "staging" {
      ~ id          = "29419209:staging" -> (known after apply)
        # (2 unchanged attributes hidden)

      ~ deploy_access_levels {
          ~ access_level_description = "Maintainers" -> (known after apply)
          - group_id                 = 0 -> null
          ~ group_id                  = 0 -> xxxxxx # forces replacement
            # (1 unchanged attribute hidden)
        }
    }
```

### Description

The resource only allows adding a single role to the protected environment permissions. I need to be able to add the maintainers role, multiple individual users, and groups. It probably makes sense to either allow multiple `deploy_access_levels` blocks or to accept lists for access_level, group_id, and user_id.

**Comment by armsnyder** [comment]
The resource seems to work as long as you only use a single `deploy_access_levels` block, so I relabeled this as an enhancement to allow multiple `deploy_access_levels` blocks. I can take a look at adding this today.
