### ISSUE TITLE
Authorization issues with programmatically generated personal access tokens

### ISSUE THREAD

**Issue by Jasper-Ben** [gitlabhq/terraform-provider-gitlab#1017]
### GitLab Provider version

3.13.0

### GitLab version

GitLab 14.9.2-ee 

### Terraform version

v1.1.7

### Relevant log output

```shell
│ Error: POST https://gitlab.example.com/api/v4/groups: 401 {message: 401 Unauthorized}
│                                                                                                                      
│   with gitlab_group.gitlab_groups["FOO"],       
│   on module-k8s-gitlab.tf line 53, in resource "gitlab_group" "gitlab_groups":
│   53: resource "gitlab_group" "gitlab_groups" {
```

### Description

This module assumes that personal access tokens can be used as bearer tokens:
https://github.com/gitlabhq/terraform-provider-gitlab/blob/6b2205b9c9e0f295c359f55a3576f6023738c535/internal/provider/config.go#L71

This is true for access tokens generated via the GitLab webinterface, however this appears not to be true for programmatically generated personal access tokens, as described in the [GitLab documentation](https://docs.gitlab.com/ee/user/profile/personal_access_tokens.html#create-a-personal-access-token-programmatically). Usecase: Automatic spin-up, API token generation and configuration of a freshly set-up GitLab instance with a single `terraform apply`.

I have verified this behavior using curl:

Using `PRIVATE-TOKEN` authentication:
```
curl --header "PRIVATE-TOKEN: <programmatically_generated_token>" "https://gitlab.example.com/api/v4/user"       
```
-> 200 success

Using `Bearer` authentication:
```
curl --header "Authorization: Bearer <programmatically_generated_token>" "https://gitlab.example.com/api/v4/user"
```
-> 401 unauthorized

I am unsure if this is a bug in GitLab itself, or if this "works as intended", as I am not familiar enough with their authorization mechanisms. I will definitely open a separate issue in the GitLab issue tracker and link it in here (or maybe someone here knows more than I do?).

In the meanwhile, a fix for this provider can be easily provided by adding an option for enforcing the usage of personal access authentication instead of bearer token authentication.

**Comment by Jasper-Ben** [comment]
Issue report in GitLab: https://gitlab.com/gitlab-org/gitlab/-/issues/358652

**Comment by timofurrer** [comment]
It should ™️ actually [be supported](https://docs.gitlab.com/ee/api/index.html#personalprojectgroup-access-tokens) and I remember to use PATs quite often (I can't verify right now, but maybe someone else can help out here .. @PatrickRice-KSC @jtymes @armsnyder)

How did you generate the PAT? May the scope be an issue or is it expired?

**Comment by Jasper-Ben** [comment]
👋 

> How did you generate the PAT? 

As mentioned above PATs generally work when generated via the web UI. I was able to use such a PAT with API permissions successfully as bearer token.
However, it does not work if the token is set programmatically, as described here: https://docs.gitlab.com/ee/user/profile/personal_access_tokens.html#create-a-personal-access-token-programmatically Feel free to try it yourself 🙂

> May the scope be an issue or is it expired?

Scope is set to "API", just like web ui generated token which works. And it isn't expired. As mentioned above, access using the PAT authentication works.

**Comment by Jasper-Ben** [comment]
So at this point I have tree possible explanations:

1. GitLab generally does not support bearer auth for programmatically generated tokens, which should at least be mentioned in their docs, ideally fixed.
2. There are some (technical) limitations on how a bearer token has to look like which my token does not fulfill, causing GitLab to silently fail while adding this token as bearer token. Again, this should then be at least documented by them. I am using `secrets.token_urlsafe(100)` to generate the token (https://docs.python.org/3/library/secrets.html#module-secrets)
3. I am just stupid and doing something wrong (PEBKAC is always a possibility :wink:). So I would be grateful if someone could try to reproduce my issue :slightly_smiling_face:

**Comment by Jasper-Ben** [comment]
P.S.: (Obviously) I have tested the PR I created and it fixes this issue for this provider. So if someone is reproducing my issue, feel free to also test my PR and see for yourself :+1:

**Comment by PatrickRice-KSC** [comment]
Hey @Jasper-Ben - While I'm not necessarily opposed to the PR you submitted, I'm having trouble reproducing the issue you're mentioning here. Here are the steps I tried:

- Spun up a gitlab-ee cluster in docker
- used the rails console to generate a programmatic token using the commands specified in their documentation, and changing the scope to `:api :read_api`:

```
gitlab-rails runner "token = User.find_by_username('root').personal_access_tokens.create(scopes: [:api, :read_api], name: 'Automation token'); token.set_token('token-string-here123'); token.save!"
```
- run the acceptance tests using `make testacc GITLAB_TOKEN=token-string-here123`

When I do that, I see the acceptance tests pass. Can you let me know what string value you're using for your token so I can test if maybe it's an issue there?

![image](https://user-images.githubusercontent.com/50960557/162631744-27a8369e-6ea8-4cc7-ae94-c41c3c575286.png)

**Comment by Jasper-Ben** [comment]
Hi @PatrickRice-KSC, that's interesting! I could successfully connect with bearer token using the `token-string-here123` string. However, when using a random token with char-length of 100, bearer token suddenly does not work any more.

So it seems like this is the case:

> There are some (technical) limitations on how a bearer token has to look like which my token does not fulfill, causing GitLab to silently fail while adding this token as bearer token. Again, this should then be at least documented by them.

Damn, now I wish had tested this earlier but I didn't really believe that this could be an issue. Was more like a "well, if nothing else works, I could try this in a desperate attempt" :sweat_smile: 

So the following works:

```
gitlab-rails runner "token = User.find_by_username('root').personal_access_tokens.create(scopes: [:api], name: 'Automation token'); token.set_token('token-string-here123'); token.save!"

curl --header "Authorization: Bearer token-string-here123" "https://gitlab.example.com/api/v4/user"

-> 200
```

The following does not:

```
gitlab-rails runner "token = User.find_by_username('root').personal_access_tokens.create(scopes: [:api], name: 'Automation token'); token.set_token('dotooK6teiWahkeideicha4aesaGhi7vaiHaigoo7pheWeeV3ein6Ohgoh9looGuis3veenge2ia3ii4phiamooTh9ieyohvoo2O'); token.save!"

curl --header "Authorization: Bearer dotooK6teiWahkeideicha4aesaGhi7vaiHaigoo7pheWeeV3ein6Ohgoh9looGuis3veenge2ia3ii4phiamooTh9ieyohvoo2O" "https://gitlab.example.com/api/v4/user"

-> 401
```

However, using the 100 char long token still works with private-token authorization:

```
curl --header "PRIVATE-TOKEN: dotooK6teiWahkeideicha4aesaGhi7vaiHaigoo7pheWeeV3ein6Ohgoh9looGuis3veenge2ia3ii4phiamooTh9ieyohvoo2O" "https://gitlab.example.com/api/v4/user"

-> 200
```

So after some trial and error I can now say that "41" is the magical max. length of a token which is still usable as bearer token...

Arrrrrgh :man_facepalming:

**Comment by PatrickRice-KSC** [comment]
@Jasper-Ben  - It's actually interesting that a length of 41 works! In their documentation, it states that [20 is the max length](https://docs.gitlab.com/ee/user/profile/personal_access_tokens.html#create-a-personal-access-token-programmatically)

![image](https://user-images.githubusercontent.com/50960557/162638903-fda5e2da-0d30-4ff1-a19a-f71fb4153074.png)

I'm kinda thinking we should close the PR (though I really appreciate the effort!) just because it feels like we should encourage users to follow the documented flows, and within the documented flows using a programmatic bearer token would work 🙂

**Comment by Jasper-Ben** [comment]
> @Jasper-Ben - It's actually interesting that a length of 41 works! In their documentation, it states that [20 is the max length]

Interesting! I totally overlooked that part... case of too stupid to RTFM I guess :rofl: Turns out it was a case of PEBKAC. Although to be fair it isn't exactly user-friendly to silently accept invalid tokens.

> I'm kinda thinking we should close the PR

For sure! Now I know what works, I am totally happy with how things are :+1:

**Comment by PatrickRice-KSC** [comment]
> Interesting! I totally overlooked that part... case of too stupid to RTFM I guess 🤣 Turns out it was a case of PEBKAC. Although to be fair it isn't exactly user-friendly to silently accept invalid tokens.

We've seen this in a couple places where the API silently accepts invalid values, it's definitely a bit obnoxious. Thanks for helping us triage this, it's always good to learn!

**Comment by Jasper-Ben** [comment]
Thanks for your input! :slightly_smiling_face:
