### ISSUE TITLE
Change detected in resource gitlab_project_access_token whereas there is no real change

### ISSUE THREAD

**Issue by MrLuje** [gitlabhq/terraform-provider-gitlab#1025]
### GitLab Provider version

3.12.0

### GitLab version

GitLab Community Edition 14.3.2

### Terraform version

1.1.8

### Relevant Terraform Configuration

```hcl
resource "gitlab_project_access_token" "token-read" {
  project = gitlab_project.project.id
  name    = format("REPO_%s-read", var.project_name)
  scopes  = ["read_repository"]
}
```

### Description

The gitlab api is timezone-sensitive. When running this terraform multiple time from the same computer, I don't have any issue.
Next, we moved the terraform to our CI server and we got the following change :

```hcl
~ resource "gitlab_project_access_token" "token-read" {
      ~ created_at = "2022-04-11 17:35:12.695 +0200 CEST" -> "2022-04-11 17:35:12.695 +0200 +0200"
        id         = "1630:237"
        name       = "REPO_Atlantis-read"
        # (6 unchanged attributes hidden)
    }
```

It looks like the created_at field got the proper timezoned-date but also includes the timezone from which the request has been made, which I don't think is relevant and should be omitted from the state

**Comment by PatrickRice-KSC** [comment]
Hm, we could potentially make the state file timezone independent by converting to GMT, but would that cause issues on the subsequent apply? Will need to test this with a local instance...

**Comment by MrLuje** [comment]
From what I understand, there are 2 timezone data :
```
2022-04-11 17:35:12.695 +0200 +0200
                           |     |-> timezone of the api request 
                           |-------> timezone of the server
```
The first timezone info doesn't change between both requests, which is expected because it holds "real" data
The second one seems like a "contextual" info of the request (from where the request has been made) which makes the state differs
So we could keep the first timezone info which is data-related but not the second, which is request-related

BTW, I noticed another usage of CreatedAt field (on resource_gitlab_group_access_token) on which the format is specified. Not sure if it fixes this issue but IMHO all date fields of the provider should have the same format
https://github.com/gitlabhq/terraform-provider-gitlab/blob/f283205925feacd2bd553541ee2df50986a9106b/internal/provider/resource_gitlab_group_access_token.go#L203

**Comment by PatrickRice-KSC** [comment]
I'll check that out when I test it this weekend and see if that resolves the issue. Seems like it should, given the RFC3339 standard only include one timezone format.

**Comment by PatrickRice-KSC** [comment]
Hey @MrLuje - I'm having trouble reproducing this issue to ensure that formatting the timestamp will resolve the issue. Here's what I did, let me know if you see anything weird with this (all of the below running in gitpod):

1. Added a "network" to our docker-compose file (used in downstream steps), and added a couple container names to our docker-compose to make them easier to reference from other docker containers.
2. Created an example terraform configuration to use with our CE container (mapped into the /code folder in subsequent steps):

```terraform
terraform {
  required_version = ">= 0.15"
  required_providers {
    gitlab = {
      source  = "gitlabhq/gitlab"
      version = "~> 3.13.0"
    }
  }
}
provider "gitlab" {
    token = "ACCTEST1234567890123"
    base_url = "http://ce:80"
}

resource "gitlab_project" "hello-world" {
  name = "cuddly_kittens"
}

resource "gitlab_project_access_token" "kitten-token" {
    project = gitlab_project.hello-world.id
    name = "snuggle"

    scopes = ["api"]
}
```

3. ran a docker container with terraform in it: `docker run -it -v $(pwd):/code --entrypoint /bin/ash --network="terraform-provider-gitlab_gitlab"  hashicorp/terraform`
4. ran `terraform init && terraform apply` in that docker container, saving the local state in the /code folder.
5. exited and destroyed the docker container from step 3
6. ran a _new_ docker container with terraform in it (to simulate the move to a CI/CD server): ` docker run -it -v $(pwd):/code --entrypoint /bin/ash --network="terraform-provider-gitlab_gitlab"  hashicorp/terraform`
7. Modified the timezone in the new container using `tzdata` (to GMT +2 - Brussels)
8. ran `terraform init && terraform apply`  again

**Expected**:  Changes should be flagged, and approval requested on the second run
**Got**: No changes were detected in the second run:

![image](https://user-images.githubusercontent.com/50960557/163686153-344bd8dc-3b8d-4030-b6ea-be6214e71ae6.png)

Any ideas?

**Comment by MrLuje** [comment]
@PatrickRice-KSC The repo steps look good but I confirm that I can't reproduce it either.
I will try to reproduce it this week on the server I initially had the issue on.

From the top of my mind, things that may have occured between the initial state and the CI move :
- DST changed (went from +1 to +2 during march)
- Gitlab upgrade (14.3.x to 14.9.x), I simulated this with docker and I had some unrelated changes due to container id change, but nothing regarding the date format
- Terraform state moved from local file to [gitlab backend](https://docs.gitlab.com/ee/user/infrastructure/iac/terraform_state.html#get-started-using-local-development) but again, no change regarding the time format
