### ISSUE TITLE
Consider implementing checks for correct GitLab instance setup

### ISSUE THREAD

**Issue by timofurrer** [gitlabhq/terraform-provider-gitlab#1027]
We should consider implementing checks to verify if the GitLab instance is correctly spun up.

The best place is probably the `healthcheck-and-setup.sh` or `await-healthy.sh` script.

_Originally posted by @timofurrer in https://github.com/gitlabhq/terraform-provider-gitlab/pull/1023#discussion_r851960590_

**Comment by Shocktrooper** [comment]
@timofurrer Any thoughts on which file is preferable?

**Comment by PatrickRice-KSC** [comment]
Seems like the healthcheck-and-setup is the right spot, just to make it idempotent.

**Comment by timofurrer** [comment]
I came to the conclusion that this will be not worth to implement - the effort is too big for what we'll gain. I'm going to close it.
