### ISSUE TITLE
Refactor cert generation for acceptance tests

### ISSUE THREAD

**Issue by timofurrer** [gitlabhq/terraform-provider-gitlab#1042]
Let's make sure that we properly configure the certs for the acceptance tests GitLab instance regarding subdomains etc.

***

I kinda dislike the naming of the re-used cert files here - since it's not only for the registry anymore. 

Also, is it configured properly for the pages to actually work? Regarding subdomains?

_Originally posted by @timofurrer in https://github.com/gitlabhq/terraform-provider-gitlab/pull/1041#discussion_r857144280_

**Comment by armsnyder** [comment]
Is this just for the pages feature? We'll keep running the GitLab API in plaintext mode yes?

**Comment by timofurrer** [comment]
Yes, exactly.
