### ISSUE TITLE
CI Variables causing failed plan on archived projects

### ISSUE THREAD

**Issue by aarmstrong-gel** [gitlabhq/terraform-provider-gitlab#1090]
### GitLab Provider version

3.13.0

### GitLab version

GitLab Enterprise Edition 15.0.0-pre 067b7295beb

### Terraform version

Terraform v1.1.8 on darwin_amd64

### Relevant Terraform Configuration

```hcl
data "gitlab_projects" "filtered" {
  group_id = <top level group id>

  per_page            = 50
  max_queryable_pages = 1000

  archived          = false
  include_subgroups = true
  order_by          = "id"
  simple            = true
  visibility        = "private"
  with_shared       = false
}

resource "gitlab_project_variable" "project_var" {
  for_each = data.gitlab_projects.filtered.id

  project   = each.value
  key       = "CI_VAR_KEY"
  value     = "CI_VAR_VALUE"
  masked    = true
  protected = false
}
```

### Relevant log output

```shell
Error: GET https://gitlab.com/api/v4/projects/<project_id>/variables/<CI_VAR>: 403 {message: 403 Forbidden}
```

### Description

We are deploying CI Variables to a group of projects. 
This works but we have some projects that can be archived between terraform runs.
When a project is archived, moved or deleted the provider reports a 403 Forbidden (as the variable at that address is no longer available).
We would expect this to be marked for deletion from the state file, rather than cause an error that fails the plan from completing.

**Comment by aarmstrong-gel** [comment]
Hi @timofurrer , thanks for getting in touch. 
Absolutely correct (misinterpretation on my behalf), I ran through this with a moved project, deleted project and archived project. This is only an issue when a project is archived (updated the title/comments).

I agree that the 403 return is fair enough due the project being in a readonly state. 
Will try and look into filtering out the archived projects with the archived param from `data.gitlab_projects`.

Thanks for your time,
Alex

**Comment by czomo** [comment]
Did you find any workaround for this? How would filtering archived projects would work?

**Comment by aarmstrong-gel** [comment]
From what I've understood you'll be denied access to the variable (now set to readonly) when archiving a project. You could look at your workflow to manage that. E.g. ensure the variables are removed from state before archiving or use an external vault (hashi, aws secrets man etc) would be paths I'd look down without knowing your use case. 
I'd suggest opening a new issue if there are any specifics you want to discuss or look at.
