### ISSUE TITLE
Add protected environments required_approval_count

### ISSUE THREAD

**Issue by thenom** [gitlabhq/terraform-provider-gitlab#1096]
### Feature Description

To allow you to control the required_approval_count via the gitlab_project_protected_environment resource

### Do you want to implement this?

- [X] I would like to implement this myself 👷

**Comment by timofurrer** [comment]
Thanks for raising this 🎉 

A few pointers for implementation:

* go-gitlab needs to support this first, see: https://github.com/xanzy/go-gitlab/blob/1ca150701fc8084feb459296cbd8b8a5ca8c544b/protected_environments.go#L37
* upstream API docs are [here](https://docs.gitlab.com/ee/api/protected_environments.html#:~:text=by%20a%20hash.-,required_approval_count,which%20isn%E2%80%99t%20yet%20available%20for%20use.%20For%20details%2C%20see%20issue.,-approval_rules)

**Comment by thenom** [comment]
Cheers @timofurrer , here is my PR for the dependency package:
https://github.com/xanzy/go-gitlab/pull/1482
