### ISSUE TITLE
New maintainers

### ISSUE THREAD

**Issue by nagyv** [gitlabhq/terraform-provider-gitlab#1100]
### Feature Description

I'd like to propose giving Maintainer rights to @PatrickRice-KSC and Triage rights to @Shocktrooper. 

Do you have any other candidates for maintainership? What do you think about giving them more responsibility?

@armsnyder @DonNicoJs @timofurrer @ro

### Do you want to implement this?

- [X] I would like to implement this myself 👷

**Comment by PatrickRice-KSC** [comment]
Always excited to help out more :)

I'm supportive of triage for @Shocktrooper  too!

**Comment by timofurrer** [comment]
@nagyv sounds good for me and since Adam also gave a 👍  I think you can put this in place 🎉

**Comment by nagyv** [comment]
Done.

Thanks for your support @PatrickRice-KSC and @Shocktrooper!
