### ISSUE TITLE
Emit owner access_token via gitlab_project_access_token

### ISSUE THREAD

**Issue by Nainterceptor** [gitlabhq/terraform-provider-gitlab#1138]
### GitLab Provider version

3.15.1

### GitLab version

Gitlab.com

### Terraform version

1.2.3

### Relevant Terraform Configuration

```hcl
resource "gitlab_project_access_token" "project_website" {
  project      = <redacted>
  name         = "terraform"
  access_level = "owner"

  scopes = ["api"]
}
```

### Relevant log output

```shell
│ Error: expected access_level to be one of [no one minimal guest reporter developer maintainer master], got owner
│ 
│   with gitlab_project_access_token.project_website,
│   on projects.tf line 33, in resource "gitlab_project_access_token" "project_website":
│   33:   access_level = "owner"
```

### Description

It's not possible to use "owner" access level, according to [access_level_helpers.go](https://github.com/gitlabhq/terraform-provider-gitlab/blob/main/internal/provider/access_level_helpers.go#L40), but API documentation say : 
- [Valid values are 10 (Guest), 20 (Reporter), 30 (Developer), 40 (Maintainer), and 50 (Owner)](https://docs.gitlab.com/ee/api/project_access_tokens.html#create-a-project-access-token)
- [Can have a maximum role of Owner for a project](https://docs.gitlab.com/ee/user/project/settings/project_access_tokens.html#bot-users-for-projects)

I can do a merge request to just add Owner to the list, but I don't know what it will be impacted.

**Comment by timofurrer** [comment]
Thanks @Nainterceptor for the report!

I've just created a PR to support `owner` as a valid value for `access_level` :)

**Comment by ignatenkobrain** [comment]
@timofurrer any chance there will be a release anytime soon? Thanks in advance for reply!

**Comment by timofurrer** [comment]
@ignatenkobrain Yes, I've just drafted a changelog PR [here](https://github.com/gitlabhq/terraform-provider-gitlab/pull/1163) and we'll have a release by end of this week. Stay tuned! 🎉

**Comment by ignatenkobrain** [comment]
│ Error: POST https://gitlab.com/api/v4/projects/37215813/share: 400 {error: group_access does not have a valid value}

=(
