### ISSUE TITLE
Implement a `gitlab_project_membership` data source

### ISSUE THREAD

**Issue by jeffqumata** [gitlabhq/terraform-provider-gitlab#1180]
### Feature Description

I'm starting to migrate my company's gitlab groups/users/etc into terraform. At the moment we have no need to directly manage projects in tf (there's a lot of them and we're happy to create them on gitlab.com) but one thing I need to ensure is that nobody outside an approved list of users has access to our projects. Basically all company projects should only be accessible by company employees.

My plan was to iterate over projects returned by the `gitlab_projects` data source and check the entries in the `project_membership` were all in my list of authorised users... but it seems there is no `project_membership` data source.

I appreciate that I have a non-typical use case but a `gitlab_project_membership` data source would make this possible. I assume since its already been declared as a resource it should be trivial to implement a similar data source?

### Do you want to implement this?

- [ ] I would like to implement this myself 👷

**Comment by timofurrer** [comment]
Thanks for the request! This data source has actually been in the making for quite some while already: https://github.com/gitlabhq/terraform-provider-gitlab/pull/593

I'll see that I can bring it to a mergeable state asap.

> My plan was to iterate over projects returned by the gitlab_projects data source and check the entries in the project_membership were all in my list of authorised users... but it seems there is no project_membership data source.

I'm kind of curious about your use case though: are you basically using terraform here *just to verify* if the members of the project are the matching a given set of *approved* users? 

What if it's not the case?

What I'm thinking is that you may want to actually make terraform "own" the project membership entire and therefore use the `gitlab_project_membership` resource.

**Comment by jeffqumata** [comment]
> I'm kind of curious about your use case though: are you basically using terraform here just to verify if the members of the project are the matching a given set of approved users?

That was the plan. #453 means that we cannot manage the full list of group or project members using the provider. I have worked around that for groups by using the `gitlab_group_membership` data source. I was planning to do the same for project membership (hence this issue). 

> What I'm thinking is that you may want to actually make terraform "own" the project membership entire and therefore use the gitlab_project_membership resource.

I dont think thats possible in my case - all users gain access to projects through group inheritance so my list of users for project membership needs to be empty and should remove anything which is already there (or at least throw an error)
