### ISSUE TITLE
Question: is it possible to manage Gitlab admin settings?

### ISSUE THREAD

**Issue by iverberk** [gitlabhq/terraform-provider-gitlab#1187]
I would like to use this provider to set a baseline configuration for Gitlab. For example to restrict the user project limit or disable sign-ups. Can it be done with the provider? I've scanned the issues and documentation but was unable to find a suitable resource.

**Comment by timofurrer** [comment]
It's currently not possible. I assume you are referring to basically managing the [Application settings API](https://docs.gitlab.com/ee/api/settings.html) in a resource with this provider, right?

@JanKoppe worked on this quite some time ago, see https://github.com/gitlabhq/terraform-provider-gitlab/issues/957
Are there any updates @JanKoppe from your side? Are you still interested in landing this in the provider? Should someone else take this over?

**Comment by filipowm** [comment]
@iverberk For the time being, I recommend you looking at [GitLab Configuration as Code](https://github.com/Roche/gitlab-configuration-as-code) (GCasC), which could do what you exactly expect, unfortunately outside of Terraform, but still easy to use (either manually or from within some CI/CD pipeline).

**Comment by JanKoppe** [comment]
Hey, no updates from my side on #957 - anyone who wants to work on it: Feel free to pick up where I left off! This is way down on my backlog right now.

Thank you so much @filipowm, this pretty much looks like it could help us out with the original issue, which prompted me to start work on such a resource.

During the development of such a resource we noticed more and more that this does not really fit the model of Terraforms state mangagement very well, and it seems like a dedicated tool could be the way to go here. Running an additional tool in the CD pipeline is a compromise we can live with very well. Will give this a spin in the coming days.

**Comment by timofurrer** [comment]
I'm closing this in favor of #957 and https://github.com/gitlabhq/terraform-provider-gitlab/pull/1201

**Comment by timofurrer** [comment]
We've implemented a first experimental version of a `gitlab_application_settings` resource which will be released with [v.3.17.0](https://github.com/gitlabhq/terraform-provider-gitlab/milestone/17). We'd appreciate feedback!
