### ISSUE TITLE
Inconsistent types of IDs and Group IDs

### ISSUE THREAD

**Issue by 1oglop1** [gitlabhq/terraform-provider-gitlab#1212]
### GitLab Provider version

3.1.3 - via https://github.com/pulumi/pulumi-gitlab/tree/v4.7.1

### GitLab version

saas

### Description

I used resource `resource_gitlab_group_share_group` and noticed that it requires two GroupIds but one is a string while the other is int.

https://github.com/gitlabhq/terraform-provider-gitlab/blob/746420e5e1eb4cef6a05e2d023231d20bc5e0db6/internal/provider/resource_gitlab_group_share_group.go#L32-L38

While API supports both int and string https://docs.gitlab.com/ee/api/projects.html#share-project-with-group

ref: pulumi/pulumi-gitlab/issues/28

**Comment by timofurrer** [comment]
The situation with the Terraform schema is that an attribute can only have a single type - thus we use a `string` when a `string` and `integer` is allowed and `integer` when only an `integer` is allowed.

For these APIs (btw. the link to the API is not the one from the code you've referenced, but is besides the point I guess 😊 ) it's documented that the [project](https://docs.gitlab.com/ee/api/projects.html#share-project-with-group:~:text=to%20share%20with.-,id,The%20ID%20or%20URL%2Dencoded%20path%20of%20the%20project.,-expires_at) / [group](https://docs.gitlab.com/ee/api/groups.html#share-groups-with-groups:~:text=POST%20/groups/%3Aid/share,path%20of%20the%20group) id for which the group is shared with can be an `integer` or a `string` and in the terraform provider is therefore a `string` - but it works with an `integer` and `string`. However, the group that is shared (according to the documentation, see [here](https://docs.gitlab.com/ee/api/projects.html#share-project-with-group:~:text=grant%20the%20group.-,group_id,The%20ID%20of%20the%20group%20to%20share%20with.,-id) and [here](https://docs.gitlab.com/ee/api/projects.html#share-project-with-group:~:text=grant%20the%20group.-,group_id,The%20ID%20of%20the%20group%20to%20share%20with.,-id)) must be an `integer`. 

I haven't checked if this could theoretically be a `string`, too. I may check later or if you tried it and it works for sure and by intention, let me know and we could think of changing the provider schema type to a `string` to - unless it wouldn't be backwards compatible.

**Comment by 1oglop1** [comment]
Thank you for the information, I rely on the provider and just found types to be "weird". 
It seems like ID used to be an integer until the Gitlab team found out integers are not good enough for IDs and started changing the API. Therefore this seems to be an upstream problem which I'm not sure that the terraform provider can do anything about it.

If my assumption is true we can probably close this issue.

**Comment by timofurrer** [comment]
I'm pretty confident that IDs are technically enough - but often it's nice to have more readable descriptive name ids instead of numerical ids.

> If my assumption is true we can probably close this issue.

Great! I'm going to close it - let us know if you need anything else :)
