### ISSUE TITLE
Merge request self-approval

### ISSUE THREAD

**Issue by ndarwincorn** [gitlabhq/terraform-provider-gitlab#123]
One of the last gaps for our use of this provider is enabling self-approval of merge requests.

I'll take a look at making time to contribute a PR for this.

Many thanks to y'all for the work on the provider in the last few months. It's gone from not doing much for us to being able to mostly automate our project creation process (and help me sleep better from a DR perspective if we ever needed to stand up our own gitlab instance).

**Comment by armsnyder** [comment]
Can you clarify if this is for project-level approval settings or merge-request-level approval settings?

Assuming it's project-level, I propose adding a `gitlab_project_merge_request_approvals` resource for this API https://docs.gitlab.com/ee/api/merge_request_approvals.html#project-level-mr-approvals

**Comment by ndarwincorn** [comment]
Definitely project-level. When I opened this it was blocked (at least from having tests) by #157. I see that's no longer the case. And that's the correct API call as well.

If I can make the time I'll open a PR that adds the resource.

**Comment by armsnyder** [comment]
@ndarwincorn [gitlab_project_level_mr_approvals](https://registry.terraform.io/providers/gitlabhq/gitlab/latest/docs/resources/project_level_mr_approvals) was added and released recently in 3.0.0 of the provider. Thanks for offering to add the resource, but it looks like we can close this!
