### ISSUE TITLE
Unable to perform Update Operations on Gitlab projects from 3.16.0 version onwards

### ISSUE THREAD

**Issue by sandeepanumula92** [gitlabhq/terraform-provider-gitlab#1241]
### GitLab Provider version

3.16.0

### GitLab version

14.9.2-ee

### Terraform version

0.13.4

### Relevant Terraform Configuration

```hcl
resource "gitlab_project" "project"{
All the project settings/properties goes here like id, name, path, ci_config_path etc
}
```

### Relevant log output

```shell
Error: PUT https://gitlab.com/api/v4/projects/project_id: 403 {message 403 forbidden}

err="rpc error: code=Unavailable desc =transport is closing"
```

### Description

We are trying to update the gitlab project settings through terraform but it fails with PUT 403 forbidden error from 3.16.0 version onwards

We are able to perform the same the operations manually using command line/postman with same gitlab access token and on same project.

Till 3.15.0 version, this works fine with terraform

**Comment by Shocktrooper** [comment]
Hello! @sandeepanumula92 apologies but the version of GitLab you are using is out of our support range which matches GitLab with only supporting the previous 3 minor releases (As of this comment is 15.1, 15.2, 15.3).

With the `gitlab_project` resource and a few others there were some changes made in the newer versions of the provider to support the ongoing changes that GitLab themselves made with their API.  If you could update your tools to the latest stable versions and see if this issue still happens then it would be appreciated and we could troubleshoot further if the issue still arises.  Feel free to re-open a new issue if the above recommendation does not work.

That being said if you are to keep on the older version of GitLab a workaround for you would be to alias the resources that are not working to the 3.16.1 version of the provider or whichever version works for you.

https://www.terraform.io/language/providers/configuration#alias-multiple-provider-configurations
