### ISSUE TITLE
Gitlab access token broken on  >3.16.1

### ISSUE THREAD

**Issue by gabrieloandco** [gitlabhq/terraform-provider-gitlab#1246]
### GitLab Provider version

>3.16.1

### GitLab version

GitLab Enterprise Edition 14.1.7-ee

### Terraform version

v1.1.5

### Relevant Terraform Configuration

```hcl
resource "gitlab_project_access_token" "kubernetes" {

  project    = var.kubernetes.project
  name       = "Acess token for ${var.project}"

  scopes = [
    "read_repository",
    "write_repository"
  ]
}
```

### Relevant log output

```shell
│ Error: Provider produced inconsistent result after apply │ │ When applying changes to module.gitlab_project_x.gitlab_project_access_token.kubernetes[0], provider "provider["registry.terraform.io/gitlabhq/gitlab"]" produced an unexpected │ new value: Root resource was present, but now absent. │ │ This is a bug in the provider, which should be reported in the provider's own issue tracker.
```

### Description

Gitlab providers fails on creating access tokens on newest versions,  workaround was to roll back the version to 3.16.1

**Comment by Shocktrooper** [comment]
Hello @gabrieloandco apologies but the version of GitLab you are using is out of our support range which matches GitLab with only supporting the previous 3 minor releases (As of this comment is 15.1, 15.2, 15.3).  

That being said if you are to keep on the older version of GitLab a workaround for you would be to alias the resources that are not working to the 3.16.1 version of the provider or whichever version works for you.

https://www.terraform.io/language/providers/configuration#alias-multiple-provider-configurations
