### ISSUE TITLE
Cannot manage already existing projects

### ISSUE THREAD

**Issue by SomaGallai** [gitlabhq/terraform-provider-gitlab#1247]
### GitLab Provider version

3.18.0

### GitLab version

GitLab Enterprise Edition 15.4.0-pre b9548e306fe

### Terraform version

Terraform v1.2.6

### Relevant log output

```shell
│ Error: POST https://gitlab.com/api/v4/projects: 400 {message: {name: [has already been taken]}, {path: [has already been taken]}}
│ 
│   with gitlab_project.templates["project-template"],
│   on group-templates.tf line 19, in resource "gitlab_project" "templates":
│   19: resource "gitlab_project" "templates" {
│ 
╵
```

### Description

When doing `terraform apply` to manage already existing GitLab projects it throws an error 400 as the name has already been used. I am not trying to create a new project I would like to make sure all of my projects share the same configurations inside them, is that possible using this provider?

**Comment by timofurrer** [comment]
> [..] is that possible using this provider?

Yes, this is absolutely possible with this provider.

 However, what you are looking for are Terraform imports, which [migrate existing infrastructure to be managed by Terraform](https://www.terraform.io/cli/import#:~:text=Terraform%20is%20able%20to%20import%20existing%20infrastructure.%20This%20allows%20you%20take%20resources%20you%27ve%20created%20by%20some%20other%20means%20and%20bring%20it%20under%20Terraform%20management.).

So, given a `<project-id>` you can run `terraform import gitlab_project.<resource-name> <project-id>` to import - which you'll manage with a resource definition like this:

```hcl
resource "gitlab_project" "<resource-name>" {
   project = "<project-id>"
   
   ...
}
```

Did that answer your question?

**Comment by SomaGallai** [comment]
> > [..] is that possible using this provider?
> 
> Yes, this is absolutely possible with this provider.
> 
> However, what you are looking for are Terraform imports, which [migrate existing infrastructure to be managed by Terraform](https://www.terraform.io/cli/import#:~:text=Terraform%20is%20able%20to%20import%20existing%20infrastructure.%20This%20allows%20you%20take%20resources%20you%27ve%20created%20by%20some%20other%20means%20and%20bring%20it%20under%20Terraform%20management.).
> 
> So, given a `<project-id>` you can run `terraform import gitlab_project.<resource-name> <project-id>` to import - which you'll manage with a resource definition like this:
> 
> ```terraform
> resource "gitlab_project" "<resource-name>" {
>    project = "<project-id>"
>    
>    ...
> }
> ```
> 
> Did that answer your question?

Thank you very much for the explanation, I would like to ask if there is any faster way to import a lot of projects or does it have to be this one-by-one?

**Comment by timofurrer** [comment]
No, there isn't something out of the box. Depending on your situation a little scripting with curling the GitLab API and passing it to tf imports may help :)
