### ISSUE TITLE
Documentation includes unsupported argument

### ISSUE THREAD

**Issue by octopus20** [gitlabhq/terraform-provider-gitlab#1255]
### GitLab Provider version

3.18.0

### Terraform version

1.2.9

### Relevant Terraform Configuration

```hcl
resource "gitlab_group_saml_link" "test123" {
  group_id        = "12345"
  access_level    = "developer"
  saml_group_name = "samlgroupname1"
}
```

### Relevant log output

```shell
│ Error: Missing required argument
│
│   on main.tf line 24, in resource "gitlab_group_saml_link" "test13":
│   24: resource "gitlab_group_saml_link" "test13" {
│
│ The argument "group" is required, but no definition was found.
╵
╷
│ Error: Unsupported argument
│
│   on main.tf line 25, in resource "gitlab_group_saml_link" "test13":
│   25:   group_id        = "devops-test1"
│
│ An argument named "group_id" is not expected here.
```

### Description

In provider documentation [here](https://registry.terraform.io/providers/gitlabhq/gitlab/latest/docs/resources/group_saml_link) the resource uses `group_id` to link saml group with gitlab group, but after terraform applied the resource is shows the `group_id` is not supported argument and  argument "group" is required, but no definition was found.

**Comment by timofurrer** [comment]
Unfortunately, the example in the docs is wrong. Supported is `group` and not `group_id`.

Thanks for the report! I've fixed it in #1256 🎉
