### ISSUE TITLE
creating a gitlab branch results in a 500 Internal Server Error

### ISSUE THREAD

**Issue by jfuller28495** [gitlabhq/terraform-provider-gitlab#1287]
### GitLab Provider version

13.15.0

### GitLab version

Gitlab 15.4.2 version ee

### Terraform version

1.3.3

### Relevant Terraform Configuration

```hcl
resource "gitlab_project" "project" {
  provider = gitlab
  name         = var.project_name
  description  = var.project_description
  namespace_id = data.gitlab_group.group.id
  default_branch = "development"
  issues_enabled = false
  request_access_enabled = false
  merge_requests_enabled = true
  pipelines_enabled = true
  approvals_before_merge = 1
  wiki_enabled = false
  snippets_enabled = true
  container_registry_enabled = false
  lfs_enabled = false
  visibility_level = "private"
  merge_method = "ff"
  only_allow_merge_if_pipeline_succeeds = true
  only_allow_merge_if_all_discussions_are_resolved = true
  shared_runners_enabled = false
  archived = false
  initialize_with_readme = true
}

resource "gitlab_branch" "qa" {
  name    = "qa"
  ref     = "development"
  project = gitlab_project.project.id
}
```

### Relevant log output

```shell
$ terraform apply terraform.plan || true
module.new_repo.gitlab_project.project: Creating...
module.new_repo.gitlab_project.project: Creation complete after 4s [id=456]
module.new_repo.gitlab_branch_protection.qa: Creating...
module.new_repo.gitlab_branch.qa: Creating...
module.new_repo.gitlab_branch.production: Creating...
module.new_repo.gitlab_branch_protection.production: Creating...
module.new_repo.gitlab_branch_protection.development: Creating...
module.new_repo.gitlab_branch_protection.qa: Creation complete after 0s [id=456:qa]
module.new_repo.gitlab_branch_protection.development: Creation complete after 0s [id=456:development]
module.new_repo.gitlab_branch_protection.production: Creation complete after 0s [id=456:production]
module.new_repo.gitlab_branch.qa: Still creating... [10s elapsed]
module.new_repo.gitlab_branch.production: Still creating... [10s elapsed]
╷
│ Error: POST https://gitlab-development.redacted.com/api/v4/projects/456/repository/branches: 500 {message: 500 Internal Server Error}
│ 
│   with module.new_repo.gitlab_branch.production,
│   on project-build/main.tf line 35, in resource "gitlab_branch" "production":
│   35: resource "gitlab_branch" "production" {
│ 
╵
╷
│ Error: POST https://gitlab-development.redacted.com/api/v4/projects/456/repository/branches: 500 {message: 500 Internal Server Error}
│ 
│   with module.new_repo.gitlab_branch.qa,
│   on project-build/main.tf line 51, in resource "gitlab_branch" "qa":
│   51: resource "gitlab_branch" "qa" {
│ 
╵
```

### Description

I'm unable to create branches via terraform after this latest version update, every attempt throws a 500 internal server error. I walked through the existing Gitlab provider versions starting at latest (3.18.0) and then stepping back from 3.12.0 to 3.15.0 and I didn't find a version that would work for me to build these branches. Creation of the project still works as expected. Previous versions (v13 / v14 of Gitlab) had this working fine with terraform, so my suspicion is that this is a product of updating to the v15.x.x Gitlab versions. I didn't see any existing issues on this error, apologies if this is a duplicate.

**Comment by Shocktrooper** [comment]
@jfuller28495 not sure if this could be it but there were some changes to initializing with readme made recently and I wonder if this affected your initialization.  I have not ran into this myself on the latest version of GitLab and the provider but I can try sometime later.  Before that happens if you could find the 500 error in your logs that should tell you more about the issue you are having.  Also running with TF_LOG=DEBUG might be able to help as well

**Comment by jfuller28495** [comment]
we think we've sorted this out on our end - it was a buried config in our filehook settings that was preventing adding new branches without certain requirements met, and it was preventing our automation from creating the required branches at initialization time since the automation couldn't place a file and create the branch at the same time like you can from a local IDE. will reopen if this ends up not being the case. Thanks!~
