### ISSUE TITLE
Update test matrix to new GitLab versions

### ISSUE THREAD

**Issue by PatrickRice-KSC** [gitlabhq/terraform-provider-gitlab#1301]
### Feature Description

This issue will update the test matrix to the newly released versions of GitLab.

### Do you want to implement this?

- [X] I would like to implement this myself 👷

**Comment by PatrickRice-KSC** [comment]
@nagyv | @timofurrer | @armsnyder  | @Shocktrooper   - The reason most of the actions are failing, after some examination, is because our license we use for our GitLab is expired 😨 . Just to confirm, I dug back into the PR submitted to change it, and @armsnyder  did indeed mention it expired in August 2022.

@nagyv - would you be able to get us a new ultimate license generated, so we can get that updated and get our actions passing again?

**Comment by timofurrer** [comment]
I've completely missed that comment, but yes, I can confirm and noticed that, too. See #1304 .

I'm working on getting the license and I'll update the repo asap.
