### ISSUE TITLE
[Feature Request] Repository mirroring configuration

### ISSUE THREAD

**Issue by mauleb** [gitlabhq/terraform-provider-gitlab#150]
Howdy!

It would be handy to be able to configure repository mirroring for a project.

Thanks!

**Comment by unacceptable** [comment]
Here is a link to the documentation on how this is done.

https://docs.gitlab.com/ee/user/project/repository/repository_mirroring.html#setting-up-a-push-mirror-from-gitlab-to-github-core

I think that this would be amazing when coupled with other providers.

**Comment by unacceptable** [comment]
I started to look into building something, but I couldn't find an API spec.  It looks like the functionality isn't publicly accessible. 😕 

https://docs.gitlab.com/ee/api/api_resources.html#project-resources

I found the following issues relating to this as well:

https://gitlab.com/gitlab-org/gitlab/issues/1499
https://gitlab.com/gitlab-org/gitlab/issues/7599

I also watched network traffic in Developer Tools in Chrome while manually doing this in the public gitlab.  Here are the results:

```
Request URL: https://gitlab.com/aztek-io/example/mirror
Request Method: POST
Status Code: 302 Found
Remote Address: 35.231.145.151:443
Referrer Policy: origin-when-cross-origin

Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
Cache-Control: no-cache
Connection: keep-alive
Content-Length: 674
Content-Type: application/x-www-form-urlencoded
Cookie: REDACTED
Host: gitlab.com
Origin: https://gitlab.com
Pragma: no-cache
Referer: https://gitlab.com/aztek-io/example/-/settings/repository
Sec-Fetch-Mode: navigate
Sec-Fetch-Site: same-origin
Sec-Fetch-User: ?1
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36

utf8: ✓
_method: patch
authenticity_token: REDACTED
url: https://user@example.com/something.git
mirror_direction: push
project[remote_mirrors_attributes][0][enabled]: 1
project[remote_mirrors_attributes][0][url]: https://user@example.com/something.git
project[remote_mirrors_attributes][0][only_protected_branches]: 0
project[remote_mirrors_attributes][0][ssh_known_hosts]: 
project[remote_mirrors_attributes][0][auth_method]: password
project[remote_mirrors_attributes][0][password]: asdfasdfasdfasdf
```
I will look tomorrow to see if it is possible to generate the cookies used in the console wiht the programatic access keys, but I am not going to hold my breath.  Hopefully this functionity is added to the API soon.

**Comment by FelikZ** [comment]
Hey, will this output `ssh public key` that generated after successful mirroring setup?
![image](https://user-images.githubusercontent.com/1080269/68212074-1bbf0380-ffd9-11e9-9bf1-e42dd3d15931.png)

This is an essential part to create a webhook for in the old GIT provider to have close to realtime sync.

**Comment by lukemgriffith** [comment]
The original issues are closed, and it looks like they publish a API spec now 
https://docs.gitlab.com/ee/api/remote_mirrors.html
@unacceptable  did you managed to start anything? or is this up for grabs

**Comment by jocelynthode** [comment]
@unacceptable Anything new on your front or has asked before is this up for grabs?

**Comment by lukemgriffith** [comment]
As of yesterday, my PR into go-gitlab was complete to support this functionality. I'm working on a branch to implement this into the provider.

https://github.com/xanzy/go-gitlab/pull/879

**Comment by JanisOrlovs** [comment]
Is there any estimates when this feature could be merged?

**Comment by lukemgriffith** [comment]
@FelikZ  currently thats not supported by the gitlab mirrors API, wont be something that can be implemented into go-gitlab or the terraform provider. go-gitlabs current implementation works with host based provided credentials via SSH or HTTPS.

**Comment by armsnyder** [comment]
This was recently added via #358 and will be in the next release.
