### ISSUE TITLE
[Feature Request] Change allowed merge request approvers

### ISSUE THREAD

**Issue by boomshadow** [gitlabhq/terraform-provider-gitlab#162]
Greetings!

It would be nice to be able to manage the list of which users are allowed to handle merge requests on a project. GitLab has an API for this feature: https://docs.gitlab.com/ee/api/merge_request_approvals.html#change-allowed-approvers

**Comment by gdubicki** [comment]
This API is deprecated since GitLab 12.3 released in September 2019. We should use https://docs.gitlab.com/ee/api/merge_request_approvals.html#project-level-mr-approvals API instead.

**Comment by gdubicki** [comment]
Oh, this is almost merged. See https://github.com/terraform-providers/terraform-provider-gitlab/pull/208 and https://github.com/terraform-providers/terraform-provider-gitlab/pull/250 .

**Comment by armsnyder** [comment]
PR for this #208

**Comment by nicholasklick** [comment]
Solved via: https://github.com/gitlabhq/terraform-provider-gitlab/pull/250
