### ISSUE TITLE
[Feature Request] Add users and groups to gitlab_branch_protection

### ISSUE THREAD

**Issue by richwine** [gitlabhq/terraform-provider-gitlab#165]
It looks like `gitlab_branch_protection` resource currently only supports `access_level` (referred to as Roles in Gitlab UI). [The API](https://docs.gitlab.com/ee/api/protected_branches.html#example-with-user--group-level-access-starter) also supports `user_id` and `group_id`. Would be fantastic to have those available as well.

**Comment by armsnyder** [comment]
PR for this #329

**Comment by mgriffin13** [comment]
It doesn't look like there has been any movement on the linked PR since Oct 2020. This issue is a blocker for me to implement some security controls on managed Gitlab projects.

**Comment by armsnyder** [comment]
@jasoncarlsen @jeremad It looks like you both have PRs open for this (#329, #443). Could you let us know if you're able to continue working on them, or if you need any assistance?

**Comment by jasoncarlsen** [comment]
@armsnyder Apologies for the delayed response.  I won't have any time in the near future to work on it.  @sirlatrom has offered to carry it to a new PR.

**Comment by sirlatrom** [comment]
> 
> 
> @armsnyder Apologies for the delayed response. I won't have any time in the near future to work on it. @sirlatrom has offered to carry it to a new PR.

As far as I understood from the design discussion, we want to stick as closely to the GitLab API as possible, right?

Here's a redacted API response, which I think should direct the state structure:

```json
[
  {
    "id": 1605,
    "name": "master",
    "push_access_levels": [
      {
        "access_level": 40,
        "access_level_description": "Maintainers",
        "user_id": null,
        "group_id": null
      }
    ],
    "merge_access_levels": [
      {
        "access_level": 30,
        "access_level_description": "Developers + Maintainers",
        "user_id": null,
        "group_id": null
      }
    ],
    "unprotect_access_levels": [],
    "code_owner_approval_required": true
  },
  {
    "id": 1630,
    "name": "feature/iamroot",
    "push_access_levels": [
      {
        "access_level": 40,
        "access_level_description": "[REDACTED]",
        "user_id": 2,
        "group_id": null
      },
      {
        "access_level": 40,
        "access_level_description": "[REDACTED]",
        "user_id": null,
        "group_id": 101
      },
      {
        "access_level": 40,
        "access_level_description": "Maintainers",
        "user_id": null,
        "group_id": null
      }
    ],
    "merge_access_levels": [
      {
        "access_level": 40,
        "access_level_description": "[REDACTED]",
        "user_id": 3,
        "group_id": null
      },
      {
        "access_level": 40,
        "access_level_description": "[REDACTED]",
        "user_id": null,
        "group_id": 101
      },
      {
        "access_level": 30,
        "access_level_description": "Developers + Maintainers",
        "user_id": null,
        "group_id": null
      },
      {
        "access_level": 40,
        "access_level_description": "Maintainers",
        "user_id": null,
        "group_id": null
      }
    ],
    "unprotect_access_levels": [],
    "code_owner_approval_required": true
  }
]
```

**Comment by armsnyder** [comment]
@sirlatrom Thanks for offering to pick this up! Your proposed structure highlights something interesting: The structure of the POST request body is fundamentally different from the structure of the response body. I'm fine with aligning with the response structure as you have suggested. @roidelapluie do you have thoughts on that, since it's a unique situation? API: https://docs.gitlab.com/ee/api/protected_branches.html#protect-repository-branches

**Comment by armsnyder** [comment]
One challenge to watch out for, if using the response structure, is that some of the POST API fields are premium-tier only. So you would need some logic in the `create` function to ensure that the resource is still usable for non-premium users.

**Comment by sirlatrom** [comment]
@armsnyder Quoting from the [docs](https://docs.gitlab.com/ee/api/protected_branches.html#example-with-user--group-level-access):

> Example with user / group level access premium
> 
> Elements in the allowed_to_push / allowed_to_merge / allowed_to_unprotect array should take the form {user_id: integer}, {group_id: integer} or {access_level: integer}. Each user must have access to the project and each group must have this project shared. These access levels allow more granular control over protected branch access and were added to the API in GitLab 10.3 EE.

This may help to explain the difference between the POST arguments and the returned data structure.

**Comment by armsnyder** [comment]
I opened #550 to talk Gitlab versions some more, but I would think 10.3 is out of support for us.
