### ISSUE TITLE
Feature Request: ability to trigger Gitlab CI Pipeline as Provisioner

### ISSUE THREAD

**Issue by Andor** [gitlabhq/terraform-provider-gitlab#182]
Hello!

That's could be cool of we will have the feature to trigger gitlab-ci pipeline from Terraform. I guess via provisioner provider.

Example of code:
```hcl
resource "aws_instance" "instance" {
  count = 3
  ...
  provisioner "gitlab-ci-pipeline" {
    project = "my-gitlab-project"
    branch = "branch-to-trigger-pipeline-on"
    variables = {
      host_to_provision = aws_instance.myinstance[count.index].private_ip
    }
    wait = true
  }
}
```

Yeah, I know this is possible with `local-exec` and `curl`, but you may agree it is not so nice anyhow.

Also I personally run Terraform from docker container and it is simplier to not continain `curl` inside.

**Comment by armsnyder** [comment]
Hashicorp doesn't seem to distribute third party provisioners https://www.terraform.io/docs/extend/how-terraform-works.html#discovery

And they are pretty clear about provisioners being a last resort because Terraform's intended use is for managing graphs of stateful resources.

**Comment by FernandoMiguel** [comment]
one of the big changes of TF v0.13 is namespace for providers

https://github.com/hashicorp/terraform/pull/24477

> As part of implementing a new decentralized namespace for providers, Terraform now requires an explicit source specification for any provider that is not in the "hashicorp" namespace in the main public registry. (More details will be added about this prior to release, including links to upgrade steps.)

**Comment by armsnyder** [comment]
@FernandoMiguel Yes, but my understanding of the issue was that it was asking for a provisioner, which is different from a provider. Based on the doc I linked and [this issue](https://github.com/hashicorp/terraform/issues/20896) it doesn't seem to be a supported plugin type.
