### ISSUE TITLE
[Feature Request] new resource type gitlab_pipeline_schedule_variable

### ISSUE THREAD

**Issue by mkjmdski** [gitlabhq/terraform-provider-gitlab#184]
Current implementation of gitlab_pipeline_schedule doesn't allow to define custom variables, but there is an endpoint in API which allow to create those variables https://docs.gitlab.com/ee/api/pipeline_schedules.html#create-a-new-pipeline-schedule-variable

**Comment by armsnyder** [comment]
Fixed via #204
