### ISSUE TITLE
Feature request: Add more supported services

### ISSUE THREAD

**Issue by Andor** [gitlabhq/terraform-provider-gitlab#192]
Gitlab has plenty of supported 3rd party services to integrate: [API](https://docs.gitlab.com/ee/api/services.html).

Terraform Gitlab Provider supports only Slack and Jira services.

I would be rather nice to add more supported types of services to this lovely terraform provider.

Right now I'm personally interested in [YouTrack](https://docs.gitlab.com/ee/api/services.html#youtrack) integration, but support for other services would be helpful for some other people as well.

**Comment by trietsch** [comment]
I agree with this. I'm mostly interested in the Hangouts / Google Chat integration. Maybe it's possible to generalize this, so that there's no need to create a dedicated resource for each integration that GitLab offers?

**Comment by armsnyder** [comment]
Superseded by #607
