### ISSUE TITLE
[Bug] environment_scope for resource gitlab_project_variable defaults to 0 instead of *

### ISSUE THREAD

**Issue by kherpel** [gitlabhq/terraform-provider-gitlab#195]
Hi,

We have run into an issue with the gitlab_project_variable resource. We have several Gitlab variables defined using Terraform. After the upgrade to 0.12.11 the variables were not set in the CI pipeline. After investigating we found that the new version automatically set the environment_scope to "0" which results in a new scope listed in the Gitlab CI/CD variable settings. This new scope is not used by the CI/CD pipeline resulting in missing variable values during the deployment. After adding `environment_scope = "*"` to the Terraform script the correct scope "All environments" was set.

Kind regards,
Kristian

### Terraform Version

Docker image hashicorp/terraform with version 0.12.11
Plugin for provider "gitlab" (terraform-providers/gitlab) 2.3.0

### Affected Resource(s)

- environment_scope

### Terraform Configuration Files
```hcl
resource "gitlab_project_variable" "api_set_logging_s3_bucketname_staging" {
  key     = "AWS_S3_BUCKET_NAME_STAGING"
  project = gitlab_project.api.id
  value   = aws_s3_bucket.s3_logging_staging.bucket
}
```

### Debug Output
```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

# gitlab_project_variable.api_set_logging_s3_bucketname_staging will be updated in-place
  ~ resource "gitlab_project_variable" "api_set_logging_s3_bucketname_staging" {
      + environment_scope = "0"
        id                = "90:AWS_S3_BUCKET_NAME_STAGING"
        key               = "AWS_S3_BUCKET_NAME_STAGING"
        masked            = false
        project           = "90"
        protected         = false
        value             = (sensitive value)
        variable_type     = "env_var"
    }
``` 

### Expected Behavior

* If not defined in resource the environment_scope value should be set to "*" for All environments

### Actual Behavior

* environment_scope is set to non-existing scope "0"

### Steps to Reproduce

1. Create gitlab_project_variable resource with key, project and value (was created with older version in Gitlab by older Terraform version )
2. Run terraform plan

**Comment by gbrunacci** [comment]
I second to this, my env vars set via terraform are useless by default unless I set `environment_scope = "*"`.

Default behavior should be all environments.

**Comment by spuder** [comment]
Also seeing this

```hcl
data "gitlab_project" "foobar" {
  id = "42"
}

# This should not have an environment scope. Terraform is mistakenly setting it to `0`
resource "gitlab_project_variable" "foobar-dev" {
  project   = "42"
  key       = "NOMAD_TOKEN"
  value     = "1111111111111"
  protected = false
  masked    = true
}

resource "gitlab_project_variable" "foobar-qa" {
  project           = "1691"
  key               = "NOMAD_TOKEN"
  value             = "222222222222"
  protected         = true
  masked            = true
  environment_scope = "qa"
}
```

![Screenshot 2020-04-26 10 10 31](https://user-images.githubusercontent.com/242382/80313125-50e92900-87a6-11ea-8441-a8da06da42c5.png)

**Comment by woz5999** [comment]
anyone have any idea how to get someone to review and merge the PR i submitted?
