### ISSUE TITLE
[Bug] Unsupported argument: commit_committer_check 

### ISSUE THREAD

**Issue by LipingSun** [gitlabhq/terraform-provider-gitlab#202]
Hi there,

Getting error when `setting commit_committer_check` in `gitlab_project_push_rules`. According to [document](https://www.terraform.io/docs/providers/gitlab/r/project_push_rules.html#commit_committer_check), `commit_committer_check` should be supported.

### Terraform Version
+ Terraform v0.12.12
+ provider.gitlab v2.3.0

### Affected Resource(s)
- gitlab_project_push_rules

### Panic Output
```
Error: Unsupported argument

  on modules/gitlab_project/main.tf line 24, in resource "gitlab_project_push_rules" "push_rules":
  24:   commit_committer_check = true

An argument named "commit_committer_check" is not expected here.
```

**Comment by timofurrer** [comment]
This code has been refactored from the `gitlab_project_push_rules` resource into the `gitlab_project` resource. I'm going to close this, because it's very attic and seems solved 🎉 

If someone still experiences this issue, please open a new one :)
