### ISSUE TITLE
Destroy acceptance tests not tested properly + duplicated code

### ISSUE THREAD

**Issue by kirecek** [gitlabhq/terraform-provider-gitlab#205]
Hello, I noticed that many destroy tests do checks only for the absence of a parent resource (i.e. gitlab_project and gitlab_group) and delete function for a particular resource is not tested at all (they are only called by terraform).

What's worse, most of these destroy tests are duplicated code. For example, the following tests are the same.

- [x] [testAccCheckGitlabPipelineScheduleDestroy](https://github.com/terraform-providers/terraform-provider-gitlab/blob/master/gitlab/resource_gitlab_pipeline_schedule_test.go#L130)
- [x] [testAccCheckGitlabPipelineTriggerDestroy](https://github.com/terraform-providers/terraform-provider-gitlab/blob/master/gitlab/resource_gitlab_pipeline_trigger_test.go#L99)
- [x] [testAccCheckGitlabProjectPushRulesDestroy](https://github.com/terraform-providers/terraform-provider-gitlab/blob/master/gitlab/resource_gitlab_project_push_rules_test.go#L165)
- [x] [testAccCheckGitlabProjectHookDestroy](https://github.com/terraform-providers/terraform-provider-gitlab/blob/master/gitlab/resource_gitlab_project_hook_test.go#L155)
- [x] [testAccCheckGitlabServiceJiraDestroy](https://github.com/terraform-providers/terraform-provider-gitlab/blob/master/gitlab/resource_gitlab_service_jira_test.go#L106)
- [x] [testAccCheckGitlabServiceSlackDestroy](https://github.com/terraform-providers/terraform-provider-gitlab/blob/master/gitlab/resource_gitlab_service_slack_test.go#L126)
- [x] [testAccCheckGitlabLabelDestroy](https://github.com/terraform-providers/terraform-provider-gitlab/blob/master/gitlab/resource_gitlab_label_test.go#L114)
- [x] [testAccCheckGitlabProjectVariableDestroy](https://github.com/terraform-providers/terraform-provider-gitlab/blob/master/gitlab/resource_gitlab_project_variable_test.go#L111)

I think it deserves some refactoring. Does it make sense to take some action here?

**Comment by armsnyder** [comment]
Still a weak point of our tests
