### ISSUE TITLE
Support for project_creation_level on groups

### ISSUE THREAD

**Issue by dr4Ke** [gitlabhq/terraform-provider-gitlab#210]
This is a feature request to add the `project_creation_level` parameters to the `gitlab_groups` resource.

### Terraform Version
Terraform v0.12.13
+ provider.gitlab v2.3.0

### Affected Resource(s)
- gitlab_groups

### Terraform Configuration Files
```hcl
resource "gitlab_group" "mygroup" {
  name        = "mygroup"
  path        = "mygroup"
  description = "My group description"
  visibility_level = "internal"
  project_creation_level = "noone"
}
```
In this example, I added the inexistent `project_creation_level`. Gitlab supports these values:
- `noone`
- `maintainer`
- `developer`

**Comment by justinkillen** [comment]
+1

**Comment by justinkillen** [comment]
Missing in xanzy/go-gitlab.  Issue/PR: https://github.com/xanzy/go-gitlab/issues/762

**Comment by justinkillen** [comment]
WIP: https://github.com/justinkillen/terraform-provider-gitlab/tree/more_group_options

**Comment by justinkillen** [comment]
https://github.com/terraform-providers/terraform-provider-gitlab/pull/257

**Comment by justinkillen** [comment]
Also adds additional fields:

* AutoDevopsEnabled
* EmailsDisabled
* MentionsDisabled
* SharedRunnersMinutesLimit
* ExtraSharedRunnersminutesLimit

**Comment by justinkillen** [comment]
Could use some help resolving test issues: https://github.com/terraform-providers/terraform-provider-gitlab/pull/362

**Comment by dr4Ke** [comment]
I'm sorry I won't be able to help much as I just left for the holidays and don't have my work env at hand.
