### ISSUE TITLE
Incorrect project environment variable lookup

### ISSUE THREAD

**Issue by abelmokadem** [gitlabhq/terraform-provider-gitlab#213]
### Terraform Version
```
$ terraform -v
Terraform v0.12.13
+ provider.vault v2.6.0
```

### Affected Resource(s)
Please list the resources as a list, for example:
- gitlab_project_variable

### Terraform Configuration Files
```hcl
resource "gitlab_project_variable" "vault-role-id" {
  key               = "VAULT_ROLE_ID"
  value             = vault_approle_auth_backend_role.app-role.role_id
  project           = var.project.gitlab_project.id
  environment_scope = "development"
  protected         = var.gitlab_protected_environment
}

resource "gitlab_project_variable" "vault-role-id" {
  key               = "VAULT_ROLE_ID"
  value             = vault_approle_auth_backend_role.app-role.role_id
  project           = var.project.gitlab_project.id
  environment_scope = "production"
  protected         = var.gitlab_protected_environment
}
```

### Description
The GitLab project environment variable lookup is incorrect. In GitLab an environment variable can have the same name in multiple environment scopes. However, the GitLab api doesn't support this on the REST api that is used in the source code of this provider. So what happens is that the wrong environment variable is being read when refreshing the state.

Solving this would be to fetch the list of all project variable and find the variable with the corresponding name and environment_scope.
```
/api/v4/projects/<project_id>/variables
```

**Comment by jakubigla** [comment]
Basically environment_scope becomes useless if this is not implemented. 
I had such a nice design with variables distribution to CI pipeline purposes and now I need to bin it :)

**Comment by abelmokadem** [comment]
@jakubigla Same here, you can use it to create environment variables for different scopes. That part works, but afterwards you can't modify or delete them. In our case that is fine for now but we really need this to be fixed so that we can also update variables and remove the lifecycle ignore in our codebase.

**Comment by oesah** [comment]
I have the same issue, staging pipeline overrides production environment scope and vice versa. Cannot create two variables with the same name in 2 different scopes. Any workarounds to this?

**Comment by oesah** [comment]
So, basically it is documented here: https://github.com/terraform-providers/terraform-provider-gitlab/blob/master/gitlab/resource_gitlab_project_variable.go#L117

The feature is just commented out, but I don't fully understand the reason why. Anyone an idea?

**Comment by jakubigla** [comment]
The workaround is:
```
lifecycle {
    ignore_changes = [ value ]
  }
```

**Comment by oesah** [comment]
@jakubigla Thanks for the hint, but what I did instead is:

1. Install Golang
2. Pull the repository
3. Uncomment line `gitlab/resource_gitlab_project_variable.go#L117`
4. Build the binary with golang using `terraform-provider-gitlab_v2.4.0_x4`
5. Copy that binary into the folder you are using your terraform commands from
6. Re init terraform

I tried it just now and it seems that line uncommented resolves the issue. My question would be, why was this commented out. It says due to "configuration drift", but doesn't that also apply to the other properties like masked?

**Comment by oesah** [comment]
Unfortunately, my solution described one comment earlier does not seem to work when I run it in Gitlab Pipeline. I am getting the following error:
```
Error: Failed to instantiate provider "gitlab" to obtain schema: fork/exec /builds/bosg/op-infra/cluster/terraform-provider-gitlab_v2.4.0_x4: exec format error
```

Strangely, it works on my local machine. Trying to figure out why.

**Comment by abelmokadem** [comment]
@oesah is your GitLab runner using the same architecture as your local machine? Are you on a mac or linux? And what is your GitLab docker container running? You might be able to solve this problem  by building the binary inside the docker container that you use for your pipeline.

**Comment by oesah** [comment]
Yes, my Mac uses darwin_64 while the pipeline uses linux_64. I guess that's the issue then, thanks for the tip. Will try to build it in the pipeline.

**Comment by roidelapluie** [comment]
New release is out with the fix

**Comment by wesselvdv** [comment]
I see, but it's still an issue. Seems that having multiple variables with the same name, but different environment scope is suffering from some sort of ordering issue. Plans are now always showing changes for both value and scope.

**Comment by abelmokadem** [comment]
@roidelapluie there is another issue indeed. It's what I mentioned in my issue. The lookup for the variables is incorrect.

```
Description
The GitLab project environment variable lookup is incorrect. In GitLab an environment variable can have the same name in multiple environment scopes. However, the GitLab api doesn't support this on the REST api that is used in the source code of this provider. So what happens is that the wrong environment variable is being read when refreshing the state.

Solving this would be to fetch the list of all project variable and find the variable with the corresponding name and environment_scope.

/api/v4/projects/<project_id>/variables
```

**Comment by wesselvdv** [comment]
@roidelapluie Can this be reopened? This issue is clearly not fixed, if any it has become more apparent in the current release.

**Comment by oesah** [comment]
@abelmokadem I can confirm, this did not fix the issue. However, now we see how it should work and why it isn't.

I checked this repository, but I see that we are using v4 api. I think the real issues lie here: https://github.com/xanzy/go-gitlab/blob/master/group_variables.go#L84
https://github.com/xanzy/go-gitlab/blob/master/project_variables.go#L86

In both calls, they are simply asking for the the project ID and variable name, since Gitlab API does not allow filtering per environment scope (yet).

So I understand what you mean now. I think the issue needs to be reported in https://github.com/xanzy/go-gitlab though. I will open an issue there and hopefully we get a fix soon. Then the this release (2.5.0) should work out of the box I guess.

**Comment by oesah** [comment]
The root problem goes back to Gitlab itself. You can follow the issue here: https://github.com/xanzy/go-gitlab/issues/746

**Comment by woz5999** [comment]
I've made a fork of the provider to work around this issue using ListVariables to lookup scoped variables.  Would it be worth putting in a pull request for this? Not sure if the maintainers would rather wait for an upstream api fix or have something that works now.

**Comment by roidelapluie** [comment]
@woz5999 can we decide over the PR?

**Comment by woz5999** [comment]
Nevermind. After some more testing, you can successfully do the lookup easy enough, but there's no still deterministic way to actually update/delete the correct var.

**Comment by abelmokadem** [comment]
We resorted to just deleting and recreating variables in GitLab. It sucks because we have to deploy our terraform project twice.

**Comment by s256** [comment]
As an idea, we currently use the API for Varibale details (https://docs.gitlab.com/ee/api/project_level_variables.html#show-variable-details) which only filter for the key and not the scope. If we would use the json provided by the project (https://docs.gitlab.com/ee/api/project_level_variables.html#list-project-variables) we would also get the scope of the variables. 

like this:

`[{"variable_type":"env_var","key":"REPOSITORY_URL","value":"foobar.com","protected":false,"masked":false,"environment_scope":"stage"},{"variable_type":"env_var","key":"REPOSITORY_URL","value":"foobar.com","protected":false,"masked":false,"environment_scope":"prod"}]`

it is a hack as we don't want all the other information, but we could work with it and get correct diffs.

https://docs.gitlab.com/ee/api/project_level_variables.html#update-variable  updates the values according to the scope. So don't think we need to wait for github here.

**Comment by woz5999** [comment]
@s256 I think the problem when I looked into this is that the update-variable API still isn't deterministic. There's no way to specify which scoped variable you want to modify, so even if you can PUT the environment scope in the payload, it will just update a random variable with the given name/key. I'd be thrilled if I end up being wrong, but that's the issue that forced me to abandon a fix.

Here's my aborted attempt: https://github.com/woz5999/terraform-provider-gitlab/commit/73ffb4fc2d9b527c58e6a9a9173a23cb09baaa75

**Comment by abelmokadem** [comment]
I think there should be a gigantic warning sign on this resource... This is really messed up.

**Comment by s256** [comment]
I didn't test the update-variable API, but I will. If that's true, we're talking about completely different issue in gitlab here. Will get back to you asap.

**Comment by s256** [comment]
Using curl to access the API leaves me more confused.

I think it's really a bug in the update variable API. I just opened a support request with gitlab.

If you have more than one scope of a variable, the api wouldn't let you update other scopes except the first one you created.

Steps to reproduce:
```
# Create Var in scope "dev"
curl --request POST --header "PRIVATE-TOKEN: ************" "https://gitlab.acme.com/api/v4/projects/1/variables" --form "key=testvar" --form "value=bar" --form "environment_scope=dev"

# Works (update Scope:dev)
curl --request PUT --header "PRIVATE-TOKEN: ************" "https://gitlab.acme.com//api/v4/projects/1/variables/testvar" --form "value=test" --form "environment_scope=dev"

#Works of course (new scope "stage")
curl --request POST --header "PRIVATE-TOKEN: ************" "https://gitlab.acme.com//api/v4/projects/1/variables" --form "key=testvar" --form "value=bar" --form "environment_scope=stage"

# Update scope "stage" fails with: {"message":{"key":["(testvar) has already been taken"]}}
curl --request PUT --header "PRIVATE-TOKEN: ************" "https://gitlab.acme.com//api/v4/projects/1/variables/testvar" --form "value=test" --form "environment_scope=stage"

# Update Still works with Scope "dev"
curl --request PUT --header "PRIVATE-TOKEN: ************" "https://gitlab.acme.com//api/v4/projects/1/variables/testvar" --form "value=change_back" --form "environment_scope=dev"
 ```

If this gets fixed, this issue should resolve itself and we don't need an extra filter for the api the get the variables of a specific scope, as we can use the list api.

**Comment by techthumb** [comment]
#324 aims to resolve this issue

**Comment by s256** [comment]
Gitlab is providing a fix in the next version:
https://gitlab.com/gitlab-org/gitlab/-/issues/9912#note_377146498

**Comment by jakubigla** [comment]
Few days ago GitLab has enabled a feature flag that has fixed the API but has broken this resource completely.
When can we expect a fix?

**Comment by Nainterceptor** [comment]
It break our terraform deployment file currently :/

**Comment by wesselvdv** [comment]
This is turning into a major issue now.

**Comment by roidelapluie** [comment]
Can you share with us more details about the issue?

**Comment by woz5999** [comment]
Per https://gitlab.com/gitlab-org/gitlab/-/issues/9912, the underlying API changed, breaking this resource.

**Comment by jakubigla** [comment]
Sure thing, although it feels  github.com/xanzy/go-gitlab needs to be fixed first...

Basically the issue was introduced in this file: https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/api/variables.rb by enabling a feature flag. If there's more than one variable with the same name (diff env scope), it will fail if you don't provide `environment_scope` filter in the request. This is a new thing and neither this provider nor go library support this filter. 
Therefore, when running Terraform plan in this scenario is producing the following error (as the mentioned earlier ruby file indicates): 

```Error: GET https://gitlab.com/api/v4/projects/xxxxx/variables/AWS_ACCESS_KEY_ID: 409 {message: There are multiple variables with provided parameters. Please use 'filter[environment_scope]'}
```

**Comment by woz5999** [comment]
Looks like there's an open issue and possible code fix here: https://github.com/xanzy/go-gitlab/issues/746

**Comment by futebolbryant** [comment]
This is terrible and dirty but this is how I'm managing my gitlab variables until it's fixed:

```
locals {
  gitlab_output_file_name = "../convert_gitlab_vars.sh"

  non_static_vars = {
    "EXAMPLE_VAR": someresource.name.attr,
    "ANOTHER_EXAMPLE_VAR": someresource.name.attr,
  }

  // i have two variables for workspace specific variables vs global
  all_vars = merge(local.non_static_vars, var.gitlab_base_env_vars, var.gitlab_env_specific_env_vars)
}

resource "gitlab_project_variable" "all" {
  for_each = local.all_vars

  project = var.gitlab_api_project_id
  key = "${each.key}_${var.env}"
  value = each.value
  protected = true
  environment_scope = var.env
}

resource "null_resource" "gitlab_var_output" {

  triggers = {
    // trigger file recreation on any variable change
    gitlab_vars = base64encode(jsonencode(gitlab_project_variable.all))
  }

  provisioner "local-exec" {
    command = <<EOT
    $(rm ${local.gitlab_output_file_name} || true) && echo "#!/bin/bash" >> ${local.gitlab_output_file_name}

    %{ for env_var_key in values(gitlab_project_variable.all)[*].key ~}
      TRIMMED_ENV_VARKEY="${ replace(env_var_key, "_${var.env}", "")}"
      echo $TRIMMED_ENV_VARKEY
      echo "eval export $TRIMMED_ENV_VARKEY=\\\\$'"$TRIMMED_ENV_VARKEY"_'\$CI_BUILD_REF_NAME" >> ${local.gitlab_output_file_name}
    %{ endfor ~}

EOT
  }
}

```

This creates a file "convert_gitlab_vars.sh" with exports translating the variables to their base name based on the CI environment:

`eval export EXAMPLE_VAR_ONE=\$'EXAMPLE_VAR_ONE_'$CI_BUILD_REF_NAME`
`eval export EXAMPLE_VAR_TWO=\$'EXAMPLE_VAR_TWO_'$CI_BUILD_REF_NAME`

Then in my .gitlab-ci.yml:

```
before_script:
  - source convert_gitlab_vars.sh
```

Variables then accessible by the 'base name': i.e. `EXAMPLE_VAR_ONE`

**Comment by tyronedd** [comment]
@nicholasklick bumping this up, since this is really breaking my workflow Terraform and Gitlab.

**Comment by Nainterceptor** [comment]
@nicholasklick Sorry to add noise in the thread, but I just received an email from gitlab to renew our gold licence, but our terraform workflow is broken since 28 days (according to my last message here)…

How can we help ?

**Comment by nicholasklick** [comment]
https://github.com/gitlabhq/terraform-provider-gitlab/pull/324 seems like a temporary fix. We will further evaluate it.

**Comment by mathieux51** [comment]
My temporary fix:
```
resource "null_resource" "kubeconfig" {
  triggers = {
    kubeconfig = module.eks.kubeconfig
  }
  provisioner "local-exec" {
    interpreter = ["/bin/sh", "-c"]
    command     = <<EOF
curl \
  -g --include \
  --request DELETE \
  --header "PRIVATE-TOKEN: ${var.gitlab_access_token}" \
    "https://gitlab.com/api/v4/projects/${var.project_id}/variables/KUBECONFIG?filter[environment_scope]=${var.environment}"

curl \
  --include \
  --request POST \
  --header "PRIVATE-TOKEN: ${var.gitlab_access_token}" "https://gitlab.com/api/v4/projects/${var.project_id}/variables" \
  --form "key=KUBECONFIG" \
  --form "value=${chomp(module.eks.kubeconfig)}" \
  --form "protected=false" \
  --form "variable_type=file" \
  --form "masked=false" \
  --form "environment_scope=${var.environment}"
EOF
  }
}
```

**Comment by abelmokadem** [comment]
I'm getting really desperate now, I just made a mistake in a whole lot of projects and I have no mechanism to fix this using terraform. 

@mathieux51 how do you ensure that these variables get destroyed when the resource is removed?

**Comment by mathieux51** [comment]
@abelmokadem As it's a _temporary fix_ I usually remove them manually using Gitlab UI. Maybe there is a way to do it automatically but I don't know it yet.
