### ISSUE TITLE
Implement gitlab_project.build_access_level

### ISSUE THREAD

**Issue by jsirex** [gitlabhq/terraform-provider-gitlab#234]
```
400 {message: {name: []}, {project_feature.builds_access_level: [cannot have higher visibility level than repository access level]}}
```

**Comment by armsnyder** [comment]
Hi @jsirex, I couldn't find a parameter called `build_access_level` in the [project API docs](https://docs.gitlab.com/ee/api/projects.html). Can you give us some more information about the feature?

**Comment by jsirex** [comment]
It was long time ago. If API have changed, probably this ticket is not actual anymore..

**Comment by armsnyder** [comment]
Ok, I'm going to close the issue then. Please re-open it if you have more information about the feature. Thanks!
