### ISSUE TITLE
Can't create project for a user

### ISSUE THREAD

**Issue by nishant-jain-94** [gitlabhq/terraform-provider-gitlab#238]
Hi,

I am trying to **Create Project for User** using the Terraform Gitlab Provider. Gitlab API provides a way to create a Project for a User using this API Endpoint. Is there a way where we could do achieve the same thing using the Terraform Gitlab Provider

### Terraform Version
Terraform v0.12.12

### Affected Resource(s)
Please list the resources as a list, for example:
- gitlab_project

### Terraform Configuration Files
```hcl
resource "gitlab_project" "this" {
  name                                  = "test-project-one"
  path                                  = "test-project-one"
  description                           = "Test Description"
  namespace_id                          = "<ID_OF_USER>"
  only_allow_merge_if_pipeline_succeeds = true
  visibility_level                      = "private"
}
```

### Expected Behavior
Expected the project to be created under the user

### Actual Behavior
Throws HTTP Error 400. namespace id is not valid.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

**Comment by zoonfafer** [comment]
A user's namespace_id is not the same as the user's ID.  Get the user's namespace_id with this:

```console
$ curl --silent \
  --request GET \
  --header "Content-Type: application/json" \
  --header "Authorization: Bearer ${GITLAB_TOKEN}" \
  "https://gitlab.com/api/v4/namespaces/${GITLAB_USER}" | jq -r .id
```

Until there is a data source for GitLab namespaces, you may have to make do with the above.

**Comment by armsnyder** [comment]
Let's move this discussion over to #85. I'm interested in if you have thoughts on a namespace datasource versus adding a new attribute to the existing project resource.
