### ISSUE TITLE
Data source gitlab_user not transferring all values to state

### ISSUE THREAD

**Issue by mcrmonkey** [gitlabhq/terraform-provider-gitlab#249]
### Terraform Version
```
> terraform_0.12.20 -v
Terraform v0.12.20
+ provider.gitlab v2.5.0
```

### Affected ~Resource(s)~ Data source(s)
- gitlab_user

### Terraform Configuration Files
```hcl
provider "gitlab" {
  token   = var.gitlab_token
}

data "gitlab_user" "work_account" {
  username = "antk-cts"
}
```

### Debug Output
https://gist.github.com/mcrmonkey/0ed0da5e1f2826776148c616f54395d7

Note: Some values have been omitted such as paths, email addresses, company name and API tokens. Final state is included in the gist.

### Panic Output
There was no panic.

### Expected Behavior
Details such as `two_factor_enabled` etc should be transferred through to the state

### Actual Behavior
Only basic details such as the `name`, `username`, `user_id` are transferred to state

### Steps to Reproduce

Ensure you have a valid gitlab api token to use

1. `terraform init`
2. `terraform plan -out=terraform.plan -var gitlab_token=<token>`
3. `terraform apply terraform.plan`

### Important Factoids
The additional fields and the associated values are noted in the plan

### References
- #193 hints at some import issues with an email address and is one of the fields that is missing from the data source in the state

**Comment by ubdb** [comment]
To make the importance of the bug more obvious - the result is that imported users will be replaced when running terraform plan.
So importing users is not working or usable.

```
  # module.sxris-user.gitlab_user.res_gl_user["yelouarti"] must be replaced
-/+ resource "gitlab_user" "res_gl_user" {
      ~ can_create_group  = true -> false
      + email             = "xxxx@domain.com" # forces replacement
      ~ id                = "118" -> (known after apply)
      + is_admin          = false
      + is_external       = false
        name              = "xxxx xxxx"
      + password          = (sensitive value)
        projects_limit    = 0
      + reset_password    = false
      + skip_confirmation = true
        username          = "xxxxxxx"
    }

```

**Comment by ubdb** [comment]
workaround for using s3 with dynamo for state+locking:
- copy terraform state from s3 to local filesystem
- edit terraform state, set email and initial password
- copy terraform state from local filesystem to s3
- run terraform plan (exits with error)
- copy shown digest into dynamo table used for terraform locking row: <bucket>/env:/<workspace>/terraform.tfstate-md5 field: Digest
- re-run terraform plan (shouldn't show the same error again)
- be happy

**Comment by ilpianista** [comment]
FYI I added some of those attributes to the state in #261

**Comment by armsnyder** [comment]
Merged #261 so the resource should be fixed in the next provider release at least.

I looked at the `data_source_gitlab_user_test.go` test and sure enough it does not cover the attributes that you mentioned, so there could be a bug with the data source still.

**Comment by armsnyder** [comment]
Based on my reading of the API https://docs.gitlab.com/ee/api/users.html#for-user the `two_factor_enabled` field is only returned if an admin API token is used.

**Comment by armsnyder** [comment]
Looks like the data source was fixed via #102 . Can you try the latest release of the provider?

**Comment by mcrmonkey** [comment]
It does seem to be performing better than it was :+1: 

Re: `two_factor_enabled` yes, you're right its only exposed to admin people - although it is exposed to group admin's in the UI but thats not for here 

Thanks :)

**Comment by armsnyder** [comment]
Thanks for checking! Is it alright to close this issue?

**Comment by mcrmonkey** [comment]
yep 'm fine with this :+1:
