### ISSUE TITLE
Feature Request: more granular handling of gitlab_project.tags

### ISSUE THREAD

**Issue by randomswdev** [gitlabhq/terraform-provider-gitlab#252]
Hi there,

### Affected Resource(s)
gitlab_project, tag attribute

The tag attribute allows to assign topics (the tags name was replaced because of confusion with git tags) to a GitLab project. But when assigning a list of topics, all the project topics are replaced with the ones in the list. This does not allow to manage a set of topics with Terraform, while allowing manual management of additional topics.
The users associated with a GitLab project can be managed both by Terraform and manually as far as the two sets are disjoint. I would like to have something similar also for the topics.

### Terraform Configuration Files
An example Terraform configuration file could be:
```hcl
resource "gitlab_project" "example" {
  name        = "example"
  description = "My awesome codebase"

  visibility_level = "public"
}

resource "gitlab_project_topic" "topic1" {
   project   = gitlab_porject.example.id
   value     = "my-first-topic"
}

resource "gitlab_project_topic" "topic1" {
   project   = gitlab_porject.example.id
   value     = "my-second-topic"
}
```

### Expected Behavior
In the example above, Terraform should just take care of associating the two topics above to the project, without removing or altering additional topics that could be associated with the project.

### Additional comments
If you think that the proposal sounds reasonable, I can take care of contributing a pull request to implement the change.

**Comment by QuingKhaos** [comment]
I'm 👎🏻 on this, as I see the tags/topics similar to tags on AWS resources. If you manage the tags on AWS resources it manages all of them and reconciles them if they're changed outside of Terraform. The same behavior applies to GitLab project tags/topics here.

The general rule, if you manage something with Terraform, don't manage parts of it outside of Terraform. I know the provider doesn't support everything, but what is supported should be only managed by Terraform.

You can still ignore changes to the tags after creating to allow manual edits:

```terraform
resource "gitlab_project" "example" {
  name        = "example"
  description = "My awesome codebase"

  visibility_level = "public"

  tags = ["foo", "bar"]

  lifecycle {
    ignore_changes = [tags]
  }
}
```

**Comment by PatrickRice-KSC** [comment]
FYI @timofurrer  - The bot removed your stale tag 😆

**Comment by timofurrer** [comment]
... you haven't noticed, but in this case you are the stale bot 😂  Going to close :) Please let us know if there are still issues.

(no seriously - thanks for the reminder ;))
