### ISSUE TITLE
gitlab_group_cluster diff on kubernetes_ca_cert on each apply 

### ISSUE THREAD

**Issue by MPV** [gitlabhq/terraform-provider-gitlab#256]
### Affected Resource(s)
Please list the resources as a list, for example:
- `gitlab_group_cluster`

### Terraform Configuration Files
```hcl
resource "gitlab_group_cluster" "mycluster" {
  # ...
  base64decode(azurerm_kubernetes_cluster.mycluster.kube_config.0.cluster_ca_certificate)
}
```

### Expected Behavior

No diff after first apply.

### Actual Behavior

Diff after every subsequent apply.

### Steps to Reproduce

1. `terraform apply`

### Workarounds

Add trimspace() around the cert, like this:

Before:
```hcl
base64decode(azurerm_kubernetes_cluster.mycluster.kube_config.0.cluster_ca_certificate)
```

After:
```hcl
trimspace(base64decode(azurerm_kubernetes_cluster.mycluster.kube_config.0.cluster_ca_certificate))
```

### References

First discovered/mentioned here: https://github.com/terraform-providers/terraform-provider-gitlab/pull/178#issuecomment-584125798

**Comment by MPV** [comment]
Looking at the code, it seems the tests apply `trimspace()`:
https://github.com/terraform-providers/terraform-provider-gitlab/pull/178/files#diff-1347dce80447b815000aa96c3cae80bbR228

...but not the example usage:
https://github.com/terraform-providers/terraform-provider-gitlab/pull/178/files#diff-c96ecf54d16275172e04bc7e3b33ff83R31

(or better yet: the implementation, so you wouldn't need to do it yourself)

**Comment by roidelapluie** [comment]
This should be skipped by the provider, in a DiffSuppressFunc.

**Comment by magic7s** [comment]
@MPV does it perform different as a Project Cluster?

**Comment by MPV** [comment]
@magic7s I'm sorry, but I haven't been able to try that myself in my context. Feel free to give it a try.

**Comment by bschoenmaeckers** [comment]
I'm experiencing this as well with the project cluster. The workaround seems to work as well with the project scoped one.

**Comment by sereinity** [comment]
My temporary solution is
```tf
lifecycle {
  ignore_changes = [
    kubernetes_ca_cert,
  ]
}
```

**Comment by Nainterceptor** [comment]
Hello, 

Same issue here, with [scaleway provider](https://github.com/scaleway/terraform-provider-scaleway/issues/788).

It's better to wrap with trimspace than use ignore_changes in my case, because it will detect and update if someone regenerate the kubeconfig from scaleway console.

Best regards,
Gaël

**Comment by armsnyder** [comment]
We probably need the same change from #665 to his resource.
