### ISSUE TITLE
Create a CONTRIBUTING.md

### ISSUE THREAD

**Issue by richardc** [gitlabhq/terraform-provider-gitlab#26]
The main terraform project has notes on how to contribute, and guidance for maintainers, but it's not immediately obvious when looking at this repo in isolation.

Add suitable linking to the README.md, or a new CONTRIBUTING.md, or something. 

https://github.com/hashicorp/terraform/blob/master/docs/maintainer-etiquette.md

**Comment by richardc** [comment]
Promoting from the comments of #5

**Comment by roidelapluie** [comment]
should be implemented in https://github.com/terraform-providers/terraform-provider-template

**Comment by armsnyder** [comment]
Agreed, we should have a CONTRIBUTING.md. @nicholasklick since you're most familiar with GitLab values, would you want to start one?

**Comment by armsnyder** [comment]
#427 has some data which might be useful.

**Comment by armsnyder** [comment]
It would also be good to ask folks to read the [Hashicorp provider design principles](https://www.terraform.io/docs/extend/hashicorp-provider-design-principles.html), since we often link to it in PR feedback.

**Comment by armsnyder** [comment]
I have seen some new PRs containing `//lintignore` comments, probably because the codebase as-is has linter issues. We should clarify that new code should adhere to linters if possible, and ideally point to some good example code where there are no issues.
