### ISSUE TITLE
password doesn't work?

### ISSUE THREAD

**Issue by h3adache** [gitlabhq/terraform-provider-gitlab#280]
I'm using 
```
Terraform v0.12.23
+ provider.gitlab v2.5.0
```
and `GitLab12.8.6`

I defined a user resource with a password of `"testing"`.
The user is created fine but cannot log in with the password.
I set `reset_password = false`.

I don't know if this is a known issue as I can't find it in any reported issues

**Comment by armsnyder** [comment]
@h3adache I'm unable to reproduce this with provider.gitlab v2.11.0. Logging in with the configured password is working. Can you confirm whether you're still having this problem?

**Comment by h3adache** [comment]
Hi @armsnyder! 
Sorry for the late response.
I don't have access to that project anymore but it was using a previous version of gitlab provider.
I'll setup a new project using the latest gitlab provider and let you know today.
Thanks!

**Comment by h3adache** [comment]
I just tried this using the latest provider and it seems to work now.
Thanks!

**Comment by armsnyder** [comment]
Thank you for checking!
