### ISSUE TITLE
[Feature request]: Allow setting container expiration policy 

### ISSUE THREAD

**Issue by abeluck** [gitlabhq/terraform-provider-gitlab#286]
Please consider adding the `container_expiration_policy_attributes` argument from the Gitlab Projects API.

This allows one to configure containers to automatically expire according to certain rules.

* API: https://docs.gitlab.com/ee/api/projects.html#edit-project
* Attribute: `container_expiration_policy_attributes`

**Comment by Shocktrooper** [comment]
Looks like the required go-gitlab work is done for this to be implemented here as well.  I might take a shot at this as my first go project
