### ISSUE TITLE
Avoid "Too many requests" by providing some form of exponential back off logic

### ISSUE THREAD

**Issue by ysb33r** [gitlabhq/terraform-provider-gitlab#287]
I think it would be great if some form of back off logic can be implented, I am running into 429 issues with a non-trivial configuration. (I have 173 entities in mine).

I can easily reproduce this issue with `plan` or `apply` with or without `-refresh`. Even doing `-parrallelism=1` is not enough.

### Terraform Version
* Terraform 0.12.1
* provider.gitlab v2.5.0

### Affected Resource(s)
Please list the resources as a list, for example:
data.gitlab_group x1
data.gitlab_user x13
gitlab_branch_protection x42
gitlab_group x3
gitlab_group_membership x13
gitlab_group x4
gitlab_project x32
gitlab_project_push_rules x32
gitlab_service_slack x32

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Expected Behavior
Slow down number of requests as to not exceed Gitlab's rate limit.

### Actual Behavior
429 HTTP codes prevents the operation from completing. The exact place where it fails is slightly random. It just depends no when the rate limit is hit.

### Steps to Reproduce
```
$terraform apply -refresh=true 
```

### References
See [Gitlab Rate Limit documentation](https://docs.gitlab.com/ee/user/gitlab_com/index.html#gitlabcom-specific-rate-limits)

**Comment by oboukili** [comment]
Apparently, as I understand it, the go-gitlab client already [ensures a rate limiter is configured on the client](https://github.com/xanzy/go-gitlab/blob/30361b69e2e4a328a2c919df055b7b877e30e782/gitlab.go#L589-L589).
If you're experiencing 429 it might mean some API calls the provider makes use another client, silently eating up the rate limit quota (needle in a haystack).
I'm almost sure I saw in the code that a pooled connection client was being used for the provider Gitlab client, so this reinforces that hypothesis I guess.

**Comment by armsnyder** [comment]
I didn't find anything about multiple clients in the provider. It's possible that other API usage of GitLab is affecting the provider client's quota. Maybe this can be fixed by configuring the client with a [custom retry](https://github.com/xanzy/go-gitlab/blob/v0.37.0/client_options.go#L38) behavior.

**Comment by timofurrer** [comment]
I'm going to close this for now. If it comes up again, please let us know! 🎉
