### ISSUE TITLE
Feature request - "Allowed to create projects" on groups

### ISSUE THREAD

**Issue by rhysjtevans** [gitlabhq/terraform-provider-gitlab#293]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
gitlab version 2.5

### Affected Resource(s)
Please list the resources as a list, for example:
- gitlab_group

It would be great if the option for 
"Allowed to create projects" on Group properties could be added current options are 
- No one
- Maintainers
- Developers + Maintainers

**Comment by armsnyder** [comment]
There's a WIP PR for this #257

**Comment by armsnyder** [comment]
Fixed via #362 new attribute `project_creation_level` in the next release.
