### ISSUE TITLE
gitlab_deploy_key_enable should implement can_push

### ISSUE THREAD

**Issue by sebastianortizs4n** [gitlabhq/terraform-provider-gitlab#294]
Hi there,

gitlab provider resource `gitlab_deploy_key_enable` should also support the `can_push` argument of the `gitlab_deploy_key`, currently there is not way to automate enabling added deploys key to write to the added project.

**Comment by ineedaccount** [comment]
seems like the api doesn't have this option: https://docs.gitlab.com/ee/api/deploy_keys.html#enable-a-deploy-key

it only has it when you create a new deploy key and add it to a project. https://docs.gitlab.com/ee/api/deploy_keys.html#add-deploy-key

**Comment by sebastianortizs4n** [comment]
I created an issue in gitlab about that. Thanks.

https://gitlab.com/gitlab-org/gitlab/-/issues/214483

**Comment by sebastianortizs4n** [comment]
@ineedaccount 

As mentioned https://gitlab.com/gitlab-org/gitlab/-/issues/214483#note_332198427 this operation should be done via de https://docs.gitlab.com/ee/api/deploy_keys.html#update-deploy-key once it is added vía the `Enable Deploy Key` API

**Comment by armsnyder** [comment]
The attribute exists in the schema (via #176), but it is missing in the documentation.

**Comment by timofurrer** [comment]
It's supported and documented by now 🎉
