### ISSUE TITLE
gitlab_project_variable uses a non unique identifier

### ISSUE THREAD

**Issue by phumberdroz** [gitlabhq/terraform-provider-gitlab#298]
### Terraform Version
Terraform v0.12.24
...
+ provider.gitlab v2.6.0
...
### Affected Resource(s)
- gitlab_project_variable

### Expected Behavior
What should have happened?
I have multiple time
```
resource "gitlab_project_variable" "AWS_ACCESS_KEY" {
  project           = data.gitlab_project.project.id
  key               = "AWS_ACCESS_KEY_ID"
  value             = var.AWS_KEY
  masked            = true
  environment_scope = terraform.workspace
}
```
Should only sync that variable but instead a synced a different one with the same key.
```
   # module.sai_gitlab_aws.gitlab_project_variable.AWS_ACCESS_KEY will be updated in-place
   ~ resource "gitlab_project_variable" "AWS_ACCESS_KEY" {
       ~ environment_scope = "production*" -> "development"
         id                = "10:AWS_ACCESS_KEY_ID"
         key               = "AWS_ACCESS_KEY_ID"
       ~ masked            = false -> true
         project           = "10"
         protected         = false
       ~ value             = (sensitive value)
         variable_type     = "env_var"
     }
```
### Actual Behavior
It should use a different identifier to map gitlab_project_variable as key is not unique

**Comment by ineedaccount** [comment]
That's the correct behavior. Your resource name must be unique.
module.sai_gitlab_aws.gitlab_project_variable.AWS_ACCESS_KEY is not unique

You need something like
```
resource "gitlab_project_variable" "AWS_ACCESS_KEY_0" {
  project           = data.gitlab_project.project.id
  key               = "AWS_ACCESS_KEY_ID"
  value             = var.AWS_KEY
  masked            = true
  environment_scope = terraform.workspace
}

resource "gitlab_project_variable" "AWS_ACCESS_KEY_1" {
  project           = data.gitlab_project.project.id
  key               = "AWS_ACCESS_KEY_ID"
  value             = var.AWS_KEY
  masked            = true
  environment_scope = terraform.workspace
}
```
and so on

or you can use terraform 0.12.6 and take advantage of `for_each` https://blog.gruntwork.io/terraform-tips-tricks-loops-if-statements-and-gotchas-f739bbae55f9

**Comment by phumberdroz** [comment]
No I only have the Dev workspace currently managed by Terraform. There is pre existing Vars for other stages configured in Gitlab CI.

**Comment by phumberdroz** [comment]
Looking at the API documentation there is no unique identifier to use in the endpoints.
https://docs.gitlab.com/ee/api/project_level_variables.html

**Comment by phumberdroz** [comment]
Related GitLab Issue: https://gitlab.com/gitlab-org/gitlab/issues/9912

**Comment by techthumb** [comment]
#324 aims to resolve this issue

**Comment by s256** [comment]
going to be fixed in the next release:
https://gitlab.com/gitlab-org/gitlab/-/issues/9912#note_377146498

**Comment by armsnyder** [comment]
I'm closing this issue in favor of #213 where most of the activity is. Rest assured we're looking to get this fixed soon!
