### ISSUE TITLE
[Feature request]: Sharing a group with another group

### ISSUE THREAD

**Issue by iamcharlieza** [gitlabhq/terraform-provider-gitlab#300]
Hi 👋 

### Expected Behavior
Would like to invite another group to have rights in another group. This was previously not available in Gitlab. They have however added support for it. In the latest version of Gitlab you can share a group with another group.

### References
- https://docs.gitlab.com/ce/user/group/#sharing-a-group-with-another-group

Hopefully, I will be able to contribute in future 😄 Thank you in advance for the help!

**Comment by armsnyder** [comment]
I can think of two ways of doing this.

1. Use the existing `gitlab_group_members` resource and add a new value called `shared_group_id`, since the rest of the values are the same, and it's a similar idea.

    ```hcl
    resource "gitlab_group_membership" "user_membership_example" {
      group_id     = "12345"
      user_id      = "67890"
      access_level = "guest"
      expires_at   = "2020-12-31"
    }
    ```

    ```hcl
    resource "gitlab_group_membership" "group_membership_example" {
      group_id        = "12345"
      shared_group_id = "67890"
      access_level    = "guest"
      expires_at      = "2020-12-31"
    }
    ```

2. Create a new `gitlab_group_share` resource that's the same as `gitlab_group_members` but replacing `user_id` with `shared_group_id`.

    ```hcl
    resource "gitlab_group_share" "example" {
      group_id        = "12345"
      shared_group_id = "67890"
      access_level    = "guest"
      expires_at      = "2020-12-31"
    }
    ```

Anyone have thoughts on the design?

**Comment by armsnyder** [comment]
Looking more at the code, we would probably want something similar to how it's done for projects already.

The `gitlab_project` resource has a `shared_with_groups` value.

There's also a dedicated `gitlab_project_share_group` resource.

One or both of these approaches then would be good for consistency reasons:

3.
    ```hcl
    resource "gitlab_group" "example" {
      name        = "example"
      path        = "example"
      description = "An example group"

      shared_with_groups {
        group_id           = 5678
        group_access_level = "guest"
      }
    }
    ```

4.
    ```hcl
    resource "gitlab_group_share_group" "example" {
      group_id        = "12345"
      shared_group_id = "67890"
      access_level    = "guest"
    }
    ```

**Comment by horjulf** [comment]
PR upstream to add read support on the Groups endpoint https://github.com/xanzy/go-gitlab/pull/894
Will PR support here once that has been merged and tagged.
