### ISSUE TITLE
Issue when running gitlab TF code in gitlab pipeline.

### ISSUE THREAD

**Issue by shakerky-awx** [gitlabhq/terraform-provider-gitlab#306]
Hi, I'm trying to TF the gitlab config, and the code works perfectly on my laptop, but whenever it's run inside a pipeline it fails, with 

```
Error: Get "https://gitlab.company.com/api/v4/users?username=user.name1": dial tcp 34.xx.xx.xx:443: connect: connection timed out
   on gitlab_users.tf line 7, in data "gitlab_user" "gitlib_user":
    7: data "gitlab_user" "gitlib_user" {
 Error: Get "https://gitlab.company.com/api/v4/users?username=user.name2": dial tcp 34.xx.xx.xx:443: connect: connection timed out
   on gitlab_users.tf line 7, in data "gitlab_user" "gitlib_user":
    7: data "gitlab_user" "gitlib_user" {
```
Now, I know the connection works in the pipeline, because the line immediately before is this, and it works perfectly:
```curl  -H \"Authorization: Bearer ${GITLAB_TOKEN}\" 'https://gitlab.company.com/api/v4/users?username=user.name1'"```

This is some example code:
```
provider "gitlab" {
  # sourced from the GITLAB_TOKEN environment variable.
  # token = var.gitlab_devops_token
  base_url = var.gitlab_url
}

data "gitlab_users" "gitlab_users_all" {
  sort = "asc"
  order_by = "id"
}

data "gitlab_user" "gitlab_user" {
  for_each = toset(data.gitlab_users.gitlab_users_all.users[*].username)

  username = each.value
}
```

### Terraform Version
% terraform -v
Terraform v0.12.24
+ provider.gitlab v2.5.1

### Affected Resource(s)
Please list the resources as a list, for example:
- gitlab_user, but that's just the first resources it gets to

### Terraform Configuration Files
```
provider "gitlab" {
  # sourced from the GITLAB_TOKEN environment variable.
  # token = var.gitlab_devops_token
  base_url = var.gitlab_url
}

data "gitlab_users" "gitlab_users_all" {
  sort = "asc"
  order_by = "id"
}

data "gitlab_user" "gitlab_user" {
  for_each = toset(data.gitlab_users.gitlab_users_all.users[*].username)

  username = each.value
}
```
### Debug Output
Can't get debugging info, as gitlab cuts it off.

### Expected Behavior
It should have got the data from gitlab

### Actual Behavior
TCP Timeout, but only within the gitlab runner

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan`

### Important Factoids
It's on GCP, in a GKE cluster, if that makes any difference

**Comment by armsnyder** [comment]
Hi @shakerky-awx, are you still having problems? Can you elaborate why you do not think it is a connection failure, and maybe share more logs? To me it looks like a networking problem specific to your own infrastructure setup, and not something we would be able to help with. Perhaps check if you have any sort of firewall or custom routing rules set up in GCP. For what it's worth the provider works for me when I run it from a GitLab runner, running in AWS.

**Comment by armsnyder** [comment]
Closing since it doesn't seem to be a provider bug, and lack of response from author.
