### ISSUE TITLE
Group Datasource Slowness, need ability to set with_projects option to false

### ISSUE THREAD

**Issue by mitchellmaler** [gitlabhq/terraform-provider-gitlab#307]
### Terraform Version
N/A

### Affected Resource(s)
Please list the resources as a list, for example:
- gitlab_group

### Terraform Configuration Files
N/A

Currently when you pull a group datasouce it can take a while to return since it pulls each project along with it since the option with_projects defaults to true on the api call. Would it be possible to have the option to set with_projects to false since sometimes it isn't necessary to pull all groups groups when just needing group details which will speed it up

### References
https://docs.gitlab.com/ee/api/groups.html#details-of-a-group

**Comment by armsnyder** [comment]
It looks like the `with_projects` attribute is [deprecated](https://gitlab.com/gitlab-org/gitlab/-/issues/213797), so it is unlikely that this project or the go-gitlab package it depends on will start supporting it.

**Comment by timofurrer** [comment]
I don't think that we'll implement this for the reason @armsnyder mentioned. I'm going to close it for now. If anyone wants to contribute it with a disclaimer that it is deprecated, feel free and we'll discuss it in a PR. 🎉
