### ISSUE TITLE
Feature Request: Support project creation from templates

### ISSUE THREAD

**Issue by elijah-roberts** [gitlabhq/terraform-provider-gitlab#333]
The gitlab api supports creating new projects from either built-in, or custom templates:

https://docs.gitlab.com/ee/api/projects.html#create-project

![image](https://user-images.githubusercontent.com/19742213/84304386-ac346800-ab15-11ea-88fe-77ecc560783b.png)

I would love to have this functionality, so that I could create new projects from  templates, and manage via terraform in one step.

Currently I have to manually create through the console, or use the API to create the project from a template in gitlab, then I have to import into terraform 

I would be open to working on this, if someone could give me some direction/input on implimentation

**Comment by kassybas** [comment]
We could utilize this feature for our gitlab project creation automation, it's great that it's already worked on.

I'm not sure what's the status of this, is there possible eta? is the any way to contribute to this feature?

**Comment by nicholasklick** [comment]
This was resolved by https://github.com/gitlabhq/terraform-provider-gitlab/pull/334
