### ISSUE TITLE
[feature request] forking_access_level and pages_access_level

### ISSUE THREAD

**Issue by FernandoMiguel** [gitlabhq/terraform-provider-gitlab#351]
### Affected Resource(s)
Please list the resources as a list, for example:
- pages_access_level
- forking_access_level

ideally keeping in sync with https://docs.gitlab.com/ee/api/projects.html#create-project

**Comment by tobiasbueschel** [comment]
Thanks a lot for everyone who has been maintaining this repo!

I agree with @FernandoMiguel, would be great if the GitLab repo creation properties are kept in sync, e.g. I have a use case for disabling GitLab's page feature across all repos that I create with Terraform.
