### ISSUE TITLE
422 {error: Project push rule exists}

### ISSUE THREAD

**Issue by FernandoMiguel** [gitlabhq/terraform-provider-gitlab#352]
### Terraform Version
Terraform v0.12.27
+ provider.gitlab v2.10.0

### Affected Resource(s)
Please list the resources as a list, for example:
- gitlab_project_push_rules

### Terraform Configuration Files
```hcl
resource "gitlab_project_push_rules" "project_push_rules" {
  project                       = gitlab_project.project.id
  commit_message_regex          = var.PROJECT_PUSH_RULES_COMMIT_MESSAGE_REGEX
  branch_name_regex             = var.PROJECT_PUSH_RULES_BRANCH_NAME_REGEX
  author_email_regex            = var.PROJECT_PUSH_RULES_AUTHOR_EMAIL_REGEX
  file_name_regex               = var.PROJECT_PUSH_RULES_FILE_NAME_REGEX
  deny_delete_tag               = var.PROJECT_PUSH_RULES_DENY_DELETE_TAG
  member_check                  = var.PROJECT_PUSH_RULES_MEMBER_CHECK
  prevent_secrets               = var.PROJECT_PUSH_RULES_PREVENT_SECRETS
  max_file_size                 = var.PROJECT_PUSH_RULES_MAX_FILE_SIZE
  # commit_committer_check        = var.PROJECT_PUSH_RULES_COMMIT_COMMITTER_CHECK
  # commit_message_negative_regex = var.PROJECT_PUSH_RULES_COMMIT_MESSAGE_NEGATIVE_REGEX
}

output project_push_rules {
  value = gitlab_project_push_rules.project_push_rules
}

variable "PROJECT_PUSH_RULES_COMMIT_MESSAGE_REGEX" {
  description = "(Optional, string) All commit messages must match this regex"
  type        = string
  default     = null
}

variable "PROJECT_PUSH_RULES_COMMIT_MESSAGE_NEGATIVE_REGEX" {
  type    = string
  default = null
}

variable "PROJECT_PUSH_RULES_BRANCH_NAME_REGEX" {
  description = "(Optional, string) All branch names must match this regex"
  type        = string
  default     = null
}

variable "PROJECT_PUSH_RULES_AUTHOR_EMAIL_REGEX" {
  description = "(Optional, string) All commit author emails must match this regex"
  type        = string
  default     = null
}

variable "PROJECT_PUSH_RULES_FILE_NAME_REGEX" {
  description = "(Optional, string) All commited filenames must not match this regex"
  type        = string
  default     = null
}

variable "PROJECT_PUSH_RULES_DENY_DELETE_TAG" {
  description = "(Optional, bool) Deny deleting a tag"
  type        = bool
  default     = false
}

variable "PROJECT_PUSH_RULES_MEMBER_CHECK" {
  description = "(Optional, bool) Restrict commits by author (email) to existing GitLab users"
  type        = bool
  default     = false
}

variable "PROJECT_PUSH_RULES_PREVENT_SECRETS" {
  description = "(Optional, bool) GitLab will reject any files that are likely to contain secrets"
  type        = bool
  default     = true
}

variable "PROJECT_PUSH_RULES_MAX_FILE_SIZE" {
  description = "(Optional, int) Maximum file size (MB)"
  type        = number
  default     = "0"
}

variable "PROJECT_PUSH_RULES_COMMIT_COMMITTER_CHECK" {
  description = "(Optional, bool) Users can only push commits to this repository that were committed with one of their own verified emails"
  type        = bool
  default     = false
}
```

### Debug Output
```hcl
  # gitlab_project_push_rules.project_push_rules will be created
  + resource "gitlab_project_push_rules" "project_push_rules" {
      + deny_delete_tag = false
      + id              = (known after apply)
      + max_file_size   = 0
      + member_check    = false
      + prevent_secrets = true
      + project         = "REDACTED"
    }

Error: POST https://gitlab.com/api/v4/projects/REDACTED/push_rule: 422 {error: Project push rule exists}

  on main.tf line 62, in resource "gitlab_project_push_rules" "project_push_rules":
  62: resource "gitlab_project_push_rules" "project_push_rules" {

```
### Expected Behavior
for a rule to be created

### Actual Behavior
error: Project push rule exists

### Steps to Reproduce
1. `terraform apply`

not related, but i'm seeing
```hcl
An argument named "commit_committer_check" is not expected here.
```
while that element exists in the documentation

**Comment by ziporah** [comment]
I request to reopen this ticket. When creating the rule for the first time, the required response would be to import the default rule that get's created on project creation. If you create a rule while creating the project. You need to import the rule in the state before you can change it

**Comment by armsnyder** [comment]
@ziporah I agree that we haven't found the best solution yet if creating a project with custom push rules requires two applies.

One approach would be to let the `gitlab_project_push_rules` resource update the existing rules when the resource is create, overwriting any rules that are already there, as in #269.

Another approach would be moving the push rules into the `gitlab_project` resource as attributes.

Definitely looking for suggestions.

**Comment by ziporah** [comment]
I took a quick look at the code, it might be possible to just pull in the resource at the moment you are creating it and then push the information you pulled into the state.
in [resourceGitlabProjectPushRulesCreate](https://github.com/gitlabhq/terraform-provider-gitlab/blob/1c78d7e1141f182dd81da659b12452cbe4ecdab1/gitlab/resource_gitlab_project_push_rules.go#L88) you can first call
```
pushRules, _, err := client.Projects.GetProjectPushRules(project)
``` 
this should get the rules for the current object, it will always be automatically created by gitlab and the id will be the same as the project id, so you have all the info that is in gitlab already. Next you call resourceGitlabProjectPushRulesUpdate on the id, with the options you acquired in the Create, this alters the remote object to reflect the required changes. After this Update succeeds, you can use the d.SetId to push the information you pulled into the state and call  resourceGitlabProjectPushRulesRead to read back the information and allow terraform to fully update the current rule with the correct info.
