### ISSUE TITLE
[Feature Request] "disable_overriding_approvers_per_merge_request"

### ISSUE THREAD

**Issue by TheMacStack** [gitlabhq/terraform-provider-gitlab#357]
Hi there,

It would be very helpful to be able to manage settings exposed via the [Merge Request API](https://docs.gitlab.com/ee/api/merge_request_approvals.html) especially the "Can override approvers and approvals required per merge request" and other settings in that UI context (Project > Settings > General > Merge Request Approvals)

To me it would make sense if these were either added to the gitlab_project resource or a resource of their own

**Comment by armsnyder** [comment]
I see a few open PRs for this already - #160, #244, and #356. Hopefully one of them can be merged soon.

**Comment by armsnyder** [comment]
Fixed via #356 which will be in the next release.
