### ISSUE TITLE
gitlab_project_variable: Add `masked` checks

### ISSUE THREAD

**Issue by michaelwooley** [gitlabhq/terraform-provider-gitlab#371]
Hi, I was recently trying to add a few variables using `gitlab_project_variable` but was running into some issues with the `masked` option.

It turns out that the cause of my issue is just that my assigned variables didn't meet the masked variables requirements, which are described [here](https://gitlab.com/help/ci/variables/README#mask-a-custom-variable).

It would be great if these checks could be done either on validate or even just return a more informative error message at apply time.

For my case I was assigning a variable to the value so I doubt it would be possible to do the checks before apply.

### Terraform Version

Terraform v0.12.29
+ provider.digitalocean v1.22.0
+ provider.gitlab v2.11.0
+ provider.helm v1.2.4
+ provider.kubernetes v1.12.0

### Affected Resource(s)

- gitlab_project_variable

### Terraform Configuration Files

```hcl
provider "gitlab" {
  token = var.gitlab_token
}

data "gitlab_project" "my-project" {
  id = 123
}

resource "gitlab_project_variable" "container-auth" {
  project   = data.gitlab_project.ci-node-example.id
  key       = "CONTAINER_REGISTRY"
  value     = {"auths":{"registry.digitalocean.com":{"auth":"XXXXX"}}} # <--- Cannot handle "{"
  protected = true
  environment_scope = "*"
  masked = true # <--- error
}

# Same as above but the value is derived from a 
resource "gitlab_project_variable" "container-auth-2" {
  project   = data.gitlab_project.ci-node-example.id
  key       = "CONTAINER_REGISTRY_FROM_VAR"
  value     = var.container_registry_credentials # <-- imported from another module
  protected = true
  environment_scope = "*"
  masked = true # <--- error
}
```

### Debug Output

No crash per se. Here is the attempt to create a plan:

https://gist.github.com/michaelwooley/a3ff9c1d7085f6855839c1dda7a9e4cf

### Panic Output

N/A

### Expected Behavior

Either:

- A failed apply with a message along the lines of "invalid mask variable received, see the requirements here https://gitlab.com/help/ci/variables/README#masked-variable-requirements"
- ()

### Actual Behavior

Opaque error seen above. This caused me to wonder about a bug here first. Probably not the best thought process but the fact that it worked with masked = false suggested it. The relevant docs on this are buried pretty deep unless you try to go in through the UI.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

N/A

### References

N/A

**Comment by armsnyder** [comment]
The validation rules for masked fields are complicated and change semi-regularly. I think instead of adding validation logic to this provider we can provide a friendlier error message.

**Comment by armsnyder** [comment]
Reopening this since we should make the same improvement to `gitlab_group_variable`.
