### ISSUE TITLE
Global deploy key

### ISSUE THREAD

**Issue by DavidGamba** [gitlabhq/terraform-provider-gitlab#373]
### Terraform Version

Terraform v0.12.26
+ provider.aws v2.69.0
+ provider.gitlab v2.10.0

### Affected Resource(s)

- gitlab_deploy_key

### Expected Behavior

Project should be optional so I can have global deploy keys the same way I create them using the Admin UI.

![image](https://user-images.githubusercontent.com/1115287/89470874-07f82780-d73a-11ea-9aa4-69dcc4453033.png)

**Comment by armsnyder** [comment]
The [API for public deploy keys](https://docs.gitlab.com/ee/api/deploy_keys.html#list-all-deploy-keys) is read-only, it seems, so in the current state we couldn't make a resource of it.

**Comment by DavidGamba** [comment]
Can you make a `data` resource out of it? even with just that, we can track its use in code as long as that is able to be used in a project.
