### ISSUE TITLE
Not working with terraform 0.13

### ISSUE THREAD

**Issue by thuck** [gitlabhq/terraform-provider-gitlab#383]
Hi;

I just bumped my version of terraform from 0.12 to 0.13 and gitlab is not working anymore.
Looks like it tries to collect the provider from there:
registry.terraform.io/terraform-providers/gitlab

What leads to a 404 page.
Any information when do we get the provider in the official "repo"?

**Comment by nicholasklick** [comment]
@thuck we are working with Hashicorp to get it included in the Registry. Stay tuned.

**Comment by thuck** [comment]
@nicholasklick any idea if we are going to have this available soon?

**Comment by NeckBeardPrince** [comment]
Bump. The docs also link to an archived Github.

**Comment by brenwhyte** [comment]
Yeap, in the same boat here. An update would be appreciated.

**Comment by thuck** [comment]
Looks like this will be fixed with the new version: https://github.com/gitlabhq/terraform-provider-gitlab/issues/411

**Comment by NeckBeardPrince** [comment]
Bonus points if you get it into the TF Registry.

**Comment by nicholasklick** [comment]
We have updated the build process and enabled publishing to the Terraform provider registry.
Currently a prerelease was published: https://registry.terraform.io/providers/gitlabhq/gitlab/latest

Hopefully, you can expect a 3.0.0 release in the coming days.

**Comment by nicholasklick** [comment]
3.0.0 has shipped! https://github.com/gitlabhq/terraform-provider-gitlab/releases/tag/v3.0.0

It should be available on > 0.13 https://registry.terraform.io/providers/gitlabhq/gitlab/latest

**Comment by liuyangc3** [comment]
@nicholasklick there is `hashicorp/gitlab` in Terraform v0.13.3 somewhere.
```hcl
data "gitlab_project" "this" {
}
```
if run `terraform init` got this error
```
Error: Failed to install providers
Could not find required providers, but found possible alternatives:
  hashicorp/gitlab -> gitlabhq/gitlab
```

**Comment by armsnyder** [comment]
@liuyangc3 I believe that is the expected behavior. Any provider that is not maintained by HashiCorp needs to be explicitly declared in your `terraform` block. See the upgrade guide section [Explicit Provider Source Locations](https://www.terraform.io/upgrade-guides/0-13.html#explicit-provider-source-locations).
