### ISSUE TITLE
CI/CD Pipeline cannot use gitlab_project_variable value

### ISSUE THREAD

**Issue by cevich** [gitlabhq/terraform-provider-gitlab#384]
### Terraform Version

0.12.28

### Affected Resource(s)

gitlab_project_variable

### Terraform Configuration Files

```hcl
resource gitlab_project_variable "cicdvar" {
    for_each = var.vars
    project = var.project_id
    key = each.key
    value = each.value[1]
    protected = contains([1,3], each.value[0]) ? true : false
    masked = contains([2,3], each.value[0]) ? true : false
}
```

### Debug Output

N/A

### Panic Output

N/A

### Expected Behavior

When no environment is specified in the resource block, the variable in gitlab should be defined with an environment of `All (default)`..

### Actual Behavior

In gitlab, the variable is defined with a (non-existing) environment of `0` (zero).  Since that environment doesn't exist (in my case, no environments are defined), the variable isn't defined in any pipelines run for the project.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

This problem can be very difficult for an end-user to debug, from the pipeline output perspective.  I only noticed it by accident, when editing the variable in the WebUI, and clicking the drop-down for 'environment'.

### References

Possibly related to #213

**Comment by cevich** [comment]
I'm not a golang expert (barely even a novice), but I wonder if this isn't the cause of the problem: https://github.com/terraform-providers/terraform-provider-gitlab/blob/master/gitlab/resource_gitlab_project_variable.go#L71

Since it appears to me, the [default value is `false` which in most languages string-translates to "0" (zero).](
https://github.com/terraform-providers/terraform-provider-gitlab/blob/master/gitlab/resource_gitlab_project_variable.go#L56)

The Gitlab API docs aren't very specific, but they do [specify this attribute as optional](https://docs.gitlab.com/ee/api/project_level_variables.html#create-variable).  I'm assuming that means the provider behavior should be:

1. If the value of the variable is `false`, do not send an `environment` variable at all
2. Else, string-translate the environment value and send it.

**Comment by armsnyder** [comment]
Closing in favor of #195
