### ISSUE TITLE
Bogus issue to diagnose github support case

### ISSUE THREAD

**Issue by justinkillen** [gitlabhq/terraform-provider-gitlab#395]
I reported a bug to github where when this repo was moved from terraform-providesr to gitlabhq the notifications weren't updated.  This request is just to help diagnose that report.

**Comment by thetalorian** [comment]
@justinkillen  Testing notifications

**Comment by armsnyder** [comment]
@justinkillen do you still need this open?

**Comment by nicholasklick** [comment]
@justinkillen I am going to close this for now. Please reopen if for some reason it is needed.

**Comment by justinkillen** [comment]
Sorry all - I missed the notification.  Yes, closing is the right thing to do.  Thanks, and sorry about any confusion :)
