### ISSUE TITLE
Meta - PRs for new resources frequently do not update website/gitlab.erb index file 

### ISSUE THREAD

**Issue by armsnyder** [gitlabhq/terraform-provider-gitlab#398]
I've noticed in doing reviews that for the majority of PRs that add new resource types, the docs are not updated correctly. In particular, contributors often do not realize they must update the `website/gitlab.erb` file.

Is there a way we can make this better, either by generating the index automatically or by adding a GitHub Action to automate checking that `website/gitlab.erb` was updated?

**Comment by nicholasklick** [comment]
Automation sounds like a great idea long term. A [boring solution](https://about.gitlab.com/handbook/values/#boring-solutions) could be to create a PR template and require doc updates to be included?

**Comment by armsnyder** [comment]
It looks like maybe with the new docs format for Terraform Registry you no longer need to maintain your own index, so this could be a non-issue once we integrate with Terraform Registry and move to the new docs format. https://www.terraform.io/docs/registry/providers/docs.html

**Comment by armsnyder** [comment]
Fixed via #413
