### ISSUE TITLE
Publish 3.0.0 release

### ISSUE THREAD

**Issue by nicholasklick** [gitlabhq/terraform-provider-gitlab#411]
@roidelapluie @armsnyder 

Are we ready to publish a new major release?

What has been the process previously?

1. Create a new release
1. Notify Hashicorp via slack?

Thanks.

**Comment by roidelapluie** [comment]
Previously hashicorp did all the work. I don't know what the new procedure is.

**Comment by roidelapluie** [comment]
@armsnyder do you know if CHANGELOG is up to date?

**Comment by armsnyder** [comment]
@nicholasklick I also don't know how to do a release. Maybe when you finish the Terraform Registry setup you'll get some instructions from Hashicorp?

@roidelapluie I just pushed an update for the last couple merges.

**Comment by attachmentgenie** [comment]
publishing a release to the registry requires finishing the terraform registry setup (that person needs admin permissions on this repository), Setting a gpg key (and sharing the public part with hashicorp) as a github secret, and running the workflow from #412.

**Comment by armsnyder** [comment]
@attachmentgenie Yup, sounds right.

@nicholasklick Assuming you're admin, you'll probably find some info in the publish page here, after logging in: https://registry.terraform.io/publish/provider. When I visit that page it doesn't let me select the gitlabhq org, so I'm not sure what lies beyond.

**Comment by liuyangc3** [comment]
👍 Glad to see the new release in terraform registry, we are waiting for it so long

**Comment by nicholasklick** [comment]
Looks like the `release` action worked!
https://github.com/gitlabhq/terraform-provider-gitlab/releases/tag/v3.0.0-pre

**Comment by armsnyder** [comment]
@nicholasklick Awesome! Did you write the release notes yourself or were they generated by the releaser tool? Also, just making sure you saw our conversation [here](https://github.com/gitlabhq/terraform-provider-gitlab/pull/416#issuecomment-694003637) about possibly removing the `gitlab_push_rule` and/or `gitlab_project_share_group` resources. Can we come to a consensus about that and do it before releasing 3.0.0?

**Comment by nicholasklick** [comment]
@armsnyder the release notes were generated.

**Comment by nicholasklick** [comment]
<img width="1144" alt="Screen Shot 2020-09-18 at 1 06 37 AM" src="https://user-images.githubusercontent.com/24757/93558366-4bee6700-f94b-11ea-9029-37984d509f34.png">
 Looks like publishing to the registry is working also!

**Comment by nicholasklick** [comment]
@armsnyder @roidelapluie for the 3.0.0 release we may needed to generate the release notes ourselves based on a diff. Since I created a number of test releases, I am not sure a new 3.0.0 would contain the full changelog.

**Comment by armsnyder** [comment]
My fingers are crossed that goreleaser will pick up on the "3.0.0" header in the CHANGELOG.md. That would be magical.

**Comment by armsnyder** [comment]
@nicholasklick @roidelapluie My PR for the `gitlab_push_rules` change is here #422 😄 

I think that's the last urgent/breaking fix for 3.0.0?

**Comment by nicholasklick** [comment]
@armsnyder ok great! You want to merge it and attempt to create the `3.0.0`?

We will see if the registry picks it up as expected?

**Comment by roidelapluie** [comment]
The PR is not totally fine. I will comment later today.

**Comment by armsnyder** [comment]
Yeah I'll definitely wait for feedback before merging.

**Comment by Nainterceptor** [comment]
Hello,

If you want my feedback, everything seems to be working here, but we're using a very small part of the provider (to define variables mainly)

**Comment by nicholasklick** [comment]
Shipped! https://github.com/gitlabhq/terraform-provider-gitlab/releases/tag/v3.0.0

**Comment by FernandoMiguel** [comment]
are the provider docs updated too?

**Comment by FernandoMiguel** [comment]
i see it is 
https://registry.terraform.io/providers/gitlabhq/gitlab/latest/docs/data-sources/group_membership
