### ISSUE TITLE
[feature request] support importing projects in the `gitlab_project` resource

### ISSUE THREAD

**Issue by ketzacoatl** [gitlabhq/terraform-provider-gitlab#42]
Hi,

I am looking at using the `gitlab` provider to manage a variety of projects, and wondering how reasonable it is to use this resource when the project needs to be imported. EG, in gitlab, when you create a new project, you can select to import that project from an HTTP or git/etc URL. When creating the project with the Terraform resource, I would like to be able to specify the URL the project should be initially imported from. This import is a one-time action, so IDK if it makes sense for the provider to support this, but it seems worth asking about.

Thanks!

**Comment by danielriesner** [comment]
#142 resolves this.

**Comment by baurmatt** [comment]
@roidelapluie Could you please close this issue? :)
