### ISSUE TITLE
Enterprise license for maintainers?

### ISSUE THREAD

**Issue by armsnyder** [gitlabhq/terraform-provider-gitlab#424]
Hi @nicholasklick @roidelapluie 

I was wondering if it's possible to run the EE-only tests locally? So far I've been pushing every time I want to run them, which makes working on EE features slower than it probably could be.

I was looking at #415 which needs to be validated in a UI.

**Comment by roidelapluie** [comment]
Sure. Do you have a secure way to get the license? E.g. keybase?

**Comment by armsnyder** [comment]
@roidelapluie Sure, I'm here: https://keybase.io/armsnyder

**Comment by roidelapluie** [comment]
Ok, I'll send you that tomorrow or Monday

**Comment by armsnyder** [comment]
Thanks, no rush. 😄

**Comment by armsnyder** [comment]
license get

**Comment by nicholasklick** [comment]
I just sent over the license.
