### ISSUE TITLE
Fix AT001: missing CheckDestroy

### ISSUE THREAD

**Issue by armsnyder** [gitlabhq/terraform-provider-gitlab#433]
Check: [AT001](https://github.com/bflad/tfproviderlint/tree/master/passes/AT001)

```
./gitlab/resource_gitlab_project_share_group_test.go:17:28: AT001: missing CheckDestroy
./gitlab/resource_gitlab_project_test.go:511:28: AT001: missing CheckDestroy
```

We should fix these reported issues, and then remove this check from the list of ignored checks in the gitlabproviderlint make target.

To reproduce, run `go run ./gitlabproviderlint ./gitlab` (pending #432)

**Comment by Shocktrooper** [comment]
This also appears in

- resource_gitlab_instance_variable_test.go
- resource_gitlab_project_share_group_test.go

I have picked up this work
