### ISSUE TITLE
Fix AT003: acceptance test function name should include underscore

### ISSUE THREAD

**Issue by armsnyder** [gitlabhq/terraform-provider-gitlab#435]
Check: [AT003](https://github.com/bflad/tfproviderlint/tree/master/passes/AT003)

```
./gitlab/data_source_gitlab_projects_test.go:14:6: AT003: acceptance test function name should include underscore
./gitlab/data_source_gitlab_projects_test.go:53:6: AT003: acceptance test function name should include underscore
```

We should fix these reported issues, and then remove this check from the list of ignored checks in the gitlabproviderlint make target.

To reproduce, run `go run ./gitlabproviderlint ./gitlab` (pending #432)

**Comment by PatrickRice-KSC** [comment]
Hey @armsnyder  - It looks like this may have been resolved, just looking at the project_test file. You good if I close this out? I see one test in that file, and it matches our naming convention.

**Comment by armsnyder** [comment]
There are still a couple in this file: https://github.com/gitlabhq/terraform-provider-gitlab/blob/d19ee24973d2505f9df91a1e480c3bbff9b11751/internal/provider/data_source_gitlab_projects_test.go
