### ISSUE TITLE
Fix S006: schema of TypeMap should include Elem

### ISSUE THREAD

**Issue by armsnyder** [gitlabhq/terraform-provider-gitlab#437]
Check: [S006](https://github.com/bflad/tfproviderlint/tree/master/passes/S006)

```
./gitlab/data_source_gitlab_projects.go:648:22: S006: schema of TypeMap should include Elem
```

We should fix these reported issues, and then remove this check from the list of ignored checks in the gitlabproviderlint make target.

To reproduce, run `go run ./gitlabproviderlint ./gitlab` (pending #432)

**Comment by PatrickRice-KSC** [comment]
@armsnyder  - I think this issue is resolved as well, I'm not getting this linting error on the noted file anymore. You good if I close it?

**Comment by armsnyder** [comment]
There is still one here: https://github.com/gitlabhq/terraform-provider-gitlab/blob/d19ee24973d2505f9df91a1e480c3bbff9b11751/internal/provider/data_source_gitlab_projects.go#L215

**Comment by PatrickRice-KSC** [comment]
aaah, I was running lint, which didn't return it given the lintignore. I'll run a grap and see if I can knock these out so we can close this issue.
