### ISSUE TITLE
Environments support

### ISSUE THREAD

**Issue by 23doors** [gitlabhq/terraform-provider-gitlab#444]
From what I gathered currently there is no way for provider to create Project Environments nor there is a way to manage Protected Environments. Seems that at least normal Environments are supported by github.com/xanzy/go-gitlab

Any plans to add a resource for it?

**Comment by armsnyder** [comment]
Link to the API reference for this potential new resource: https://docs.gitlab.com/ee/api/environments.html

**Comment by sirlatrom** [comment]
I've submitted https://github.com/xanzy/go-gitlab/pull/1066. Once it's merged, I'll add support in this provider.

**Comment by dhrapson** [comment]
Looks like PR #567 got superceded by #750, with issues fixed. Is that acceptable now @armsnyder?

**Comment by tahir-gvs** [comment]
Any chance of this getting released soon?

**Comment by PatrickRice-KSC** [comment]
Keeping notes up to date 😄 

PR #750  superceded by PR #938
