### ISSUE TITLE
Error with push rules for projects and non-premium GitLab version

### ISSUE THREAD

**Issue by grv87** [gitlabhq/terraform-provider-gitlab#447]
### Terraform Version
0.13.3

### Provider Version
3.0.0

### GitLab Version
12.9.0-ee (Starter)

### Affected Resource(s)
- `gitlab_project`

### Terraform Configuration Files
```hcl
resource "gitlab_project" "projects" {
...
  push_rules {
    deny_delete_tag = true
    member_check = false
    prevent_secrets = true
    commit_message_regex = "^(feat|fix|docs|style|refactor|test|chore|perf): .+"
    branch_name_regex = "^(master|(feature|hotfix)\\/.+)$"
    file_name_regex = "\\.(jar|exe)$"
    author_email_regex = null
    max_file_size = 10 # MiB
  }
}
```

### Debug Output
https://gist.github.com/grv87/7dae3d6fce31f5563365a456f6276679

### Expected Behavior
Push rules configured successfully.

### Actual Behavior
Error 403 Forbidden.
Provider tries to put the following JSON to GitLab:
```json
{
 "author_email_regex": "",
 "branch_name_regex": "^(master|(feature|hotfix)\\/.+)$",
 "commit_message_regex": "^(feat|fix|docs|style|refactor|test|chore|perf): .+",
 "commit_message_negative_regex": "",
 "file_name_regex": "\\.(jar|exe)$", 
 "member_check": false,
 "prevent_secrets": true,
 "max_file_size": 10,
 "deny_delete_tag": true,
 "commit_committer_check": false,
 "reject_unsigned_commits": false
}
```

According to [GitLab docs](https://docs.gitlab.com/ee/push_rules/push_rules.html), `commit_committer_check` and `reject_unsigned_commits` options are supported for `Premium` version only.
Somehow provider decides to send them.
JSON without these options works fine.

**Comment by grv87** [comment]
Connected to #422 #202

**Comment by grv87** [comment]
One option could be to check license (https://docs.gitlab.com/ee/api/license.html). But
> you need to authenticate yourself as an admin

It's not an option for me.

I believe that plan information should be disclosed to everyone (e.g. in https://docs.gitlab.com/ee/api/version.html), but this requires the change in GitLab itself.

Other option could be to ignore unsupported features instead of returning `403`, on the GitLab side too.

Third option is to add an option `plan` to provider and turn off unsupported features here.

**Comment by armsnyder** [comment]
@grv87 Thanks for the report. We implemented push rules as all-or-nothing, not realizing there were different version gates for individual rules. 😦 If possible can you share the exact error message you see in Terraform?

**Comment by grv87** [comment]
@armsnyder,
```
Error: Failed to edit push rules for project "157": PUT http://XXX/api/v4/projects/157/push_rule: 403 {message: 403 Forbidden}

  on gitlab.tf line 89, in resource "gitlab_project" "projects":
  89: resource "gitlab_project" "projects" {
```
I believe it is presented in the log gist.

**Comment by grv87** [comment]
For now. the only solution I see is to have two different providers, one for GitLab Premium and the second one for Starter.

**Comment by Stan0304** [comment]
@grv87, would it be possible to not adding `commit_committer_check` and `reject_unsigned_commits` at all when those fields are empty ? That's the way to go when using the API at least.

**Comment by armsnyder** [comment]
@Stan0304 Yep, that should be the correct approach to take but will require updating the plugin code. I'll start working on a PR later today.
