### ISSUE TITLE
Resource gitlab_group_ldap_link has incorrect import documentation

### ISSUE THREAD

**Issue by grv87** [gitlabhq/terraform-provider-gitlab#448]
### Terraform Version
0.13.3

### Provider Version
3.0.0

### Affected Resource(s)
- `gitlab_group_ldap_link`

### Terraform Configuration Files
```hcl
resource "gitlab_group_ldap_link" "ldap_group" {
  group_id = 123
  cn = "XXX"
  access_level = "owner"
  ldap_provider = "ldapmain"
}
```

`terraform import gitlab_group_ldap_link.ldap_group "ldapmain:XXX`

### Debug Output
https://gist.github.com/grv87/cd8d712124c0939807b8046b6c4653db

### Expected Behavior
According to [documentation](https://registry.terraform.io/providers/gitlabhq/gitlab/latest/docs/resources/group_ldap_link#import), import succeeded

### Actual Behavior
```
Error: resource gitlab_group_ldap_link doesn't support import
```

**Comment by grv87** [comment]
@armsnyder, why it is marked as enhancement when documentation explicitly promises that import is supported? I believe this is a bug in either code or documentation.

**Comment by armsnyder** [comment]
@grv87 I had misinterpreted the issue as wanting to add the ability to import.
