### ISSUE TITLE
Expose allow_merge_on_skipped_pipeline in gitlab_project

### ISSUE THREAD

**Issue by dfredell** [gitlabhq/terraform-provider-gitlab#464]
### Terraform Version
```bash
Terraform v0.12.29
+ provider.external v2.0.0
+ provider.gitlab v3.0.0
+ provider.google v3.43.0
+ provider.null v3.0.0
+ provider.random v3.0.0
+ provider.restapi v1.13.0-darwin-amd64
```

### Affected Resource(s)
- gitlab_project

### Terraform Configuration Files
```hcl
resource "gitlab_project" "example" {
  name        = "example"
  description = "My awesome codebase"

  visibility_level = "public"
  allow_merge_on_skipped_pipeline = true
}
```

### Expected Behavior
Set this "Skipped pipelines are considered successful" checkbox on the Project Settings - General - Merge Request 
![image](https://user-images.githubusercontent.com/8085744/95867983-5ecc3f80-0d2f-11eb-8ed4-27a9ccd9665c.png)

### Actual Behavior
This new feature isn't supported in terraform, but is in the GitLab API. 

```bash
$ terraform validate
Error: Unsupported argument

  on main.tf line 5, in resource "gitlab_project" "example":
  5:   allow_merge_on_skipped_pipeline = true
```

### References
GitLab Project API https://docs.gitlab.com/ee/api/projects.html with `allow_merge_on_skipped_pipeline`
GitLab merge request adding this feature https://gitlab.com/gitlab-org/gitlab/-/merge_requests/27490

**Comment by flmmartins** [comment]
Hey everyone, any ETA for this? Thanks!

**Comment by mkjmdski** [comment]
yeah, that would be an useful feature :)

**Comment by mkjmdski** [comment]
Implementation is ready, but waits for nearly a month for a reviewer https://github.com/gitlabhq/terraform-provider-gitlab/pull/705
