### ISSUE TITLE
Create gitlab_deploy_token without expiration for project

### ISSUE THREAD

**Issue by Nainterceptor** [gitlabhq/terraform-provider-gitlab#468]
Dear team,

In a project, we're using gitlab_deploy_token resource to create a deploy token to pull container in kubernetes instance.
It's expected to have an expiration in enough far away in future to ensure that kubernetes will always be able to pull docker image.
According to provider documentation of [gitlab_deploy_token](https://registry.terraform.io/providers/gitlabhq/gitlab/latest/docs/resources/deploy_token), we can set `expires_at` as the example.
-> First improvement : the `expires_at` is not in "Argument Reference" part.

I've tried to set a null value, but it set a date in the past, to it expires immediatly.
-> Second improvement : put the value as required or set a default value in future ? (First is better I think)

Currently, I've hardcoded a value in year 2100, but gitlab support an expiration value : "Never". It should be the right value in my case, at least a more meaningful value.
-> Third improvement : be able to set explicitly a "Never" value, like `false` or `"never"` ?

Thanks,
Gaël

**Comment by valorl** [comment]
I can confirm this. It is certainly unexpected behavior. The docs for `expires_at` claim:
> (Optional, string) Time the token will expire it, RFC3339 format. *Will not expire per default*.

The token should be created with `expires_at: null` in the API in order for it to have expiry _Never_. 
However, this provider, for some reason, maps a Teraform `null` value (or lack of the attribute altogether) to `0001-01-01T00:00:00Z` before sending it to the API (perhaps a serialization oversight?). 
Gitlab does not seem to have any convention where `0001-01-01T00:00:00Z` would be regarded as infinity, and thus the created token will instantly expire for being `< now`.

**Comment by willianpaixao** [comment]
I believe this bug was fixed at some point. I can currently create deploy tokens that never expire by just not setting `expires_at`.

@Nainterceptor @valorl could you update your provider to v3.6.0 and re-run?

**Comment by Nainterceptor** [comment]
I confirm that 3.6.0 solve this issue, thanks
