### ISSUE TITLE
Feature request - allow for configuring Pages visibility

### ISSUE THREAD

**Issue by tangodev** [gitlabhq/terraform-provider-gitlab#471]
Hello,

I'm working on a static site with Gitlab and I'm using Terraform to keep everything nice and tidy. I see however, that in the current version of the provider there is no way to set Pages visibility.

```
Terraform v0.13.5
+ provider registry.terraform.io/gitlabhq/gitlab v3.1.0
```

### Affected Resource(s)
- gitlab_pages (?)
- gitlab_project (?)

### Expected Behavior
User should be able to make Pages visible to Everyone via HCL configuration.

### Actual Behavior
The User needs to log into the web console and configure visibility manually:

![image](https://user-images.githubusercontent.com/12778629/97576578-a10fa500-19ee-11eb-9fb5-70e0151f521b.png)

### References

- https://docs.gitlab.com/ee/user/project/pages/introduction.html#gitlab-pages-access-control

**Comment by jeremad** [comment]
That should be easy to implement: https://github.com/xanzy/go-gitlab/blob/master/projects.go#L102
I'll have a look

**Comment by tangodev** [comment]
Awesome :)

**Comment by armsnyder** [comment]
Added via #472 and will be in the next release.
