### ISSUE TITLE
Provider can not work in a module

### ISSUE THREAD

**Issue by liuyangc3** [gitlabhq/terraform-provider-gitlab#475]
I have a module which creates some gitlab resource, the module can not work with providers statement

### Terraform Version
Terraform v0.13.3
+ provider registry.terraform.io/gitlabhq/gitlab v3.1.0

### Affected Resource(s)
module

### Terraform Configuration Files
the main.tf
```hcl
terraform {
  required_version = ">= 0.13"
  required_providers {
    gitlab = {
      source = "gitlabhq/gitlab"
    }
  }
}

# config provider
provider "gitlab" {
  alias    = "test"
  token    = "mytoken"
  base_url = "https://gitlab.domain"
}

# passing provider into a module
module "test" {
  providers = {
    gitlab     = gitlab.test
  }
  source = "./test-module"
  ...
}
```

The module code can be any gitlab resource 

### Expected Behavior
I can run this module

### Actual Behavior
if I run `terraform apply`, I will get error
```
Initializing modules...
- test in ./test-module

Initializing the backend...

Initializing provider plugins...
- Using previously-installed gitlabhq/gitlab v3.1.0
- terraform.io/builtin/terraform is built in to Terraform
- Finding latest version of hashicorp/gitlab...

Error: Failed to install providers

Could not find required providers, but found possible alternatives:

  hashicorp/gitlab -> gitlabhq/gitlab

If these suggestions look correct, upgrade your configuration with the
following command:
    terraform 0.13upgrade ./test-module
```
I have to create a version.tf in my module path to make this work, the content is already defined in main.tf.
```hcl
# the version.tf in my module
terraform {
  required_providers {
    gitlab = {
      source = "gitlabhq/gitlab"
    }
  }
  required_version = ">= 0.13"
}
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

I tested some other providers with my module they can work with `providers` statement, only gitlab provider has this issue

**Comment by matikij** [comment]
According to terraform docs: https://www.terraform.io/docs/configuration/provider-requirements.html#requiring-providers

> Each Terraform module must declare which providers it requires, so that Terraform can install and use them. Provider requirements are declared in a required_providers block.

So AFAIU gitlab provider is consistent with the documentation, not sure why other providers work without it though.

**Comment by armsnyder** [comment]
I share @matikij's take on this. It makes sense that the module would need to declare the provider source when using Terraform 1.13. Perhaps it works with "other providers" if those other providers are already under the `hashicorp` namespace, which seems to be the default. For example the `aws` provider is under `hashicorp`.

**Comment by liuyangc3** [comment]
> s. It makes sense that the module would need to declare the provider source
I don't agree with this

According to https://www.terraform.io/docs/configuration/providers.html#selecting-alternate-provider-configurations
> To select alternate provider configurations for a child module, use its providers meta-argument to specify which provider configurations should be mapped to which local provider names inside the module:

the keyword `providers` in the module exactly tells the module use which provider configuration.

**Comment by armsnyder** [comment]
Closing this. Let me know if it needs to be re-opened.
