### ISSUE TITLE
Escape username if it contains a period

### ISSUE THREAD

**Issue by spuder** [gitlabhq/terraform-provider-gitlab#476]
Terraform http backend does not work with gitlab when the username contains a period. 

terraform version
0.13.5

Reported cases

- https://gitlab.com/gitlab-org/gitlab/-/issues/219294#note_441290781
- https://gitlab.com/gitlab-org/gitlab/-/issues/238090

In both cases, the work around is to change the username `.` to an ascii equivalent. 

## Steps to reproduce

1. Follow the gitlab documentation for setting up terraform with gitlab using http backend

https://docs.gitlab.com/ee/user/infrastructure/

```
terraform {
    backend "http" {
    }
}
```

2. Run init command, This should work if your username is simple, but it will give error if username contains period. 

```
Error: Error loading state:
    HTTP remote state endpoint requires auth
```
```
terraform init \
    -backend-config="address=https://gitlab.example.com/api/v4/projects/1234/terraform/state/foobar" \
    -backend-config="lock_address=https://gitlab.example.com/api/v4/projects/1234/terraform/state/foobar/lock" \
    -backend-config="unlock_address=https://gitlab.example.com/api/v4/projects/1234/terraform/state/foobar/lock" \
    -backend-config="password=<REDACTED>" \
    -backend-config="lock_method=POST" \
    -backend-config="unlock_method=DELETE" \
    -backend-config="retry_wait_min=5" \
    -backend-config='username=spencer.owen'
```

## Workaround

Change `-backend-config='username=spencer.owen'` to `-backend-config='username=spencer%2Eowen'`

**Comment by timofurrer** [comment]
This isn't an issue of this provider, but it may be with GitLab itself. Please open an issue upstream at https://gitlab.com/gitlab-org/gitlab/-/issues

Going to close here 🎉
