### ISSUE TITLE
Support all attributes supported by API in gitlab_project resource

### ISSUE THREAD

**Issue by Zyava** [gitlabhq/terraform-provider-gitlab#477]
I'm very surprised that `gitlab_project` resource doesn't support all attributes available in the API:
https://docs.gitlab.com/ee/api/projects.html#create-project. Please support all attributes API supports - like it is done in other providers (AWS, k8s, etc.)

### Terraform Version
TF 0.13.5, Gitlab provider version 3.1.0

### Affected Resource(s)
- gitlab_project

### Expected Behavior
All attributes accepted by Gitlab API (https://docs.gitlab.com/ee/api/projects.html#create-project) are supported by `gitlab_project` resource.

### Actual Behavior
Some random subset of attributes is supported.

**Comment by kitos9112** [comment]
This would be great - Do you have plans to get a close 100% coverage of the existing GitLab v4 API to create projects?

@armsnyder

**Comment by cmd-werner** [comment]
This would be a great addition

**Comment by timofurrer** [comment]
I've attempted this (at least for now) in #917 

However, this is a never-ending story, thus I'll close this issue once #917 is merged and we can open dedicated issues for missing attributes afterwards.
