### ISSUE TITLE
Support badges

### ISSUE THREAD

**Issue by declension** [gitlabhq/terraform-provider-gitlab#487]
First - thanks for a great project - it's changed how we manage lots of things :+1: 

Badges are a great visual way of indicating status at a glance on larger projects. 

The [Gitlab API has supported badges](https://docs.gitlab.com/ee/api/project_badges.html) for a while, so I'd love for this to be configurable in terraform.

**Comment by LipingSun** [comment]
Any plan to support this feature?

**Comment by LipingSun** [comment]
@armsnyder Any update? It would be useful to have this feature supported.

**Comment by victorboissiere** [comment]
We would also love to have this feature 👍 I'll take a look if I can find some time to directly make the PR.
Which way could work best?
- Add a new variable in the project resource
- Manage it as a new standalone resource

**Comment by mekras** [comment]
I can't imagine what it would look like with a variable. Probably the resource will be better. The main thing is that we can not only add and change them, but also delete them.

Here is an example of badges in one of our projects:

![изображение](https://user-images.githubusercontent.com/192067/121399764-6d6f0300-c95f-11eb-9480-cb24095a31f6.png)

**Comment by fandujar** [comment]
@armsnyder I think we can close this issue even tho we don't have group badges support yet

**Comment by fandujar** [comment]
@declension @LipingSun @victorboissiere @mekras you can find project badge support on version 3.7.0 released hours ago.

**Comment by armsnyder** [comment]
> I think we can close this issue even tho we don't have group badges support yet

Agreed. We'd of course like to have full API coverage in the provider, but until then if anyone needs group badges specifically please open a new issue to help prioritize. 😄
