### ISSUE TITLE
release provider 3.2.0

### ISSUE THREAD

**Issue by Stromweld** [gitlabhq/terraform-provider-gitlab#488]
Now that #250 and a few other changes have been merged to master can we get a new feature released to terraform registry? I've been looking forward for a while now to use approval rules to help us better control releases and automate it with tf.

**Comment by ymatsiuk** [comment]
Together with #318 please 😉

**Comment by nicholasklick** [comment]
3.2.0 is being cut https://github.com/gitlabhq/terraform-provider-gitlab/releases/tag/v3.2.0
