### ISSUE TITLE
Add optional protected_branch_ids to the project_level_mr_approvals resource

### ISSUE THREAD

**Issue by Shocktrooper** [gitlabhq/terraform-provider-gitlab#492]
### Enhancement proposal
Add  [protected_branch_ids](https://docs.gitlab.com/ee/api/merge_request_approvals.html#create-project-level-rule) to the [project_level_mr_approvals](https://registry.terraform.io/providers/gitlabhq/gitlab/latest/docs/resources/project_level_mr_approvals) resource.

As it currenty stands my organization has different approval rules for different branches in place.  I would love to be able to scope the current resource to a branch instead of only being able to specify general rules for every branch on the project

**Comment by Shocktrooper** [comment]
If someone can throw me areas of the code I need to edit I would try to take a swing at this one albeit I have not worked with go code before

**Comment by armsnyder** [comment]
@Shocktrooper We added [project_approval_rule](https://registry.terraform.io/providers/gitlabhq/gitlab/latest/docs/resources/project_approval_rule) in the latest release 3.2.0, but it's missing a `protected_branch_ids` argument.

The code for this resource is in [resource_gitlab_project_approval_rule.go](https://github.com/gitlabhq/terraform-provider-gitlab/blob/master/gitlab/resource_gitlab_project_approval_rule.go) and its test is [resource_gitlab_project_approval_rule_test.go](https://github.com/gitlabhq/terraform-provider-gitlab/blob/master/gitlab/resource_gitlab_project_approval_rule_test.go). Those should be the only files that need modifying. It should be a pretty basic addition, and you can follow the patterns you see in the code. Good luck! 😄
