### ISSUE TITLE
Acceptance tests not working

### ISSUE THREAD

**Issue by armsnyder** [gitlabhq/terraform-provider-gitlab#493]
I've noticed in two active PRs that there are written tests which should be failing but are not failing.

Example job: https://github.com/gitlabhq/terraform-provider-gitlab/pull/449/checks?check_run_id=1443975846

The acceptance tests in PRs are succeeding after just 43 seconds, so I don't think they're actually running.

@nicholasklick we should probably not release again until we can sort this out, since there would have been PRs merged into master while this problem existed.

**Comment by nicholasklick** [comment]
@armsnyder good catch. It appears they stopped running here: https://github.com/gitlabhq/terraform-provider-gitlab/actions/runs/370175052

**Comment by nicholasklick** [comment]
```
Starting gitlab container...
Unable to find image 'gitlab/gitlab-ce:latest' locally
latest: Pulling from gitlab/gitlab-ce
2c11b7cecaa5: Pulling fs layer
04637fa56252: Pulling fs layer
```
vs
```
not starting gitlab!
==> Checking that code complies with gofmt requirements...
```

I wonder if we dont need a spec to ensure gitlab has started?

**Comment by armsnyder** [comment]
@nicholasklick When you get a chance can you look at #495, and if that can be merged maybe then @btyy77c could take a look at #494?
