### ISSUE TITLE
gitlab_project resource does not support allow configuration of the CI configuration path

### ISSUE THREAD

**Issue by justin-ldn** [gitlabhq/terraform-provider-gitlab#497]
The gitlab_project resource goes not support allow configuration of the CI configuration path.

https://gitlab.wsq.io/help/ci/pipelines/settings#custom-ci-configuration-path

### Terraform Version
0.13.2

### Affected Resource(s)
- gitlab_project

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
resource "gitlab_project" "terraform" {
  ...
  custom_ci_configuration_path = "azure-client-ci.yml@path/to/terraform-ci"
  ...
}
```

### Debug Output
N/A

### Panic Output
N/A

### Expected Behavior

Should be supported.

### Actual Behavior

Not supported - need to set using web interface.

### Steps to Reproduce
N/A

### Important Factoids
Setting a CI path is important to prevent escalation issues where committers gain access to update the CI with arbitrary code that can access credentials.

### References
N/A

**Comment by armsnyder** [comment]
Overlaps with #477

**Comment by kitos9112** [comment]
Hi,

I've raised an MR to cover this super useful use case --> https://github.com/gitlabhq/terraform-provider-gitlab/pull/662

**Comment by cmd-werner** [comment]
This has been added in provider 3.7.0
