### ISSUE TITLE
TFE plan output into Gitlab MR request

### ISSUE THREAD

**Issue by Stromweld** [gitlabhq/terraform-provider-gitlab#501]
@nicholasklick our Hashi reps told us to mention you in this request. 

### Terraform Version
0.13.5
Gitlab.com SaaS version

### Expected Behavior
When running CI/CD pipeline with VCS configured workspace in TFE or TFC, with default remote execution, it would be nice to get a copy of the terraform plan output in the gitlab MR request and not just the summary with a link to the TFE or TFC server.
This is standard behaviour in Github pull requests.

### Actual Behavior
Step passes and shows summary of changes and when clicked takes you to the TFE or TFC server.

### Steps to Reproduce
Create a Gitlab TF project and on a TFE server or TFC create a VCS driven workspace linked to the Gitlab project. Add TF files and create an MR request.

**Comment by armsnyder** [comment]
@Stromweld This sounds like a request for the Terraform CI/CD feature of GitLab. The issue tracker for that would be the regular GitLab issue tracker: https://gitlab.com/gitlab-org/gitlab/-/issues.
