### ISSUE TITLE
Remove testing user token when provider is configured

### ISSUE THREAD

**Issue by btleedev** [gitlabhq/terraform-provider-gitlab#506]
Hi,

In my terraform scripts I have an optional GitLab resource that the user can create if a boolean is true/false. The problem I'm having is when

1. the above boolean is _false_, AND
2. the user provides a blank or invalid token, AND
3. there are no GitLab resources to be looked up, created, updated, or deleted,

then the GitLab provider throws a 401 error. This is because when the provider is configured, it tests the credentials. Is there a specific reason it does this? The ask is for this test to be removed, or at least make the test optional via some attribute. See https://github.com/gitlabhq/terraform-provider-gitlab/blob/master/gitlab/config.go.

Let me know if I'm not thinking about this the right way.

### Terraform Version
0.12.29

### Affected Resource(s)
- N/A - provider instantiation

### Terraform Configuration Files
```hcl
variable "gitlab_kubernetes_integration_enabled" {
  description = "Boolean to indicate whether to add the kubernetes cluster to a GitLab group"
  type = bool
}
variable "gitlab_auth_token" {
  description = "An auth token with permission to add the EKS environment to a GitLab group"
  type        = string
  default     = ""
}
variable "gitlab_base_url" {
  description = "The base url for the GitLab instance, EG: https://gitlab.com/api/v4"
  type        = string
  default     = "https://gitlab.com/api/v4"
}
```
```hcl
provider "gitlab" {
  token = var.gitlab_auth_token
  base_url = var.gitlab_base_url
}
```
```hcl
resource "gitlab_group_cluster" "bar" {
  count = var.gitlab_kubernetes_integration_enabled ? 1 : 0

  group                         = "my-group"
  name                          = "my-name"
  enabled                       = true
  managed                       = false
  kubernetes_api_url            = "https://localhost/"
  kubernetes_token              = "some-token"
  kubernetes_ca_cert            = "some-cert"
  kubernetes_authorization_type = "rbac"
  environment_scope             = "*"
}
```

### Expected Behavior
When

1. `gitlab_kubernetes_integration_enabled` is false, AND
2. `gitlab_auth_token` is blank , AND
3. there are no GitLab resources to be looked up, created, updated, or deleted.

### Actual Behavior
What actually happened?
```
Error: GET https://git.nasdaq.com/api/v4/user: 401 {message: 401 Unauthorized}
  on .terraform/modules/eks-dcaas.eks-dcaas/providers.tf line 22, in provider "gitlab":
  22: provider "gitlab" {
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan`
2. specify `gitlab_kubernetes_integration_enabled` to `false`

**Comment by armsnyder** [comment]
@roidelapluie Do you have any insight into the purpose of this check? I'm wondering if we can remove it, or if it is needed, defer the API call until the first time the client is used. https://github.com/gitlabhq/terraform-provider-gitlab/blob/ef0ddea75d64794283f181dce06c6395f6dfdfe6/gitlab/config.go#L75

**Comment by sodre** [comment]
I am also facing this issue in our Premium install of GitLab. We are using the provider to do project name to project id conversion, as well as access the terraform remote state stored in the gitlab projects. 

My workaround is to currently put a "bot" account token in the CI/CD variables.

**Comment by sdlarsen** [comment]
I'm seeing this as well, but only after upgrading to terraform 0.15 (from plain terraform, no CI/CD). I'm using the 3.6.0 gitlab provider. 
The setup of our infrastructure (k8s cluster) works just fine, but errors out with the 401 on tear-down.

**Comment by timofurrer** [comment]
The provider now supports a `early_auth_check` provider flag, which can be set to `false` to avoid that call (#787 ).

I'm going to close this 🎉
