### ISSUE TITLE
Support Project Access Tokens

### ISSUE THREAD

**Issue by nicholasklick** [gitlabhq/terraform-provider-gitlab#508]
We should support [Project access tokens](https://docs.gitlab.com/ee/user/project/settings/project_access_tokens.html)

**Comment by armsnyder** [comment]
@nicholasklick From the API docs, it looks like the usage of project access tokens is identical to personal access tokens, so authenticating the plugin using a project access token should work as-is, right? https://docs.gitlab.com/ee/api/README.html#personalproject-access-tokens

**Comment by armsnyder** [comment]
Ah, I just noticed the "new-resource" label, so you meant a resource. I don't see an API doc for creating project access tokens. If it's only possible to create them using the UI, then we can't support it in the plugin.

**Comment by armsnyder** [comment]
Found the upstream issue: https://gitlab.com/gitlab-org/gitlab/-/issues/238991

**Comment by randomswdev** [comment]
WE are interested in developing a pull request implementing this enanchement. Just checking if somebody else is already working on this. If I'll receive no answer, we will move forward with the implementation.

**Comment by roidelapluie** [comment]
I don't think so, you're welcome!

**Comment by armsnyder** [comment]
Just an fyi - the API for this feature is being released in GitLab version 13.10 on March 22nd, so we won't be able to get passing acceptance tests for a new resource any earlier than that.

https://about.gitlab.com/upcoming-releases/

**Comment by randomswdev** [comment]
> 
> 
> Just an fyi - the API for this feature is being released in GitLab version 13.10 on March 22nd, so we won't be able to get passing acceptance tests for a new resource any earlier than that.
> 
> https://about.gitlab.com/upcoming-releases/

In the announcement I see they refer to `Scope personal access tokens to specific projects [BE]`; but I think personal access tokens are different from project access tokens, that are the ones I'm interested at.

I tested project access tokens in 13.9.1 and they appear to work. My idea was to provide a pull request that just supports project access tokens. Is it ok?

**Comment by armsnyder** [comment]
@randomswdev You're right, my mistake. 😄 A contribution for project access tokens would be very welcome! https://docs.gitlab.com/ee/api/resource_access_tokens.html

**Comment by armsnyder** [comment]
@randomswdev I just re-read the issue comments to see why I thought it was being released in 13.10. It's because the 13.9 version of the API does not give you the value of the token: https://gitlab.com/gitlab-org/gitlab/-/issues/323088

**Comment by randomswdev** [comment]
> 
> 
> @randomswdev I just re-read the issue comments to see why I thought it was being released in 13.10. It's because the 13.9 version of the API does not give you the value of the token: https://gitlab.com/gitlab-org/gitlab/-/issues/323088

Thanks for the info. We looked at the API and performed some basic testing, but we were not aware of this. We will start anyhow working on the pull request and wait for the official release of 13.10 to complete testing and remove the WIP.

**Comment by randomswdev** [comment]
We are moving forward with the implementantion, trying to integrate support for project tokens in the go-gitlab library: https://github.com/xanzy/go-gitlab/issues/1098

**Comment by randomswdev** [comment]
The go-gitlab library has just been released today, including the update for the project access token.

We just updated the pull request (https://github.com/gitlabhq/terraform-provider-gitlab/pull/588), that is thus ready for review.

**Comment by PedDavid** [comment]
The "waiting" label can be removed then, right? I couldn't see a pattern in PR being approved / landed and releases, is there any sort of schedule and / or ETA?

**Comment by randomswdev** [comment]
Looking at the waiting label tool tip it indicates that the pull request is blocked by some other issue. I think it is not really blocked: GitLab with the required fixes has been released (version 13.10) and the PR is ready for review.
The PR is also passing all the automatic tests, that use the last version of gitLab (13.10).

**Comment by mericano1** [comment]
Has anyone got a workaround while this is being reviewed and merged ?

**Comment by dhrapson** [comment]
It would be great to get that into the next release too

**Comment by timofurrer** [comment]
We've merged #588 and it will be included in the next release. I'm going to close this 🎉
