### ISSUE TITLE
resource_gitlab_deploy_key.key as sensitive resource attribute

### ISSUE THREAD

**Issue by Mpluya** [gitlabhq/terraform-provider-gitlab#514]
### Terraform Version
Terraform v0.14.3

### Affected Resource(s)
Please list the resources as a list, for example:
- resource_gitlab_deploy_key

### Terraform Configuration Files
```hcl
resource "gitlab_deploy_key" "example" {
  project = "example/deploying"
  title   = "Example deploy key"
  key     = "ssh-rsa AAAA..."
}
```

### Debug Output
n/a

### Panic Output
n/a

### Expected Behavior
Is there appetite to take advantage of Terraform's experimental feature - `Sensitive Resource Attributes`? One avenue where we could take advantage of this is in resource_gitlab_deploy_key.key. From what I understood from this feature, we would need to mark the [schema](https://github.com/gitlabhq/terraform-provider-gitlab/blob/master/gitlab/resource_gitlab_deploy_key.go#L33) mapped to this attribute sensitive, and terraform will show a placeholder marker instead of revealing deploy_key.key in the terraform plan, etc.

**Comment by armsnyder** [comment]
Yep, it looks like we would need to add `Sensitive: true` to this schema attribute.

**Comment by armsnyder** [comment]
@Mpluya I realized that the `key` attribute is a public key, so I don't think it should be treated as sensitive.

**Comment by Mpluya** [comment]
@armsnyder i overlooked that part, thanks for catching. I agree with your recommendation.
