### ISSUE TITLE
Sensitive data are shown as plain text in terraform logs

### ISSUE THREAD

**Issue by kingindanord** [gitlabhq/terraform-provider-gitlab#515]
I am not sure if here is the right place to post this issue, anyways it wont harm anyone. 

I was debugging my terraform scripts while using the github providers. Below is an example of my script.

```HCL

terraform {
  required_providers {
    gitlab = {
      source = "gitlabhq/gitlab"
      version = "3.3.0"
    }
  }
}

provider "gitlab" {
    token = var.gitlab_token
}


data "gitlab_group" "brainstorming" {
  full_path           = "brainstorming"

}

resource "gitlab_group_variable" "aws_secret_key_brainstorming" {

   group   = data.gitlab_group.brainstorming.full_path
   key       = "AWS_SECRET_ACCESS_KEY"
   value     = aws_iam_access_key.brainstorming.secret
   protected = false
   masked = true
}
```

The problem is that I can see my gitlab token and the masked variable as clear text in the terraform logs:

2021-01-02T20:06:59.197Z [DEBUG] plugin.terraform-provider-gitlab_v3.3.0: 2021/01/02 20:06:59 [DEBUG] GitLab API Request Details:

2021-01-02T20:06:59.197Z [DEBUG] plugin.terraform-provider-gitlab_v3.3.0: Content-Length: 140
2021-01-02T20:06:59.197Z [DEBUG] plugin.terraform-provider-gitlab_v3.3.0: Accept: application/json
2021-01-02T20:06:59.197Z [DEBUG] plugin.terraform-provider-gitlab_v3.3.0: Content-Type: application/json
**2021-01-02T20:06:59.197Z [DEBUG] plugin.terraform-provider-gitlab_v3.3.0: Private-Token: <"Plain Text token">**
2021-01-02T20:06:59.197Z [DEBUG] plugin.terraform-provider-gitlab_v3.3.0: Accept-Encoding: gzip
2021-01-02T20:06:59.197Z [DEBUG] plugin.terraform-provider-gitlab_v3.3.0: 
2021-01-02T20:06:59.197Z [DEBUG] plugin.terraform-provider-gitlab_v3.3.0: {
2021-01-02T20:06:59.197Z [DEBUG] plugin.terraform-provider-gitlab_v3.3.0:  "key": "AWS_SECRET_ACCESS_KEY",
**2021-01-02T20:06:59.197Z [DEBUG] plugin.terraform-provider-gitlab_v3.3.0:  "value": <"Plain Text Value">,**
2021-01-02T20:06:59.197Z [DEBUG] plugin.terraform-provider-gitlab_v3.3.0:  "variable_type": "env_var",
2021-01-02T20:06:59.197Z [DEBUG] plugin.terraform-provider-gitlab_v3.3.0:  "protected": false,
2021-01-02T20:06:59.197Z [DEBUG] plugin.terraform-provider-gitlab_v3.3.0:  "masked": true
2021-01-02T20:06:59.197Z [DEBUG] plugin.terraform-provider-gitlab_v3.3.0: }

is this behaviour as designed? or there are ways to hide these tokens and sensitive secrets?

**Comment by SvenMW** [comment]
any update on this?

Is additional information needed? This seems like a security issue to me?

**Comment by kuahyeow** [comment]
As mentioned by  @btyy77c , The `value` attribute is already marked as Sensitive = true - https://github.com/gitlabhq/terraform-provider-gitlab/blob/f821d591b6fdb7e388c3eed2b637e758900fb553/gitlab/resource_gitlab_group_variable.go#L32-L35. 

Reading https://www.terraform.io/docs/extend/best-practices/sensitive-state.html it should have prevented it from being shown ? 🤔 

I guess this will affect [project variables](https://github.com/gitlabhq/terraform-provider-gitlab/blob/f821d591b6fdb7e388c3eed2b637e758900fb553/docs/resources/project_variable.md) as well.

**Comment by SvenMW** [comment]
Hi,

thanks for your response!

> As mentioned by @btyy77c , The `value` attribute is already marked as Sensitive = true -
> 
> https://github.com/gitlabhq/terraform-provider-gitlab/blob/f821d591b6fdb7e388c3eed2b637e758900fb553/gitlab/resource_gitlab_group_variable.go#L32-L35

I'm terribly sorry, but where did @btyy77c mention this? I can't find this information in this issue?

**Comment by kuahyeow** [comment]
> I'm terribly sorry, but where did @btyy77c mention this? I can't find this information in this issue?

@SvenMW, Sorry I was unclear, this was in a Zoom conversation with @btyy77c (we both work for GitLab)

**Comment by roidelapluie** [comment]
Hello,

This is expected. It is not a bug.

**Comment by roidelapluie** [comment]
Here is the statement from @radeksimko 

https://github.com/gitlabhq/terraform-provider-gitlab/pull/93#issuecomment-466663973
> The debug log is only available to those who are capable of enabling the debug mode, which are in all (?) cases the same people who provide these (sensitive) credentials through configs or ENV variables in the first place.

> We had some early discussions about scrubbing sensitive data internally and we might introduce a solution for that at some point in the future.


This provider behaves the same as all the other terraform providers in this matter.

**Comment by btyy77c** [comment]
Hello!

It seems the `terraform-plugin-sdk` does not offer a way to scrub request/response info with `TF_LOG=DEBUG`. Here is a related issue: https://github.com/hashicorp/terraform-plugin-sdk/issues/2. 

The issue does mention:

> providers are writing values to stderr that they don't want written to stderr.

I haven't seen any of our `log.Printf("[DEBUG] ...")` statements include sensitive data. If you see any, please let us know so we can make updates!   

Otherwise, we'll need to wait for updates from the `terraform-plugin-sdk`.

I think we can close this issue for now. We can reopen if updates are made to the SDK.

Thanks!
