### ISSUE TITLE
Add support for managing `Default description template for merge requests` property

### ISSUE THREAD

**Issue by radkomateusz** [gitlabhq/terraform-provider-gitlab#517]
Hi there,

I want to submit feature request: 
Add support for managing `Default description template for merge requests` vie gitlab terraform provider. 

Currently I don't see any option to mange it using terraform. 

Option is under: Settings -> General -> Merge Request -> Default description template for merge requests

It could be done under `gitlab_project` resource or new resource could be added. 

Thanks.

**Comment by armsnyder** [comment]
It looks like the GitLab API doesn't support this attribute yet, but there is an issue for it: https://gitlab.com/gitlab-org/gitlab/-/issues/885 Unfortunately we can't add this feature to the plugin until it is supported by the API.

@nicholasklick Side note: Do you have a recommended way for us to triage requests like this one? For now I'm leaving them open and added a "waiting" label.

**Comment by mansona** [comment]
So... It looks like https://gitlab.com/gitlab-org/gitlab/-/issues/885 was actually closed and my best guess is that it was added in version 3.10 of GitLab 🤔  

Ah I actually found the API documentation: https://docs.gitlab.com/ee/api/projects.html#templates-for-issues-and-merge-requests it looks like it's only available to Premium customers but it would be nice if the gitlab provider supported it 👍
