### ISSUE TITLE
Maintain the CHANGELOG

### ISSUE THREAD

**Issue by svenstaro** [gitlabhq/terraform-provider-gitlab#521]
Hey, it would appear like the CHANGELOG.md file is several versions out of date. Could you start maintaining it again?

I think it's quite helpful to look at it during upgrades.

**Comment by nicholasklick** [comment]
@svenstaro thanks for raising this issue. This was a bit of an oversight. We need to automate this.

I just manually updated it for now: https://github.com/gitlabhq/terraform-provider-gitlab/commit/f36b1e79bd40d11b454079b8a0ac710b60e69971

Thanks!
