### ISSUE TITLE
gitlab_deploy_token and expires_at

### ISSUE THREAD

**Issue by dimitrismistriotis** [gitlabhq/terraform-provider-gitlab#522]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version

```
terraform -v
Terraform v0.14.5
+ provider registry.terraform.io/gitlabhq/gitlab v3.4.0

terraform init -upgrade

Initializing the backend...

Initializing provider plugins...
- Finding gitlabhq/gitlab versions matching "3.4.0"...
- Installing gitlabhq/gitlab v3.4.0...
- Installed gitlabhq/gitlab v3.4.0 (signed by a HashiCorp partner, key ID BC097C3333027B14)

Partner and community providers are signed by their developers.
If you'd like to know more about provider signing, you can read about it here:
https://www.terraform.io/docs/plugins/signing.html
```

### Affected Resource(s)

- gitlab_deploy_token

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
resource "gitlab_deploy_token" "PROJECT_token" {
  project    = gitlab_project.PROJECT.id
  name       = "Deploy Token for ABCD"
  username   = "deploy-token-0001"
  scopes     = ["read_repository"]
  expires_at = "2025-03-14T00:00:00.000Z"
}

```

### Expected Behaviour

Above "expires_at" is a copy-paste from your example +5 years in the future. This was ALWAYS triggering a recreation of the token as "expires_at" was changing. After lots of trial and error  found that `"2025-03-14T00:00:00Z"` (removing trailing ".000") does not trigger a recreation.

Guess that either the example should change or how date-time is handled.

**Comment by armsnyder** [comment]
One option would be for someone to contribute a `DiffSuppressFunc` for this attribute which parses and compares the values as `time.Time`.
