### ISSUE TITLE
Add functionality to "wait for project import to be finished"

### ISSUE THREAD

**Issue by bramceulemans** [gitlabhq/terraform-provider-gitlab#528]
### Terraform Version

Terraform v0.14.5

### Affected Resource(s)

- gitlab_project

### Suggestion

When importing a lot of projects in a for_each loop, it would be nice to be able to wait until the project import is done. Currently when making 30 projects, it will create them concurrently (even when parallelism is set to 1), because the provider does not wait for a project to be "finished" importing (when creating a project from a template).

**Comment by armsnyder** [comment]
Looking at the code, it should be waiting already. Can you run Terraform with `TF_LOG=TRACE` and provide a gist with the log output?

**Comment by bramceulemans** [comment]
It seems that some of the imports time out and never complete. I am not sure what the problem is.

**Comment by armsnyder** [comment]
That sounds very likely. The timeout is 1 minute and should definitely be more.

**Comment by bramceulemans** [comment]
I assume this is a timeout controlled by Gitlab and not this provider?

**Comment by roidelapluie** [comment]
It is this provider and there is a PR for this: #536
