### ISSUE TITLE
Add "prevent forking project outside of group" attribute to "gitlab_group" resource

### ISSUE THREAD

**Issue by Shocktrooper** [gitlabhq/terraform-provider-gitlab#529]
As the title states there is an option in GitLab to prevent the forking of projects outside of the group that owns them.  
The gitlab_group resouce would have to be modified to add this in.

applicable license tier's
- premium
- silver

Relevant Links:
- https://docs.gitlab.com/ee/user/group/#prevent-project-forking-outside-group

**Comment by RomanNess** [comment]
I did a quick research on this. GitLab API docs only document the parameter `prevent_forking_outside_group` for the `update` endpoint of `group` (not for `create`). https://docs.gitlab.com/ce/api/groups.html#update-group

`xanzy/go-gitlab` uses the same object for both `create` and `update` and does not implement `prevent_forking_outside_group` yet, so there is no quick way to add this feature without updating `xanzy/go-gitlab` first.
https://github.com/xanzy/go-gitlab/blob/c6c635e0a8eb95dbca3d9994cc83e484f973ee34/groups.go#L224

**Comment by armsnyder** [comment]
It's not a documentation bug. I confirmed this with the REST API locally. The `POST /api/v4/groups` API ignores the form field `prevent_forking_outside_group=true`. It can only be set using an update (`PUT`).

This means that in the resource's create function, we would need to also call the go-gitlab update function, in the case where `prevent_forking_outside_group=true`.

**Comment by Shocktrooper** [comment]
Is this something that should probably wait until GitLab is able to pass back this value in a read type API call.  Otherwise you are assuming the state is one thing if someone changes it manually on the backend creating a delta that cannot be seen with terraform

**Comment by Shocktrooper** [comment]
It would appear that GitLab themselves has in their Groups API the ability to read this value and also update it although the documentation makes no mention of this being an attribute in their own documentation.  A go-gitlab update is all that would be needed to implement this.  I have verified this can be set/read myself with a put/get request to my own instance

**Comment by jtymes** [comment]
I added it to the struct in https://github.com/xanzy/go-gitlab/pull/1390 (it was in the edit one, but not the base 🤷), so this should be doable on a new release of go-gitlab.

**Comment by jtymes** [comment]
I'm working on this.
