### ISSUE TITLE
Bi-monthly meeting

### ISSUE THREAD

**Issue by roidelapluie** [gitlabhq/terraform-provider-gitlab#534]
Hello @nicholasklick @armsnyder @dnsmichi

I am wondering if we could setup a meeting every 2 weeks (1h) to go over the pull requests and the issues. We could make that public in such a way that the community would be free to join us.

Goals:
- Look over past issues and pull request, review, comment, etc.
- Look at when/what to release.

Over time we might reduce the candence to 1/month once we have cleaned backlog.

**Comment by armsnyder** [comment]
I like the idea of an open meeting.

If you're picking a time, 18:30-07:00 UTC is good for me.

Regarding our backlog, just so you're aware, I went though the issues last year and added appropriate labels, and have been staying on top of that for new ones. Issues labeled with "help wanted" are ones needing more community+maintainer involvement, so those would be especially good to review.

The pull request backlog I'm admittedly less on top of. 😄

**Comment by roidelapluie** [comment]
I am very well aware of you **huge** work. I am also seeing this as a better/new way to collaborate with the people inside gitlab.

**Comment by btyy77c** [comment]
I can help coordinate a meeting. Just let me know!

**Comment by nicholasklick** [comment]
@roidelapluie @armsnyder @btyy77c 

Thanks for proposing this. Much appreciated.

First I want to state that we greatly appreciated the work of all the maintainers have done in the past and are continuing to do now. Thank you! 

I think meeting regularly might make some sense to organize that work.

At GitLab we try to promote async work when possible, that being said I think a monthly meeting might be doable. 
What if we planned for a monthly planning meeting which would align with the Monthly milestone process we use already at Gitlab? If we need to increase the cadence we can do so.

**Comment by nagyv** [comment]
@roidelapluie We wanted to propose the same with @DonNicoJs as we try to take care of the community and the provider. 

@btyy77c 👋  I know you left GitLab, so would like to double-check if you are still interested in coordinating these meetings.

**Comment by nagyv** [comment]
Please, cast your votes for a monthly community hour: https://docs.google.com/forms/d/e/1FAIpQLSeBMVCZFBCezQv10jxGx0EFCcDeGV3Aa6H_87lvUPtvUaFOAQ/viewform?usp=sf_link

**Comment by Shocktrooper** [comment]
@nagyv There is also that new monthly/bi-monthly code contributor meeting that some people might be interested in if you want to post that here.  Also we can bring awareness to the providers existence in that meeting as well :)

**Comment by nagyv** [comment]
@Shocktrooper Great ideas. Thanks!

**Comment by nagyv** [comment]
The code contributor event: https://www.meetup.com/gitlab-virtual-meetups/events/284654399/

**Comment by nagyv** [comment]
Based on the feedback received, I propose Wednesday 14:30-15:30 UTC. I'll create the first event for April 27. 

Everyone is welcome to join!

**Comment by timofurrer** [comment]
Since we have something established - I'm going to close this one :)
