### ISSUE TITLE
Feature Request - gitlab_project - additional argument reference (option) - Skip outdated deployment jobs

### ISSUE THREAD

**Issue by Gvazzana** [gitlabhq/terraform-provider-gitlab#541]
### Feature Request Details:
Please add the ability to configure the following ci/cd general project settings on the 'Gitlab Project' Resource. Toggle Options could be a Boolean (true / false) or enable, disable
- Auto-cancel redundant, pending pipelines
- Skip outdated deployment jobs

**Comment by armsnyder** [comment]
It sounds like this is an ask to add one more setting: `auto_cancel_pending_pipelines` to the `gitlab_project` resource.

**Comment by RomanNess** [comment]
Thought, I could do a quick PR for this before dinner. Tough luck, `AutoCancelPendingPipelines` is not implemented in `xanzy/go-gitlab` where the `project` is read from API. 
https://github.com/xanzy/go-gitlab/blob/d803e68bb3041a361bb749dbb951026b8e4607bb/projects.go#L40

However, it is already included in POST and PUT.
https://github.com/xanzy/go-gitlab/blob/d803e68bb3041a361bb749dbb951026b8e4607bb/projects.go#L517
https://github.com/xanzy/go-gitlab/blob/d803e68bb3041a361bb749dbb951026b8e4607bb/projects.go#L654

**Comment by Gvazzana** [comment]
Thank you for the update. Is there anyway to request this feature be added to the gitlab API, with more weight coming from the Terraform Provider group?

**Comment by RomanNess** [comment]
I'm not sure if it is missing in the REST API or if it is just not yet implemented in `xanzy/go-gitlab`. The first step would be to clarify this. 
Then for the latter case there's always the option to contribute the missing attributes or at least to file an issue in `xanzy/go-gitlab` that links this issue.

**Comment by ngoduykhanh** [comment]
**Auto-cancel redundant, pending pipelines** is `auto_cancel_pending_pipelines`
**Skip outdated deployment jobs** is `ci_forward_deployment_enabled`

They are both available in Gitlab API but missing from `xanzy/go-gitlab`.
| Name                          | GitLab-API GET | GitLab-API POST | GitLab-API PUT | xanzy/go-gitlab GET | xanzy/go-gitlab POST | xanzy/go-gitlab PUT |
|-------------------------------|----------------|-----------------|----------------|---------------------|----------------------|---------------------|
| auto_cancel_pending_pipelines |        x       |        x        |        x       |                     |           x          |          x          |
| ci_forward_deployment_enabled |        x       |                 |        x       |                     |                      |                     |

Is it possible to add `auto_cancel_pending_pipelines` without modifying  `xanzy/go-gitlab` ?

**Comment by Gvazzana** [comment]
Hello,
Checking on this issue. 
It would solve a lot of issues for us, in having to grant developers access to projects created with terraform, just so they can set these settings in the Gitlab GUI manually, which prevents our pipelines from failing. 
We then have to revoke access to the project from the developers.

How can we get this issue moving?
Thank you

**Comment by jgspratt** [comment]
I would like to know if there is any progress on this.

**Comment by armsnyder** [comment]
Both of these options `auto_cancel_pending_pipelines` and `ci_forward_deployment_enabled` are in the `go-gitlab` package now.

There is a PR open for adding `ci_forward_deployment_enabled` which should be merged in the next couple days. (#732).

I don't see a PR for `auto_cancel_pending_pipelines`, so anyone is welcome to work on adding that.

**Comment by timofurrer** [comment]
This will be addressed and fixed with #917.
