### ISSUE TITLE
[Suggestion] Use terrafmt on website docs and test cases for consistency

### ISSUE THREAD

**Issue by sirlatrom** [gitlabhq/terraform-provider-gitlab#548]
Coming from having made some PRs in the terraform-provider-azurerm repo, I've noticed some differences.

Terraform configuration in test cases and docs is not formatted as one would expect after running `terraform fmt`, which is something the tool `terrafmt` can help with.

See for instance their GNUmakefile:

https://github.com/terraform-providers/terraform-provider-azurerm/blob/c6e055eb6c40998b84f93b2aeaa3b7a4a846b31d/GNUmakefile#L47-L51

The tool is in github.com/katbyte/terrafmt and they install it in their `tools` target:

https://github.com/terraform-providers/terraform-provider-azurerm/blob/c6e055eb6c40998b84f93b2aeaa3b7a4a846b31d/GNUmakefile#L13-L22

If this were made part of the GitHub Actions for PRs, you could ensure docs and test cases were properly formatted going forward, and make it easier for contributors to follow the expected formatting.

**Comment by armsnyder** [comment]
Sounds like a win to me. We've had HCL bugs in our docs in the past.

**Comment by armsnyder** [comment]
This was done in #802
