### ISSUE TITLE
Define Gitlab Supported Versions

### ISSUE THREAD

**Issue by armsnyder** [gitlabhq/terraform-provider-gitlab#550]
Our acceptance tests always run against the latest stable version of Gitlab.

@roidelapluie Do you know if this provider also expected to work for previous Gitlab versions? I imaging formally defining version support in our README would help set expectations.

What do you think about updating our acceptance test matrix to also run the test suite on a) The previous minor Gitlab release, and b) The previous major Gitlab release? For example:

* `gitlab/gitlab-ce:13.8.2-ce.0`
* `gitlab/gitlab-ce:13.7.6-ce.0`
* `gitlab/gitlab-ce:12.10.14-ce.0`
* `gitlab/gitlab-ee:13.8.2-ee.0`
* `gitlab/gitlab-ee:13.7.6-ee.0`
* `gitlab/gitlab-ee:12.10.14-ee.0`

I don't think we need to statically define these versions anywhere, since so far we've been ok letting the suite run against `latest`, so I'd hope these image tags could be looked up dynamically. (This means there is the potential for us to introduce a breaking change in a minor release of this provider plugin, for an older version of Gitlab, but this has been the case for us historically anyway because we always run tests on `latest`.)

**Comment by roidelapluie** [comment]
Let's not deviate too much from https://docs.gitlab.com/ee/policy/maintenance.html#patch-releases
