### ISSUE TITLE
SDK v2

### ISSUE THREAD

**Issue by armsnyder** [gitlabhq/terraform-provider-gitlab#552]
[Upgrade to the Terraform Plugin SDK v2](https://www.terraform.io/docs/extend/guides/v2-upgrade-guide.html)

This is a potentially breaking change, since the minimum supported Terraform version becomes 1.12. HashiCorp recommends doing a major provider release when taking this upgrade.

**Comment by floh96** [comment]
@armsnyder @roidelapluie  fyi v1 will be eol on July 31, 2021. [announcement](https://discuss.hashicorp.com/t/end-of-life-timeline-for-v1-of-the-terraform-plugin-sdk/24991?u=aareet)
