### ISSUE TITLE
Documentation: This module needs to define what the required token scope is

### ISSUE THREAD

**Issue by Routhinator** [gitlabhq/terraform-provider-gitlab#557]
The docs for this module, and the Gitops demo at https://gitlab.com/gitops-demo/readme both fail to cover any information about the token required for this module.

Is it:
- A deploy token?
- A users personal access token?
- A group token?

Does it's access need to be:
- Scoped to everything?
- Scoped to just the API?

Really need to a paragraph here - or link to Gitlab documentation. 

It's overly vague at the moment.

**Comment by Routhinator** [comment]
For anyone landing here because they are similarly confused by the docs; sadly this needs to be a Persona Access Token created by a specific user.

...which means your CI will break if that user leaves the org.

**Comment by magic7s** [comment]
@Routhinator you can create a service/bot account and use a Personal Access Token under that account to avoid the issue of it being tied to a human.

**Comment by timofurrer** [comment]
It's actually documented in the provider config as:

> The OAuth2 token or project/personal access token used to connect to GitLab. It must be provided, but it can also be sourced from the GITLAB_TOKEN environment variable.

Also see: https://docs.gitlab.com/ee/api/#authentication
