### ISSUE TITLE
gitlab_project destroy doesn't wait for repository delete

### ISSUE THREAD

**Issue by armsnyder** [gitlabhq/terraform-provider-gitlab#566]
Recent acceptance test failure: https://github.com/gitlabhq/terraform-provider-gitlab/pull/565/checks?check_run_id=1877859420

```
=== RUN   TestAccGitLabProjectApprovalRule_import
Error:     testing.go:745: Error destroying resource! WARNING: Dangling resources
        may exist. The full state and error is shown below.
        
        Error: Check failed: Repository still exists
        
        State: <no state>
--- FAIL: TestAccGitLabProjectApprovalRule_import (10.19s)
```

The test creates a gitlab_project, and the error is from the `testAccCheckGitlabProjectApprovalRuleDestroy` function, which calls `testAccCheckGitlabProjectDestroy`.

I think we need to do like #539 for gitlab_project.

**Comment by armsnyder** [comment]
Ran locally on master branch with TF_LOG=DEBUG. The test seems to fail about half of the time.

https://gist.github.com/armsnyder/772669a831dc4731cdb4839e75c31005

```
2021/02/11 13:59:47 [DEBUG] Starting graph walk: walkPlanDestroy

<snip>

2021/02/11 13:59:47 [DEBUG] gitlab_project.foo: applying the planned Delete change
2021/02/11 13:59:47 [DEBUG] Delete gitlab project 120
2021/02/11 13:59:47 [DEBUG] GitLab API Request Details:
---[ REQUEST ]---------------------------------------
DELETE /api/v4/projects/120 HTTP/1.1

<snip>

-----------------------------------------------------
2021/02/11 13:59:47 [DEBUG] GitLab API Response Details:
---[ RESPONSE ]--------------------------------------
HTTP/1.1 204 No Content

<snip>

-----------------------------------------------------
2021/02/11 13:59:52 [DEBUG] GitLab API Request Details:
---[ REQUEST ]---------------------------------------
GET /api/v4/projects/120 HTTP/1.1

<snip>

-----------------------------------------------------
2021/02/11 13:59:52 [DEBUG] GitLab API Response Details:
---[ RESPONSE ]--------------------------------------
HTTP/1.1 404 Not Found

<snip>

2021/02/11 13:59:54 [DEBUG] provider has no plugin.Client
2021/02/11 13:59:54 [DEBUG] New state was assigned lineage "3bcef38e-dd9a-65be-85f7-0a7c5dc5ef56"
2021/02/11 13:59:54 [DEBUG] GitLab API Request Details:
---[ REQUEST ]---------------------------------------
GET /api/v4/projects/120 HTTP/1.1

<snip>

-----------------------------------------------------
2021/02/11 13:59:54 [DEBUG] GitLab API Response Details:
---[ RESPONSE ]--------------------------------------
HTTP/1.1 200 OK

<snip>

-----------------------------------------------------
    testing.go:745: Error destroying resource! WARNING: Dangling resources
        may exist. The full state and error is shown below.
        
        Error: Check failed: Repository still exists
        
        State: <no state>
--- FAIL: TestAccGitLabProjectApprovalRule_import (9.44s)
```

**Comment by armsnyder** [comment]
Thought log as I work on this:

I tried updating the `gitlab_project` delete function's `StateChangeConf` to set `ContinuousTargetOccurence: 3`.

The new behavior is that all tests pass, but `TestAccGitLabProjectApprovalRule_basic` fails reliably with a `WaitForState timeout` error.

> error waiting for project (145) to become deleted: timeout while waiting for state to become 'Deleted'

So something about this test or this resource is causing the project to appear to be deleted initially, but then become stuck in a non-deleted state.

Manually invoking the delete API using curl causes the project to be cleaned up.

```shell
➜ curl -s -o /dev/null -w "%{http_code}\n" -H 'PRIVATE-TOKEN: ACCTEST' http://localhost:8080/api/v4/projects/145
200
➜ curl -s -o /dev/null -w "%{http_code}\n" -XDELETE -H 'PRIVATE-TOKEN: ACCTEST' http://localhost:8080/api/v4/projects/145
202
➜ curl -s -o /dev/null -w "%{http_code}\n" -H 'PRIVATE-TOKEN: ACCTEST' http://localhost:8080/api/v4/projects/145         
404
➜ curl -s -o /dev/null -w "%{http_code}\n" -H 'PRIVATE-TOKEN: ACCTEST' http://localhost:8080/api/v4/projects/145
404
```

I tried adding a `WaitForState` to the `gitlab_project_approval_rule` delete function, but the problem persisted. It doesn't look like the issue is an inconsistent `gitlab_project_approval_rule` deletion. More likely an issue with `gitlab_project` deletion.

**Comment by timofurrer** [comment]
I haven't seen this issue, however the `TestAccGitLabProjectApprovalRule_import` test seems to not exist anymore.
@armsnyder does this still need investigation?

**Comment by armsnyder** [comment]
Seems to not be an issue anymore. Closing as stale. Thanks!
