### ISSUE TITLE
Feature request - force rotation of runner token

### ISSUE THREAD

**Issue by torinthiel** [gitlabhq/terraform-provider-gitlab#581]
The gitlab runner token is readable through gitlab_group and gitlab_project (both resource and datasource). However it's not possible to rotate it using this plugin. It would be nice to be able to somehow force it's rotation directly from terraform.

This will require some shoehorning to fit into terraform's lifecycle. I've initially envisioned something like 

```
resource "gitlab_runner_token" "foo" {
# Change to `triggers` will rotate the token
  triggers = {
    some_dependency = var.force_recreate
  }
}
```

Similar to how the null provider works. This could then be used with e.g. official time provider to force periodic rotation, or just use `terraform taint` or a different variable to enforce rotation.

This however leads to what should be done on delete, as one cannot really delete the token - does delete forces rotation? It's a no-op and creation forces rotation?

**Comment by armsnyder** [comment]
When would you expect the rotation to occur? During each terraform apply?

There's a GitLab issue about adding automatic rotation. Maybe if it's implemented then we can support it in this plugin. https://gitlab.com/gitlab-org/gitlab/-/issues/30942

**Comment by torinthiel** [comment]
As I've said, it requires some shoehorning to fit into TF paradigms.

My initial proposition was a resource, named "gitlab_runner_token", that behaves like this:
* Creation is a no-op (the token is already there)
* Deletion forces token rotation (it 'deletes' the old token)
* It has a single attribute, named `triggers`, that is a map from string to any.
* Any change to the `triggers` attribute forces re-creation

This maintains deterministic behaviour of the plugin. With this, by default, token is not rotated on every run. However user can manually enforce rotation (by using `terraform taint`) or have some way of automatically enforcing it (by e.g. setting trigger to a list of people that should have access to token, or to a date of next rotation by using the https://registry.terraform.io/providers/hashicorp/time/latest/docs/resources/rotating resource, or anything else).

The problem with this approach is that the token is already present in the 'gitlab_group' and 'gitlab_project' resources. If not removed (and that's a backward-incompatible change), and someone uses both in the same project, it would probably mean that during the rotation the group/project resources return incorrect value.
