### ISSUE TITLE
Release needed for apple m1 support

### ISSUE THREAD

**Issue by joepjoosten** [gitlabhq/terraform-provider-gitlab#585]
All developers with apple m1 chip, and use this provider need a release of this provider to be able to use terraform.

We're not able to run terraform in docker, or in rosetta, because both options don't work, and will lead to crashes of terraform (probably not due to the gitlab provider).

So the only solution is to use native m1, and everyone who is using the gitlab provider in there stack and is doing this on an apple m1, needs a release of terraform.

@armsnyder I've added support for go 1.16 in pull request #579 which will make the release available for apple m1 users.

**Comment by armsnyder** [comment]
@nicholasklick This enhancement has been merged. Can we get another release of the provider?

**Comment by joepjoosten** [comment]
I can make a branch based on tag 3.5, with only #579 applied, and it could be version 3.5.1?

**Comment by joepjoosten** [comment]
Any idea when a new release could happen?

**Comment by nicholasklick** [comment]
@joepjoosten @armsnyder Sorry for the slow reply https://github.com/gitlabhq/terraform-provider-gitlab/releases/tag/v3.6.0
