### ISSUE TITLE
Feature Request - Support for Gitlab integrations

### ISSUE THREAD

**Issue by resnostyle** [gitlabhq/terraform-provider-gitlab#587]
I'd like to able to add a discord integration to my gitlab repos.

**Comment by armsnyder** [comment]
@resnostyle Can you use the gitlab_project_hook resource? https://registry.terraform.io/providers/gitlabhq/gitlab/latest/docs/resources/project_hook

**Comment by timofurrer** [comment]
looks stale ... going to close this one. Don't hesitate to jump in and re-open if there is any value in it. Otherwise, please open a new one with a specific up-to-date request. Thanks 🍰
