### ISSUE TITLE
Add an example to the docs on how to use `push_rules`

### ISSUE THREAD

**Issue by nagyv** [gitlabhq/terraform-provider-gitlab#592]
Some users find it hard to define [`push_rules`](https://github.com/gitlabhq/terraform-provider-gitlab/blob/master/gitlab/resource_gitlab_project.go#L197) using the provider. Having an example of the correct syntax would be helpful as they have tried quite a few different approaches without success.

**Comment by willianpaixao** [comment]
Fix #642

**Comment by willianpaixao** [comment]
Maybe this issue can now be closed?

**Comment by armsnyder** [comment]
Thanks @willianpaixao. I think this can be closed.
