### ISSUE TITLE
Add support for garbage collection / clean up of image tags

### ISSUE THREAD

**Issue by srosato** [gitlabhq/terraform-provider-gitlab#594]
I did not find a way in the documentation to configure clean up image tags policy, found in the GitLab Web UI under `Settings > CI/CD > Clean up image tags`

It would be nice to be able to provision for a project the same features found in the UI

- Enable/Disable clean up image tags
- Run clean up every day / two weeks / etc.
- Keep image tags based on regex and keep *x* most recents
- Remove image tags based on regex and remove tags older than *x* days

That would be a nice addition!

**Comment by armsnyder** [comment]
This should be possible, but is blocked at the moment until the feature is supported in the Go GitLab client: https://github.com/xanzy/go-gitlab/issues/1072

**Comment by willianpaixao** [comment]
Hey @armsnyder, the issue above mentioned is already fixed.

**Comment by oschrenk** [comment]
That feature would be great!

**Comment by timofurrer** [comment]
This has been implemented with #917 and will be released with 3.13.0 next week :)
