### ISSUE TITLE
Support build coverage regex

### ISSUE THREAD

**Issue by declension** [gitlabhq/terraform-provider-gitlab#596]
Hi

Please could we add support for creating / editing projects with [`build_coverage_regex`](https://docs.gitlab.com/ee/api/projects.html#create-project)?

Thanks! 

### Terraform Version
`13.1`

**Comment by armsnyder** [comment]
This should be a simple addition. Just need to utilize this field: https://github.com/xanzy/go-gitlab/blob/3645a668a48e08fbecd03d9f887f0b63f0cccda1/projects.go#L122

**Comment by zawazawa0316** [comment]
May I work on this issue?
I have already done resource_gitlab_project.go as of now.
