### ISSUE TITLE
Allow list of strings (user and group names) as values to gitlab_project_approval_rule resource

### ISSUE THREAD

**Issue by BanzaiMan** [gitlabhq/terraform-provider-gitlab#599]
### Terraform Version
0.14.6

gitlab provider version 3.5.0

### Affected Resource(s)
gitlab_project_approval_rule

### Terraform Configuration Files
```hcl
terraform {
  required_version = ">= 0.14.0"
  required_providers {
    gitlab = {
      source  = "gitlabhq/gitlab"
      version = "< 4"
    }
  }
}

provider "gitlab" {
  token    = "XXXXXXXXX"
  base_url = "XXXXXXXXX"
}

resource "gitlab_project_approval_rule" "example-one" {
  project            = 5
  name               = "Example Rule 1"
  approvals_required = 3
  user_ids           = ["user1", "user2"]
  group_ids          = ["group1"]
}
```

### Debug Output
N/A

### Panic Output
N/A

### Expected Behavior
The provider translates the names to ids and sets the approval rule accordingly.

I would like to manage the the users and groups by name, rather than by IDs, in order to reduce the cognitive burden and increase maintainability.

### Actual Behavior
The type is not suitable, the number is required.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan`

**Comment by kerick91** [comment]
revoke

**Comment by sirlatrom** [comment]
This can be done by first looking up the users by name using the [`gitlab_user`](https://registry.terraform.io/providers/gitlabhq/gitlab/latest/docs/data-sources/user) data source and feeding the IDs to the `gitlab_project_approval_rule` resource:
```terraform
data "gitlab_user" "example" {
  for_each = ["user1", "user2"]
  username = each.value
}

data "gitlab_group" "example" {
  for_each  = ["group1"]
  full_path = each.value
}

resource "gitlab_project_approval_rule" "example-one" {
  project            = 5
  name               = "Example Rule 1"
  approvals_required = 3
  user_ids           = [for user in data.gitlab_user.example : user.id]
  group_ids          = [for group in data.gitlab_group.example : group.id]
}
```

**Comment by armsnyder** [comment]
Thanks @sirlatrom for the working example!

Unfortunately with a provider our size we don't have the bandwidth to add features which are not already present in the official GitLab API, unless there is some limitation created by Terraform that we need to work around. We try to align with the upstream API in order to reduce management overhead and compatibility issues, as well as keep code generation on the table.
