### ISSUE TITLE
Support OAuth Tokens

### ISSUE THREAD

**Issue by Lasering** [gitlabhq/terraform-provider-gitlab#60]
The [official terraform documentation](https://www.terraform.io/docs/providers/gitlab/index.html) for the Gitlab provider says that `token` should be a personal access token. Which is correct since [config.go](https://github.com/terraform-providers/terraform-provider-gitlab/blob/master/gitlab/config.go#L49) invokes `client := gitlab.NewClient(httpClient, c.Token)` and [that](https://github.com/xanzy/go-gitlab/blob/master/gitlab.go#L340) is setting the `authType` to be `privateToken`.

However, [provider.go](https://github.com/terraform-providers/terraform-provider-gitlab/blob/master/gitlab/provider.go#L67) has for the `token` description `The OAuth token used to connect to GitLab.` which hints that somewhere is the past `token` could be an OAuth token. Since `go-gitlab` supports OAuth tokens with the [`NewOAuthClient` function](https://github.com/xanzy/go-gitlab/blob/master/gitlab.go#L384) this provider could also support it. I suggest adding a new argument called `oauth_token` which would be optional, and if it was set then the `NewOAuthClient` would be used.

**Comment by Lasering** [comment]
I can make a pull request if that would make it to production faster.

**Comment by armsnyder** [comment]
What would you expect the DELETE operation to do? Should it create a [revert](https://docs.gitlab.com/ee/api/commits.html#revert-a-commit)?

**Comment by armsnyder** [comment]
The documentation should be fixed, but I'm curious, what is the use case for using an OAuth token in Terraform, where a personal access token isn't preferred?

**Comment by Lasering** [comment]
I wanted to have a Gitlab system OAuth application that invoked terraform recipes. In a OAuth application you get an access token which is not a personal access token. Meanwhile I evolved my setup and no longer use a terraform recipe. But seems other people might have a similar use case.

**Comment by wuperry563** [comment]
Hey there @armsnyder , I've actually ran into this problem within my organization as well. I'd like to take some time to contribute to this project. 

My use case is I have a UI App written for Gitlab users to generate a OAuth token, and have users create repos and files they have access rights to. 

Just wanted to make sure no one else is working on this, and that I can pick this up as an assignee.

**Comment by seboudry** [comment]
Hi there!
Is there a plan to make a release with this feature?
