### ISSUE TITLE
Support issues_template and merge_requests_template on gitlab_project

### ISSUE THREAD

**Issue by sirlatrom** [gitlabhq/terraform-provider-gitlab#603]
### Terraform Version
```
$ terraform -v
Terraform v0.14.10
```

### Affected Resource(s)
Please list the resources as a list, for example:
- gitlab_project

### Terraform Configuration Files
```hcl
resource "gitlab_project" "example" {
  name        = "example"
  description = "My awesome codebase"

  visibility_level = "public"

  issues_template         = "foo"
  merge_requests_template = "bar"
}
```

### Debug Output
N/A

### Panic Output
N/A

### Expected Behavior
The fields are available in gitlab_project both as a data source and as a resource.

### Actual Behavior
They are yet to be implemented 😄

### Steps to Reproduce
1. `terraform apply`

### Important Factoids
Only available in GitLab Premium and above.

### References
Dependencies:
- https://github.com/xanzy/go-gitlab/pull/1128

Docs:
- API: https://docs.gitlab.com/ee/api/projects.html#templates-for-issues-and-merge-requests
- Feature: https://docs.gitlab.com/ee/user/project/description_templates.html#set-a-default-template-for-merge-requests-and-issues

**Comment by armsnyder** [comment]
Related to #477

**Comment by radkomateusz** [comment]
Also it's connected with #517
