### ISSUE TITLE
Enhance documentation for gitlab_group_ldap_link resources ldap_provider attribute

### ISSUE THREAD

**Issue by Shocktrooper** [gitlabhq/terraform-provider-gitlab#605]
### Terraform Version
0.14.9

### Affected Resource(s)
- gitlab_group_ldap_link

The documentation for the ldap_provider attribute does specify that you should use the value that is stored in the GitLab database for this resource but we should clarify this to mention it is not the label you see on the UI and possibly link to documentation or document how to retrieve this value as using the label creates the resource but the entry on the UI says this is not a valid LDAP link as the server does not exist

**Comment by armsnyder** [comment]
@Shocktrooper Could you provide a good Terraform config example?

**Comment by Shocktrooper** [comment]
```hcl
resource "gitlab_group_ldap_link" "DEV-DEVELOPER" {
  group_id      = gitlab_group.DEV.id
  cn            = "DEV-DEVELOPER-ED"
  access_level  = "developer"
  ldap_provider = "ldapmain"
}
```

Not sure if the default is always called `ldapmain` but the value on the UI and inside of the gitlab.rb is completely different.  It actually took a little digging to figure out that `ldapmain` was the value I needed to configure this correctly

**Comment by timofurrer** [comment]
> We ran into this issue today. Updating the docs accordingly would be greatly appreciated

@Jasper-Ben would you have some time to create an MR from this? I'd be ready to review and eventually merge it for the upcoming v3.17.0 release in a few days?

**Comment by Jasper-Ben** [comment]
@timofurrer sure thing!
