### ISSUE TITLE
Support group level CI/CD variable environment scope

### ISSUE THREAD

**Issue by sirlatrom** [gitlabhq/terraform-provider-gitlab#610]
### Terraform Version
```
terraform -v
Terraform v0.14.10

Your version of Terraform is out of date! The latest version
is 0.15.0. You can update by downloading from https://www.terraform.io/downloads.html
```

### Affected Resource(s)
Please list the resources as a list, for example:
- gitlab_group_variable (data source and resource)

### Terraform Configuration Files
```hcl
resource "gitlab_group" "example" {
  name = "example"
  path = "example"
}

resource "gitlab_group_variable" "example" {
  group  = gitlab_group.example.id
  key    = "example"
  value  = "example"

  environment_scope = "staging"
}
```

### Debug Output
N/A.

### Panic Output
N/A.

### Expected Behavior
Ability to create a group level variable and set the environment_scope field.

### Actual Behavior
Not yet available :)

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
Only supported in GitLab Premium and above.

### References
- Depends on https://github.com/xanzy/go-gitlab/pull/1137 to be released

**Comment by macnibblet** [comment]
Any chance we might see an update on this?
