### ISSUE TITLE
add personal_access_token resource

### ISSUE THREAD

**Issue by Shocktrooper** [gitlabhq/terraform-provider-gitlab#622]
### Affected Resource(s)
- new: personal_access_token

With the GitLab Users API supporting personal access tokens for a user it would be helpful to be able to manage some of these via terraform.  This is especially helpful with service accounts as this token can then be used to configure a service in another application that is not GitLab

### Important Factoids

- go-gitlab already has the capability to create personal access tokens. 
- Revoking & Listing tokens for a user is a separate API call not apart of the users api. go-gitlab work would need to be done
- Before this can happen as we would want to be able to query the tokens that are created after the initial deployment
- This is applicable to all license tiers

Relevant Links

- https://github.com/xanzy/go-gitlab/blob/master/users.go#L838
- https://docs.gitlab.com/ee/api/personal_access_tokens.html
- https://docs.gitlab.com/ee/api/users.html#create-a-personal-access-token

**Comment by armsnyder** [comment]
This is not a great fit since there is only API support for creation but not read or deletion. There would be these scenarios:
1. The token expires in GitLab but the resource still exists
2. The resource is destroyed but the token still exists in GitLab

Would this proposed `personal_access_token` resource still be useful as a resource? Would it be useful as a datasource instead so it is not saved to state?

**Comment by Shocktrooper** [comment]
https://docs.gitlab.com/ee/api/personal_access_tokens.html

Is for read and deletion of the tokens. Combining this with the user create PAT call you have create, read and delete actions available.  Updates to PATs would just be a delete then create because you cannot modify tokens

**Comment by armsnyder** [comment]
That makes sense. I noticed that there's a note on the https://docs.gitlab.com/ee/api/personal_access_tokens.html that you can filter by your own user ID if you are non admin. Ideally a resource implementation of this would utilize that.

**Comment by Shocktrooper** [comment]
The resource shouldn't have to differ on the filter if it's their own user or another's, we can just pass back the GitLab error to the end user if they don't have permissions. For my use case I would be doing it for another account that is a service account while my account has admin so I would want to have the ability to pass in a different user id vs only use my own

**Comment by armsnyder** [comment]
You're right, it's most likely that the user being managed is not the same as the user running Terraform, so the filter would not help.

I think we want a standalone PAT resource and a warning in the doc page that it requires running the provider using an admin GitLab token.

**Comment by Shocktrooper** [comment]
Agreed and this should actually be pretty simple to implement as well and which is nice

**Comment by Shocktrooper** [comment]
@armsnyder I was working on this and is there a point to having an import on the resource? Seeing as you cannot get the PAT token value outside of creation.

**Comment by armsnyder** [comment]
Yes, sometimes users need to import resources in order to then destroy them, like if they lost their Terraform state somehow. We do this with other token resources as well.

**Comment by Shocktrooper** [comment]
Perfect ty!
