### ISSUE TITLE
Support option "Enable merged results pipelines" for projects

### ISSUE THREAD

**Issue by Skaronator** [gitlabhq/terraform-provider-gitlab#623]
I'd like to see support to set the following option via Terraform: "enable merged results pipelines"

Also the feature below, merge trains, would be great to configure from terraform.

![image](https://user-images.githubusercontent.com/2886913/117988639-e61c7880-b33b-11eb-8e63-7ea43b0df93f.png)

Settings -> General -> Merge request

### Affected Resource(s)
Please list the resources as a list, for example:
- gitlab_project

**Comment by armsnyder** [comment]
I'm not finding an API for controlling these settings unfortunately, in: https://docs.gitlab.com/ee/api/projects.html

GitLab issues for improving the API here:
* https://gitlab.com/gitlab-org/gitlab/-/issues/284100
* https://gitlab.com/gitlab-org/gitlab/-/issues/209224

**Comment by jtymes** [comment]
@armsnyder Both `merge_pipelines_enabled` and `merge_trains_enabled` appear to be in the API now. However, it looks like Merge Trains depend on having the Merge Request Pipelines enabled. I'd like to take a look at implementing these, but how would you handle that situation?

**Comment by timofurrer** [comment]
@jtymes usually we want to replicate the API and as much of the behavior as possible in the provider while still offering a sane user experience ... 

When using the API we can run the following:

```
curl -X PUT "http://localhost:8080/api/v4/projects/<project_id>" --header "PRIVATE-TOKEN: ACCTEST1234567890123" --header 'Content-Type: application/json' --data '{"merge_trains_enabled": true}'  
```

... which actually doesn't fail if `merge_pipelines_enabled` is disabled, but just silently ignores that.

I see multiple options:

1. we do the same in the provider and wouldn't implement any custom logic for these attributes, which may result in bad user experience
1. we automatically enabled `merge_pipelines_enabled` in case `merge_trains_enabled` is enabled. This could potentially shadow user mistakes (they didn't want `merge_pipelines_enabled` to be enabled 🤷 ), but may do what the user wants
1. error in case `merge_trains_enabled` is enabled, but `merge_pipelines_enabled` isn't, basically hardcoding API behavior insights in the provider.
1. ...

IMHO: it might be best to go with (1), but clearly document in the `merge_trains_enabled` field that it only takes affect if the `merge_pipelines_enabled` is being enabled, too. That way, if the API behavior changes towards auto-enabled `merge_pipelines_enabled`, the provider would just work ™️.

What do you think @armsnyder ?

**Comment by armsnyder** [comment]
@timofurrer Thanks for checking the API call 🏅 . I agree with your assessment. (No validation but copy documentation from upstream.)

**Comment by jtymes** [comment]
@timofurrer thank you for the in-depth answer. I will proceed with option 1.

**Comment by Skaronator** [comment]
Thanks! :heart:
