### ISSUE TITLE
 Error: Provider produced inconsistent final plan

### ISSUE THREAD

**Issue by gbormpilas** [gitlabhq/terraform-provider-gitlab#628]
Hi there,

We recentky started facing an issue with the gitlab provider, we would appreciate any help.

### Terraform Version
`0.15.3` 
gitlab provider version: `3.6.0` 
### Affected Resource(s)
gitlab_group_variable

### Terraform Configuration Files

```terraform
resource "gitlab_group_variable" "kube_config" {
  depends_on = [rke_cluster.cluster]
  group      = "38"
  key        = replace("RANCHER_KUBE_CONFIG_${var.rancher_cluster_name}", "-", "_")
  value      = base64encode(rke_cluster.cluster.kube_config_yaml)
  protected  = false

  provisioner "local-exec" {
    command = "echo \"${rke_cluster.cluster.kube_config_yaml}\" > ${replace("/tmp/kube_config_${var.rancher_cluster_name}", "-", "_")}"
  }
}
```

### Debug Output
https://gist.github.com/gbormpilas/52493aa90656a1391dd8523672dba7e8

### Expected Behavior
The gitlab group variable should have been updated.

### Actual Behavior
```terraform
Error: Provider produced inconsistent final plan
│ 
│ When expanding the plan for
│ module.managed-cluster.gitlab_group_variable.kube_config to include new
│ values learned so far during apply, provider
│ "registry.terraform.io/gitlabhq/gitlab" produced an invalid new value for
│ .value: inconsistent values for sensitive attribute.
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.
```

### Important Factoids
It started appearing after updating terraform from 0.13 to  0.15

**Comment by armsnyder** [comment]
So far I'm unable to reproduce the issue in a test setting.

My attempt: https://gist.github.com/armsnyder/94fa9d4c6b77ef885a58a3b6056f7541

**Comment by armsnyder** [comment]
Could you run this again with `TF_LOG=DEBUG` and upload a gist?

**Comment by timofurrer** [comment]
looks stale ... going to close this one. Don't hesitate to jump in and re-open if there is any value in it. Otherwise, please open a new one with a specific up-to-date request. Thanks 🍰
