### ISSUE TITLE
Data source user should support username

### ISSUE THREAD

**Issue by sudoapt-getclean** [gitlabhq/terraform-provider-gitlab#63]
In the source for the next release there is a data source for user this good
however it is based on using the email of the user to find the user. Currently the api for Gitlab.com does not support this for non-admin users. this makes this unusable for me (and probably other people)
[I have added a patch to also support searching for username.](https://github.com/terraform-providers/terraform-provider-gitlab/files/2321945/support_searching_for_e-mail_or_username.patch.zip)
I have two questions about this:

1. Should we support the use of email at all ( at the cost of not having a mandatory option)
2. What should take precedence if two are given. (currently I left this with email)

Please let me know what you think in the comments and give this a thumbs up if you like this feature.

(about the patch,.. I have tested it but not written tests, since i would like some guidance on what the actual functionality should be)

**Comment by armsnyder** [comment]
This was fixed via #61, as the datasource can be used to lookup by user_id, username, or email now, using a non-admin token. The only thing to be aware of is that email attribute is not filled in when using a non-admin token, but that's an intentional limitation in the API.
