### ISSUE TITLE
Add the ability to block a user

### ISSUE THREAD

**Issue by mpitt** [gitlabhq/terraform-provider-gitlab#631]
Hello, this is a feature request for adding an argument `is_blocked` (boolean, default `false`) to the `gitlab_user` resource. Thanks for your consideration.

**Comment by armsnyder** [comment]
API reference https://docs.gitlab.com/ee/api/users.html#block-user

Since the User field from the API is `"state": "blocked"` we should probably go with an optional+computed `"state"` attribute.
