### ISSUE TITLE
Plan fail

### ISSUE THREAD

**Issue by Djabx** [gitlabhq/terraform-provider-gitlab#635]
### Terraform Version

```
❯ terraform -v 
Terraform v1.0.0
on linux_amd64
+ provider registry.terraform.io/gitlabhq/gitlab v3.6.0
```

### Affected Resource(s)
Affected ressources:
- gitlab_branch_protection
- gitlab_group
- gitlab_group_variable
- gitlab_project
- gitlab_project_approval_rule
- gitlab_project_level_mr_approvals
- gitlab_project_variable
- gitlab_tag_protection
- gitlab_user

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### Debug Output

Output with `TF_LOG=trace`
https://gist.github.com/Djabx/d608d0310e1fe353296c5acd761bee44

### Expected Behavior
I should work :)

### Actual Behavior
It crash

### Steps to Reproduce

1. `terraform plan`

### Important Factoids

* Gitlab server is  13.12.2-ee
* the same plan worked 2 days ago, but the server have been updated since.

### References
?

**Comment by armsnyder** [comment]
@Djabx I'm getting a 404 from your gist

**Comment by timofurrer** [comment]
looks stale ... going to close this one. Don't hesitate to jump in and re-open if there is any value in it. Otherwise, please open a new one with a specific up-to-date request. Thanks 🍰
