### ISSUE TITLE
Feature Request: Allow adding users in branch_protection push_access_level

### ISSUE THREAD

**Issue by aldenAMS** [gitlabhq/terraform-provider-gitlab#639]
### Terraform Version
1

### Affected Resource(s)
gitlab_branch_protection

### Expected Behavior
I would like to be able to restrict pushing to certain branches to specific users as is possible through gitlab UI

### Actual Behavior
Push rules are restricted to 4 levels of access (not 5 as docs claim, gitlab rejects owner which this module accepts as valid)

**Comment by sirlatrom** [comment]
Please see if gitlabhq/terraform-provider-gitlab#556 brings the feature you're looking for.

**Comment by armsnyder** [comment]
This was released yesterday in v3.7.0. See https://registry.terraform.io/providers/gitlabhq/gitlab/latest/docs/resources/branch_protection

**Comment by aldenAMS** [comment]
Issue not resolved.

Using admin as described in documentation causes plan to fail with error:
```
│ Error: admin is an invalid value for argument push_access_level acceptable values are: [maintainer owner master no one guest reporter developer]
```

Using owner as described as valid value in terraform plan causes apply to fail with error:
```
Error: error protecting branch "master" on project "<project id>": POST https://gitlab.com/api/v4/projects/<project id>/protected_branches: 400 {error: push_access_level does not have a valid value}
```

**Comment by aldenAMS** [comment]
In addition the feature request to assign individual users, owner would just be a workaround my company finds acceptable.

**Comment by sirlatrom** [comment]
> Issue not resolved.
> 
> Using admin as described in documentation causes plan to fail with error:
> ```
> │ Error: admin is an invalid value for argument push_access_level acceptable values are: [maintainer owner master no one guest reporter developer]
> ```
> 
> Using owner as described as valid value in terraform plan causes apply to fail with error:
> ```
> Error: error protecting branch "master" on project "<project id>": POST https://gitlab.com/api/v4/projects/<project id>/protected_branches: 400 {error: push_access_level does not have a valid value}
> ```

It may be that only `developer`, ` maintainer` or `admin` are valid values in the API, so the validation function needs to be updated to reflect this is it's correct.
