### ISSUE TITLE
Allow adding groups in gitlab_branch_protection

### ISSUE THREAD

**Issue by Lena-nfb** [gitlabhq/terraform-provider-gitlab#641]
### Terraform Version

0.15.3

### Affected Resource(s)

gitlab_branch_protection

### Expected Behavior

I would like to be able to restrict allow to merge and allow to push to protected branches such as main/master to specific groups as is possible through gitlab UI.

### Actual Behavior

Push rules are restricted to 4 levels of access (not 5 as docs claim, gitlab rejects owner which this module accepts as valid).
According to the documentation "GitLab EE features to protect by group or user are not supported." [link](https://registry.terraform.io/providers/gitlabhq/gitlab/latest/docs/resources/branch_protection)

**Comment by sirlatrom** [comment]
Please see if #556 brings the feature you're looking for.

**Comment by armsnyder** [comment]
This was released yesterday in v3.7.0. See https://registry.terraform.io/providers/gitlabhq/gitlab/latest/docs/resources/branch_protection
