### ISSUE TITLE
gitlab_group resources returns returns 403 Forbidden

### ISSUE THREAD

**Issue by Lena-nfb** [gitlabhq/terraform-provider-gitlab#647]
Hi there,

I am trying to create a new group using the terraform provider and when I do `terraform apply` it returns a "403 Forbidden" error. I am passing the private_token of an administrator user to Gitlab. In the Web UI that user is able to create a new group without any problems.  I query the user through the provider and it seems doesn't have permission to create a group.
```
  {
      <username>                 = {
           can_create_group   = false
           can_create_project = false
           is_admin           = false
        }

 }
```

There's no option to update user's settings either from the UI or from the provider and if I want to create a new user using the `user` [resource](https://registry.terraform.io/providers/gitlabhq/gitlab/latest/docs/resources/user) I will have to be admin. 
It seems nobody in our team has admin permission in the API/terraform provider. 
I use the SaaS Gitlab.

### Terraform Version
0.15.3

### Affected Resource(s)
gitlab_group

### Debug Output
```
gitlab_group.maintainer: Creating...
╷
│ Error: POST https://gitlab.com/api/v4/groups: 403 {message: 403 Forbidden}
│ 
│   with gitlab_group.maintainer,
│   on maintainers.tf line 3, in resource "gitlab_group" "maintainer":
│    3: resource "gitlab_group" "maintainer" {
```

**Comment by ctoyan** [comment]
I also have a similar problem when trying to create a group.
I use a free SaaS account.
Does that mean that I can't use terraform with the free SaaS Gitlab?

**Comment by sluongng** [comment]
same issue here

**Comment by sluongng** [comment]
after a bit of investigation, if you have
`gitlab_rails['gitlab_default_can_create_group']` in your ommibus setting set to `false`, you will have to use an api token from the `root`(often admin) account user to create group without parent group.

On Gitlab cloud (gitlab.com), this option is set to false by default so that you wont be able to create root level group there.

See https://docs.gitlab.com/ee/administration/user_settings.html for more info

**Comment by timofurrer** [comment]
@armsnyder What do you think about this? Seems like we can't really do something about this from the provider side ...

**Comment by armsnyder** [comment]
We should improve our documentation with the findings in this issue.
