### ISSUE TITLE
gitlab_service_jira password not set

### ISSUE THREAD

**Issue by valvin1** [gitlabhq/terraform-provider-gitlab#672]
### Terraform Version
Terraform v0.14.5

### Affected Resource(s)
- gitlab_service_jira

### Terraform Configuration Files
```hcl
resource "gitlab_service_jira" "my_project" {
  project                  = gitlab_project.my_project.id
  url                      = "https://myjiraserver.tld"
  username                 = "user"
  password                 = var.jira_password
  project_key              = "XXXX"
  jira_issue_transition_id = "123"
  commit_events            = true
  merge_requests_events    = true
  comment_on_event_enabled = false
```

### Expected Behavior
this resource should configure the jira Integration password included

### Actual Behavior
it creates the jira integration except password which is not set and stays blank.

### Steps to Reproduce

1. add configuration of a gitlab_service_jira resources with a password
2. `terraform apply`
3. on gitlab side check the integration and test the connection. you should have a message with "password can't be blank"

**Comment by armsnyder** [comment]
Hello. Can you run your `apply` with `TF_LOG=DEBUG` and attach a gist with the debug logs? I looked at the code and it appears to be including the password in the API call correctly.

**Comment by Shocktrooper** [comment]
@ftpd I have experienced this but it appears that the password is validly set until you either go to the Integration page in GitLab for Jira or you click the test button on the integration.  I am unsure that this is a provider issue and might be more of a GitLab issue.  @ftpd or @valvin1 If you could run the provider, configure the JIRA integration and test that the integration on the project works without navigating to the JIRA integration configuration page that might confirm my suspicions.

**Comment by ftpd** [comment]
It doesn't work for me after just creating an integration. Clicking test button gives 'Validation failed', I have to manually insert password in the corresponding field in Jira itself.

**Comment by timofurrer** [comment]
@ftpd Could you please run the `terraform apply` with `TF_LOG=debug` to see the request made to GitLab - and please redact the output to not leak any secrets ;)

**Comment by ftpd** [comment]
@timofurrer the whole log from apply with debug is in my gist in https://github.com/gitlabhq/terraform-provider-gitlab/issues/672#issuecomment-1044168426

**Comment by timofurrer** [comment]
Just saw in the response that it's actually active 🤔

**Comment by ftpd** [comment]
https://registry.terraform.io/providers/gitlabhq/gitlab/latest/docs/resources/service_jira says the `active` field is read-only. For me it looks like it becomes active automagically when the integration is applied.

**Comment by ftpd** [comment]
I will try some manual approach with API calls and get back with response.

**Comment by timofurrer** [comment]
> Any advices welcomed, anyway.

I think it makes sense to open an issue here: https://gitlab.com/gitlab-org/gitlab/-/issues

@valvin1 any more information from your side?

**Comment by ftpd** [comment]
Just to make things clear: for me the password field is also blank, but I assume it's the expected look&feel - when creating the integration manually, (via the web) putting it there and clicking Save Changes, the field appears blank, despite the password is there and everything works.

**Comment by Shocktrooper** [comment]
@valvin1 bump for timofurrers comment above

**Comment by Shocktrooper** [comment]
Closing issue as no further feedback was added from end users
