### ISSUE TITLE
Feature Request: Allow adding users in branch_protection push_access_level

### ISSUE THREAD

**Issue by aldenAMS** [gitlabhq/terraform-provider-gitlab#675]
### Terraform Version
1

### Affected Resource(s)
gitlab_branch_protection

### Expected Behavior
I would like to be able to restrict pushing to certain branches to specific users as is possible through gitlab UI

### Actual Behavior
Push rules are restricted to 4 levels of access (not 5 as docs claim, gitlab rejects owner which this module accepts as valid) Docs specify admin instead of owner which will cause plan to fail.

Duplicate of https://github.com/gitlabhq/terraform-provider-gitlab/issues/639 which was closed by unrelated merge request

**Comment by armsnyder** [comment]
This is now supported in the latest version of the provider.

See docs: https://registry.terraform.io/providers/gitlabhq/gitlab/latest/docs/resources/branch_protection

Feel free to reply if there is still something missing, but for now I'm going to close the issue.
