### ISSUE TITLE
Feature Request: Add provider function to launch a trigger

### ISSUE THREAD

**Issue by fdavier** [gitlabhq/terraform-provider-gitlab#679]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
1

### Affected Resource(s)
gitlab_pipeline_trigger

### Terraform Configuration Files
New configuration needed

### Expected Behavior
We expect gitlab_pipeline_trigger_launch resource so that we can launch at time an existing trigger at project level

### Actual Behavior
gitlab_pipeline_trigger can only create trigger and there is some function to create a schedule.
But we don't have any function to launch trigger like an API call 

### Important Factoids
To be able to launch trigger at time with a new resource gitlab_pipeline_trigger_launch , we can assume that we need to sort id project. So we need so to have existing data source gitlab_project with a new attribute whih list triggers id. So we can use it to set gitlab_pipeline_trigger_launch resource

**Comment by armsnyder** [comment]
Firing one-time API calls doesn't really fit well into Terraform's declarative model of resources. That's more what a [provisioner](https://www.terraform.io/language/resources/provisioners/syntax) like [local-exec](https://www.terraform.io/language/resources/provisioners/local-exec) is for. Could you use that instead?

**Comment by teekhandekar** [comment]
@fdavier Can I work on this ?

**Comment by timofurrer** [comment]
@teekhandekar I agree with @armsnyder here. A "one time trigger" is more a thing for a provisioner / local-exec ... A resource wouldn't make any sense since there is no clear CRUD available here ..

Since this issue has been stale for over 2 months without any response from the author I'm going to close it. If there is more ideas or the situation changes somehow. Please let us know :)
