### ISSUE TITLE
[Feature Request] Add Gitlab group webhook management

### ISSUE THREAD

**Issue by williamsbdev** [gitlabhq/terraform-provider-gitlab#680]
Affected Resource(s)

- `gitlab_group_hook`

The provider currently supports `gitlab_project_hook` and other `gitlab_group_*` resources but there is no support yet for hooks at the group level.

https://docs.gitlab.com/ee/api/groups.html#add-group-hook

We'd like to request this resource in the Terraform provider so that we can manage our group webhooks with Terraform.

On another note, is there a roadmap of the features being worked/developed for this provider?

**Comment by jtymes** [comment]
@timofurrer I'm going to take a look at implementing this. I'll do an upstream alignment on fields in go-gitlab first. It looks like there may need to be some modifications to GitLab's API exposure as well to reach parity with the UI options, but I think that can come later.

**Comment by jtymes** [comment]
go-gitlab API alignment https://github.com/xanzy/go-gitlab/pull/1427

**Comment by timofurrer** [comment]
@jtymes sounds great!

> It looks like there may need to be some modifications to GitLab's API exposure as well to reach parity with the UI options, but I think that can come later.

Can you elaborate on that? Maybe I can quickly add what's missing ...

**Comment by jtymes** [comment]
The UI has "Feature flag events", and "Member events" but the API does not.
<img width="266" alt="image" src="https://user-images.githubusercontent.com/973915/159680184-b3a0157a-3eaf-4c44-a4ff-d80944ff8e92.png">
<img width="370" alt="image" src="https://user-images.githubusercontent.com/973915/159681083-122de58e-e2c1-4a69-a12f-1eef70966384.png">


[hook.rb](https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/api/entities/hook.rb)
[group_hook.rb](https://gitlab.com/gitlab-org/gitlab/-/blob/master/ee/lib/ee/api/entities/group_hook.rb)
[triggerable_hooks.rb](https://gitlab.com/gitlab-org/gitlab/-/blob/master/app/models/concerns/triggerable_hooks.rb)

Also, the API is returning what appears to be a system-level hook `repository_update_events` that cannot be changed from the group hook endpoint. Not sure if it should even be exposed in that endpoint.

**Comment by teekhandekar** [comment]
@williamsbdev Can I work on this ?

**Comment by timofurrer** [comment]
Correct me if I'm wrong, but I think @jtymes already start working on this :)

**Comment by jtymes** [comment]
Yep, I'm already working on it. Just waiting on the upstream PR in go-gitlab.

**Comment by bgadberry-gitlab** [comment]
220 seat, Ultimate customer requesting this feature: https://gitlab.my.salesforce.com/0016100001aJso6

Customer's integration with Sumo Logic requires adding a webhook for each GitLab group. 

/cc @nagyv

**Comment by timofurrer** [comment]
@bgadberry-gitlab @nagyv I'll take care of this and if all goes well it'll be available in the next provider release shortly after 15.3 has been released ;)
