### ISSUE TITLE
Feature request: resource to create files

### ISSUE THREAD

**Issue by spothound** [gitlabhq/terraform-provider-gitlab#688]
Hi there,

I am using the terraform provider 3.7.0 and I cannot find a way to create a project with certain files inside.

I would like to ask if there is a way to do this with the Terraform module and, it is not possible, make a feature request for this.

I know that there are [API calls to create files](https://docs.gitlab.com/ee/api/repository_files.html#create-new-file-in-repository) so that should be possible with Terraform as well.

Best regards.

**Comment by duyleekun** [comment]
The team removed that feature due to lacking testing
 https://github.com/gitlabhq/terraform-provider-gitlab/pull/650

**Comment by spothound** [comment]
Thanks, I will check it!

**Comment by djtecha** [comment]
This is a bummer as it would be useful to incorporate for FLUX

**Comment by timofurrer** [comment]
We've lately merged #724 which provides this in the `gitlab_repository_files` resource 🎉
