### ISSUE TITLE
Not refreshing state for manually removed group cluster, 404 thrown instead

### ISSUE THREAD

**Issue by qayshp** [gitlabhq/terraform-provider-gitlab#691]
### Terraform Version
```
gitlabhq/gitlab ">= 3.7.0"
terraform ">= 1.0.3"
```

### Affected Resource(s)
- `gitlab_group_cluster`
- possibly others

### Terraform Configuration Files
I don't think this is necessary, but, can write a new CI stage to output this if needed.

### Debug Output
Pasting here instead of gist since the relevant parts are two lines:
```
gitlab_group_cluster.eks-cluster: Refreshing state... [id=123:456]
│ Error: GET https://gitlab-ce.example.com/api/v4/groups/123/clusters/456: 404 {message: 404 Not found}
```

### Panic Output
No panic.

### Expected Behavior
TF plan to work as expected and notice that the group cluster is gone, so it needs to add a new one.

### Actual Behavior
`Error: GET https://gitlab.ims.io/api/v4/groups/5053/clusters/47: 404 {message: 404 Not found}`

### Steps to Reproduce
1. Write a (valid) `gitlab_group_cluster` resource in TF
2. `terraform apply`
3. Remove the cluster from the Group Cluster UI in GitLab
4. `terraform plan`

### Important Factoids
Running completely inside GitLab CI with the Terraform.Latest template as recommended way to add cluster to GitLab.

### References
Possibly https://github.com/gitlabhq/terraform-provider-gitlab/issues/635 but the OP's gist links are broken and they don't seem to have really specified much information.

**Comment by armsnyder** [comment]
This was resolved in #318 and will be in the next release. Stay tuned!
