### ISSUE TITLE
group_ids in gitlab_project_approval_rule has no effect

### ISSUE THREAD

**Issue by balihb** [gitlabhq/terraform-provider-gitlab#694]
### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.

### Affected Resource(s)
- gitlab_project_approval_rule

### Terraform Configuration Files
```hcl
resource "gitlab_project_approval_rule" "default" {
  project              = data.gitlab_project.this.id
  protected_branch_ids = [gitlab_branch_protection.default.branch_protection_id]
  name                 = "default branch"
  approvals_required   = var.default_branch_approvals_required
  group_ids            = [for k, v in data.gitlab_group.default_branch_approval : v.id]
}
```

### Debug Output
https://gist.github.com/balihb/148fea1e5e070d53e28406e1f304cf5d

### Expected Behavior
Set groups in `gitlab_project_approval_rule`

### Actual Behavior
Terraform reports success, but groups are not appearing in the UI, neither in the API response.

### Steps to Reproduce
1. `terraform apply`

**Comment by balihb** [comment]
after removing the groups from the config:
https://gist.github.com/balihb/3b4300d0cb8f52ce34c6f7a630e84237

**Comment by comtef** [comment]
Hello @balihb 
Are the groups you re using also members of the projects?
I had the same kind of issue when adding people. If you forget to add them as members, the API call and terraform plan is ok but users are not added as approvers.

**Comment by timofurrer** [comment]
@balihb could you make it work by sharing the project with the group as suggested by @comtef ?

> If you forget to add them as members, the API call and terraform plan is ok but users are not added as approvers.

Silently ignoring this seems to be the behavior from the upstream GitLab API in this case. In case of a non 200 status code, the provider would error.

**Comment by timofurrer** [comment]
I'm going to close this for now since the provider behavior seems to be correct - as in propagating the API behavior. 

@balihb in case what @comtef doesn't solve your issue - please don't hesitate to ping me here and I'll re-open and help to figure out what's going on 🎉
