### ISSUE TITLE
No changes detected in gitlab_project.approvals_before_merge 

### ISSUE THREAD

**Issue by nderraugh** [gitlabhq/terraform-provider-gitlab#696]
### Terraform Version
Terraform v1.0.4
on darwin_amd64

### Affected Resource
- gitlab_project

### Terraform Configuration Files
```hcl
terraform {
  required_providers {
    gitlab = {
      source  = "gitlabhq/gitlab"
      version = "3.7.0"
    }
  }
}
data "gitlab_group" "somegroup" {
  full_path = "somegroup"
}
resource "gitlab_project" "project" {
  name                                             = "some name"
  namespace_id                                     = gitlab_group.somegroup.id
  approvals_before_merge                           = 2
  merge_method                                     = "ff"
  description                                      = "description"
  remove_source_branch_after_merge                 = true
  only_allow_merge_if_all_discussions_are_resolved = true
  only_allow_merge_if_pipeline_succeeds            = true
}
```

### Expected Behavior
The provider should detect the difference between the number of approvals configured in TF and Gitlab.  Running `terraform plan` should show the changes made outside of TF and indicate that applying the current changes will overwrite those changes.

### Actual Behavior
The provider does not detect any difference between TF and the configuerd Gitlab project.

### Steps to reroduce
Configure the code above for a test repository.  Change the Gitlab project config to a single approval required before merge, e.g. project > Settings > General > Merge request (MR) approvals > Any eligible User > 2 -> 1 and re-run `terraform plan`.

**Comment by PatrickRice-KSC** [comment]
https://gitlab.com/groups/gitlab-org/-/epics/7572 is the epic for removing the `approvals_before_merge`, which looks based on conversations like it's now slated to be removed in 15.0

**Comment by timofurrer** [comment]
Let's have a look for our next release 👍

**Comment by timofurrer** [comment]
Unfortunately, this field still exists after 15.0 and I have the feeling it's not gonna be removed before 16.0 at least.

I don't see any feasible solution from the provider side and therefore I've created https://github.com/gitlabhq/terraform-provider-gitlab/pull/1161 which just adds a note for the `approvals_before_merge` field. 

@PatrickRice-KSC WDYT?

**Comment by PatrickRice-KSC** [comment]
@timofurrer  - I feel like this might be an area where it's a good idea for us to actually just _remove_ the field in the TF provider in favor of using the [`project_approval_rule`](https://registry.terraform.io/providers/gitlabhq/gitlab/latest/docs/resources/project_approval_rule) resource. While that diverges from the upstream API, it seems like this is an action that effectively protects users from themselves. The field has been deprecated since 12.0 based on some of the conversions on GitLab, so it's well outside our discussed support cycle.

**Comment by timofurrer** [comment]
@PatrickRice-KSC are you sure it's really deprecated already? It doesn't say so in the docs neither could I find a reference in the deprecations / removal [notifications](https://gitlab.com/gitlab-org/gitlab/-/tree/master/data).

**Comment by PatrickRice-KSC** [comment]
@timofurrer  - Well, that's... interesting. It's explicitly listed as deprecated in the [epic link](https://gitlab.com/groups/gitlab-org/-/epics/7572) I'd posted above, but reading the individual steps more closely seems to indicate that they're just starting the process. If you click into [one of the issues mentioned](https://gitlab.com/gitlab-org/gitlab/-/issues/352181) the conversation mentions that the [API documentation says it was deprecated in 12.0](https://docs.gitlab.com/ee/api/merge_request_approvals.html#change-configuration) but it's not widely consistent.

I agree with you that it's likely this will be removed in 16.0 (middle of 2023 based on trends) though, just given the activity on it which is to say - not that much activity.

**Comment by PatrickRice-KSC** [comment]
Merged the PR (which closes the issue) - I'll open a new issue if we want to make a subsequent change and remove the field (which would necessitate a 4.0 on our side anyway since that's a breaking change).
