### ISSUE TITLE
read_package_registry scope (among others) not supported on gitlab_deploy_token resource

### ISSUE THREAD

**Issue by flyte** [gitlabhq/terraform-provider-gitlab#698]
### Terraform Version
```
Terraform v0.14.6
+ provider registry.terraform.io/gitlabhq/gitlab v3.7.0
```

### Affected Resource(s)

- gitlab_deploy_token

### Terraform Configuration Files
```hcl
resource "gitlab_deploy_token" "protocols" {
    project = gitlab_project.project.id
    name = "Registry access"
    username = "protocols-registry-access"
    scopes = ["read_package_registry"]
}
```

### Expected Behavior
Deploy token is created/updated with the `read_package_registry` scope.

### Actual Behavior
```
Error: expected scopes.0 to be one of [read_registry read_repository], got read_package_registry

  on gitlab.tf line 33, in resource "gitlab_deploy_token" "protocols":
  33: resource "gitlab_deploy_token" "protocols" {
```

### Important Factoids
This provider only [supports](https://github.com/gitlabhq/terraform-provider-gitlab/blob/master/gitlab/resource_gitlab_deploy_token.go#L59) scopes:
```
read_repository
read_registry
```

whereas the GitLab API [supports](https://docs.gitlab.com/ee/api/deploy_tokens.html#create-a-project-deploy-token) scopes:

```
read_repository
read_registry
write_registry
read_package_registry
write_package_registry
```

**Comment by armsnyder** [comment]
Duplicates #704 

Marking as duplicate because there is more discussion on that issue.
