### ISSUE TITLE
Importing private gitlab repository  -  The requested URL returned error: 301

### ISSUE THREAD

**Issue by jimsmith** [gitlabhq/terraform-provider-gitlab#701]
### Terraform Version
```
Terraform v1.0.3
on darwin_amd64
+ provider registry.terraform.io/gitlabhq/gitlab v3.7.0
```

### Affected Resource(s)
`gitlab_project`

### Terraform Configuration Files
```hcl
resource "gitlab_project" "project" {
  name             = var.project_name
  namespace_id     = var.namespace_id
  description      = var.project_description
  visibility_level = var.project_visibility
  default_branch   = "main"
  # approvals_before_merge = true
  only_allow_merge_if_pipeline_succeeds = true
  import_url                            = "https://gitlab.com/<REMOVED>/gitlab-repo-bootstrap"

  # https://gitlab.com/help/push_rules/push_rules
  push_rules {
    commit_committer_check = true
    member_check           = true
    prevent_secrets        = var.prevent_secrets
  }

  tags = setunion(local.tags, compact(var.tags))

  lifecycle {
    prevent_destroy = false
  }
}

```

### Expected Behavior
What should have happened?

Repo successfully created with import url contents

### Actual Behavior

New repository is created then the following occurs from terraform

```
module.aws-vpn-client.gitlab_project.project: Creating...
╷
│ Error: error while waiting for project "aws-vpn-client" import to finish: unexpected state 'failed', wanted target 'finished'. last error: %!s(<nil>)
│ 
│   with module.aws-vpn-client.gitlab_project.project,
│   on modules/gitlab/main.tf line 19, in resource "gitlab_project" "project":
│   19: resource "gitlab_project" "project" {


From newly created blank repo:

```
- No repository
- The repository for this project does not exist.
- This means you can not push code until you create an empty repository or import existing one.
- The repository that is being  imported, is a private one and in a group that doesn't allow public repos.
So gitlab looks for username/password to be entered.
```
  The repository could not be imported.
  Error importing repository https://gitlab.com/REMOVED/gitlab-repo-bootstrap into REMOVED/aws-vpn-client - 13:CreateRepositoryFromURL: clone cmd wait: fatal: unable to access [FILTERED] The requested URL returned error: 301
  : exit status 128.
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform init`
2. `terraform validate`
3. `terraform plan`
4. `terraform apply`

Plan generates tf plan no errors encountered, error occurs whilst at apply 

![image](https://user-images.githubusercontent.com/2676701/130250499-74039624-670e-4994-b72e-419269a4e20b.png)

**Comment by ohasangit** [comment]
Not sure if there's a workaround for inputting the username and password for import to work (they are required even though they say optional).

Otherwise we need some way of inputting a username and password in the provider or resource definition.

**Comment by armsnyder** [comment]
@ohasangit The [Create Project API docs](https://docs.gitlab.com/ee/api/projects.html#create-project) only have a single field `import_url`, which is what we expose in the Terraform resource. I didn't see any fields for username or password. Have you tried adding the username and password to the `import_url` value as basic auth information? (https://username:password@example.com/)

**Comment by QuingKhaos** [comment]
@ohasangit You need to use `https://username@password-or-access-token:gitlab.com/<REMOVED>/gitlab-repo-bootstrap` as import URL. The GitLab UI may have separate fields to input username/password but via the API and thus the Terraform provider you have to supply the basic auth credentials direclty in the URL.

**Comment by timofurrer** [comment]
I'm going to close this for now. @jimsmith, if you are still having problems even when including username / password in the URL as suggested, please respond here again and we'll re-open 🎉

**Comment by jimsmith** [comment]
@timofurrer No reopen this as you haven't resolved it, why would you close it really 🤔?

**Comment by timofurrer** [comment]
I've closed it because there wasn't any response and a lot of folks just drop a report and never come back :)

Sorry, for the assumption and cool that you've responded so quickly 👍

**Comment by jimsmith** [comment]
I actively watch this, nothing has been actioned for this, its been reported as not working. The terraform resource has no way to pass credentials.

Folk shouldn't be closing when it's been reported 🤨🤷‍♂️

https://registry.terraform.io/providers/gitlabhq/gitlab/latest/docs/resources/project

**Comment by timofurrer** [comment]
> Where do you suggest the credentials go in the terraform resource ?

From your example I'd try this:

```hcl
locals {
    username = "..."
    password = "..."
}

resource "gitlab_project" "project" {
  name             = var.project_name
  namespace_id     = var.namespace_id
  description      = var.project_description
  visibility_level = var.project_visibility
  default_branch   = "main"
  # approvals_before_merge = true
  only_allow_merge_if_pipeline_succeeds = true
  import_url                            = "https://${local.username}:${local.password}@gitlab.com/<REMOVED>/gitlab-repo-bootstrap"

  # https://gitlab.com/help/push_rules/push_rules
  push_rules {
    commit_committer_check = true
    member_check           = true
    prevent_secrets        = var.prevent_secrets
  }

  tags = setunion(local.tags, compact(var.tags))

  lifecycle {
    prevent_destroy = false
  }
}
```

The `username` and `password` should (IMHO) be given as `variable`s and the `password` marked as `senstive` :)

**Comment by QuingKhaos** [comment]
Oh yeah, didn't recognized the 301 as a redirect, that's the first weird error. And it should be `https://username@password-or-access-token:gitlab.com/<REMOVED>/gitlab-repo-bootstrap.git`, mind the `.git` at the and of the URL. This could also be the culprit of the redirect. Always use the HTTPS Git URL, not the web URL.

@timofurrer btw, you can use the `sensitive()` function to mark locals or anything else and thus the derived `import_url` as sensitive. Of course the password/token should come from a variable normally

```hcl
locals {
    username = "..."
    password = sensitive("...")
}
```

@jimsmith Basically the issue was closed, as this isn't an issue with the provider at the first glance, it's an usage error :)

The terraform provider as a form of passing credentials as basic auth directly in the URL. As explained above, the GitLab API itself requires that to do so. A terraform provider is as close as possible to the API, so always check the API docs first: https://docs.gitlab.com/ee/api/projects.html#configure-pull-mirroring-for-a-project

**Comment by jimsmith** [comment]
Thanks, shouldn't the docs be updated to catch this issue for passing in credentials 👍🏻

**Comment by timofurrer** [comment]
@QuingKhaos 

>btw, you can use the sensitive() function to mark locals or anything else and thus the derived import_url as sensitive. Of course the password/token should come from a variable normally

Yes, I'm aware 🎉 I'm just usually suggesting it so that people don't get the impression that it's a "best practice" to store secrets in code :) Sometimes, this can be very useful and is even okay :)

Yes, indeed - we try to keep the terraform attributes aligned with the GitLab upstream API and also the documentation. I think it's generally good to rather improve the upstream docs (e.g. here regarding URL format etc) and then link from the provider to the API docs :)

I'm on vacation right now, but if any of you want to elaborate the docs in the provider, feel free to submit a PR :)

**Comment by timofurrer** [comment]
... Now, I hope that we sorted this out and as I've said: happy to review PRs improving the docs 🎉 ... or you could even submit a MR / issue in [Gitlab upstream](https://gitlab.com/gitlab-org/gitlab/-/issues).

**Comment by timofurrer** [comment]
> But it couldn't hurt to link to this API docs paragraph,

I actually have a local changes and consistently link from the provider docs to upstream docs, which should also improve the situation a little bit - at least for the cases in which the upstream doc is complete :)
