### ISSUE TITLE
Allow full set of scopes for deploy tokens

### ISSUE THREAD

**Issue by Nintorac** [gitlabhq/terraform-provider-gitlab#704]
Currently only `read_registry` and `read_repository` scopes can be applied for deploy tokens created via terraform but in the gitlab console I can make deploy tokens with those scopes as well as `write_repository`, `write_registry`, `read_package_registry`, `write_package_registry`.

### Terraform Version

Terraform v1.0.4
on linux_amd64
+ provider registry.terraform.io/gitlabhq/gitlab v3.7.0

**Comment by jindrichskupa** [comment]
PR is prepared here: https://github.com/gitlabhq/terraform-provider-gitlab/pull/695

**Comment by emeusel-evs** [comment]
Oh I would so much second this, please pull that PR. Especially due to the fact that it is just a straight forward change to reflect the full API functionality.

**Comment by rolljee** [comment]
This is awesome, i am currently looking for this too :+1: any idea when this will be available ?

**Comment by johannges** [comment]
i just opened a pr #769 for this issue, because the pr #695 has not been updated for a while.

**Comment by armsnyder** [comment]
closed via #769

**Comment by Nintorac** [comment]
Thanks all ☺️
