### ISSUE TITLE
[Feature Request] setting remove_source_branch_after_merge, build_timeout

### ISSUE THREAD

**Issue by peay** [gitlabhq/terraform-provider-gitlab#708]
- The `gitlab_project` resource exposes `remove_source_branch_after_merge` as an attribute only. It would be useful to expose it as an argument instead, so that the value can be properly Terraformed.

  The value is already part of the [Edit project API](https://docs.gitlab.com/ee/api/projects.html#edit-project), and available in `go-gitlab`.

- The `build_timeout` property from `go-gitlab` is not exposed at all by the `gitlab_project`, whether as an attribute or an argument. Exposing it would be useful as well.

These are similar to https://github.com/gitlabhq/terraform-provider-gitlab/issues/292. Those two issues might be tackled together.

**Comment by peay** [comment]
After trying it out, it seems `remove_source_branch_after_merge` can be set as an argument - [the documentation is incorrect for some reason](https://registry.terraform.io/providers/gitlabhq/gitlab/latest/docs/resources/project), but the argument works.

`build_timeout` remains to be added.

**Comment by timofurrer** [comment]
This has been implemented with #917 and will be released in the next release :)
