### ISSUE TITLE
[Feature Request] Add support for allow_force_push on branch protection

### ISSUE THREAD

**Issue by BlackDex** [gitlabhq/terraform-provider-gitlab#709]
`gitlab_branch_protection` does not support setting `allow_force_push` right now, which causes issues when used to create a mirror from an other repo like a remote github or gitlab for example.

This wasn't an issue before we updated our local environment to gitlab 14.x since that feature wasn't there.

**Comment by beekeep** [comment]
I can take a look at adding this.

**Comment by BlackDex** [comment]
Thx!!
