### ISSUE TITLE
Initialize With README variable is ignored

### ISSUE THREAD

**Issue by SachinMeier** [gitlabhq/terraform-provider-gitlab#712]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version

Terraform v1.0.3
on darwin_amd64
+ provider registry.terraform.io/gitlabhq/gitlab v3.7.0

### Affected Resource(s)
 - `gitlab_project`

### Terraform Configuration Files
```hcl
resource "gitlab_project" "regular_repository" {
      + approvals_before_merge                           = 0
      + archived                                         = false
      + container_registry_enabled                       = false
      + default_branch                                   = "master"
      + description                                      = "Testing Terraform Apply"
      + http_url_to_repo                                 = (known after apply)
      + id                                               = (known after apply)
      + initialize_with_readme                           = false
      + issues_enabled                                   = true
      + lfs_enabled                                      = false
      + merge_method                                     = "merge"
      + merge_requests_enabled                           = true
      + mirror                                           = false
      + mirror_overwrites_diverged_branches              = false
      + mirror_trigger_builds                            = false
      + name                                             = "test-repo"
      + namespace_id                                     = (known after apply)
      + only_allow_merge_if_all_discussions_are_resolved = false
      + only_allow_merge_if_pipeline_succeeds            = false
      + only_mirror_protected_branches                   = false
      + packages_enabled                                 = false
      + pages_access_level                               = "private"
      + path                                             = "test-repo"
      + path_with_namespace                              = (known after apply)
      + pipelines_enabled                                = true
      + remove_source_branch_after_merge                 = true
      + request_access_enabled                           = true
      + runners_token                                    = (sensitive value)
      + shared_runners_enabled                           = true
      + snippets_enabled                                 = true
      + ssh_url_to_repo                                  = (known after apply)
      + tags                                             = [
          + "managed_by_terraform",
          + "test-repo",
        ]
      + visibility_level                                 = "private"
      + web_url                                          = (known after apply)
      + wiki_enabled                                     = true

      + push_rules {
          + commit_committer_check  = true
          + deny_delete_tag         = false
          + member_check            = true
          + prevent_secrets         = true
          + reject_unsigned_commits = true
        }
    }
```

### Expected Behavior

Above is a standard `gitlab_project` resource being created. I copied the `terraform plan` directly from output, and as you notice, `initialize_with_readme = false`. Thus, i would expect the created repository to have no README.md file.

### Actual Behavior
However, when I ran `terraform apply`, the Repo was initalized with a README.md file.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Create a `gitlab_project` with `initialize_with_readme = false`.
2. Run `terraform plan` to confirm.
3. Run `terraform apply` to apply.
4. See repo. 

### Important Factoids

I did not create a `gitlab_protected_branch`.

**Comment by gpr** [comment]
I have the same issue with Gitlab 14.4

**Comment by timofurrer** [comment]
@armsnyder Do you have any insides on this? I failed to reproduce it :S

**Comment by armsnyder** [comment]
The whole project-initialization story is tricky because of the need to make sense of resources created upstream in GitLab, especially when initializing with a readme, which creates a branch and often a branch protection.

I would say if you can't reproduce this we should close it. We can always re-open if we see more evidence of the issue that helps us address a root cause.

As we get into addressing #749 and by extension #792, the resource will probably need some more tests to cover the extensive changes that affect this whole initialization story.

**Comment by armsnyder** [comment]
One last note is that we did have this same bug in the past #309 and was fixed, likely by #583.

**Comment by timofurrer** [comment]
I'm going to close this for now. Let's create a new one if it appears again in the latest release.

**Comment by gthieleb** [comment]
I just started using the gitlab provider and realized the README is created but the content of the description is not inside. 
This is the default behavior if creating a new project via the Gitlab UI. 
Is it worth open a ticket?

**Comment by timofurrer** [comment]
Yes, please open another ticket with something that helps us reproduce your issue. That would be great :tada:
