### ISSUE TITLE
[Feature Request] Add ability to push files

### ISSUE THREAD

**Issue by drew-viles** [gitlabhq/terraform-provider-gitlab#720]
Hi!

I could be missing something really obvious here but I can't see any way to push files using the Terraform provider.

I'm trying to setup Flux2 using Terraform [as per this guide](https://registry.terraform.io/providers/fluxcd/flux/latest/docs/guides/github).

Flux also [supports gitlab](https://fluxcd.io/docs/cmd/flux_bootstrap_gitlab/) for bootstrapping.

However at the point in their example where they push the install/sync and Kustomize files to Github using the following resource(s) below, I'm getting stuck as the Gitlab provider doesn't seem to support the ability to push things to git via the provider.

```
resource "github_repository_file" "install" {
  repository = github_repository.main.name
  file       = data.flux_install.main.path
  content    = data.flux_install.main.content
  branch     = var.branch
}

resource "github_repository_file" "sync" {
  repository = github_repository.main.name
  file       = data.flux_sync.main.path
  content    = data.flux_sync.main.content
  branch     = var.branch
}

resource "github_repository_file" "kustomize" {
  repository = github_repository.main.name
  file       = data.flux_sync.main.kustomize_path
  content    = data.flux_sync.main.kustomize_content
  branch     = var.branch
}
```

Does the Gitlab provider have anything like this to allow us to push files to Gitlab?

If so, I cannot see how - could this be made clearer?

If not, could this be added so that we can push files into a project?

**Comment by errnothxbye** [comment]
Exactly the same predicament as above. Currently, there is no capability in the GitLab's TF provider to create files within a repo as the GitHub TF provider does.

Would be great if this capability is added to the provider.

**Comment by fcervantes2** [comment]
This is definitely a blocker for us as well, for the same reason. Would make the process of onboarding a new cluster and/or other TF resources using GitOps on GitLab.

**Comment by mkjmdski** [comment]
There is a pull request for that: https://github.com/gitlabhq/terraform-provider-gitlab/pull/350 but it looks like it's not developed anymore...

**Comment by mkjmdski** [comment]
btw this duplicates https://github.com/gitlabhq/terraform-provider-gitlab/issues/688
