### ISSUE TITLE
Support integrations on `gitlab_group_cluster` and `gitlab_project_cluster`

### ISSUE THREAD

**Issue by Kaelten** [gitlabhq/terraform-provider-gitlab#727]
As best I can tell, the cluster configurations do not support enabling the prometheus or elastic search integrations.   It'd be very nice if those could be flagged as part of the provider.

**Comment by armsnyder** [comment]
I don't see fields for these settings in the API docs. They would be documented here, right? https://docs.gitlab.com/ee/api/project_clusters.html
