### ISSUE TITLE
Protected Branches on Project Import

### ISSUE THREAD

**Issue by briananderson1222** [gitlabhq/terraform-provider-gitlab#729]
I would like to understand why this logic exists. https://github.com/gitlabhq/terraform-provider-gitlab/blob/master/gitlab/resource_gitlab_project.go#L519-L531

I understand that I can specify a different default branch than the project I am importing and I like that some of this logic handles updating the new project to use the correct default_branch but I do not understand why assumptions are made about branch protection rules and why those assumptions cause hard errors. I want to be able to define a project and setup my own branch protection rules but this logic ends up either 
1) Causing a failure if there is no branch protection rule on the template project because it fails trying to remove something that is non-existent OR
2) Defines a generic branch protection rule on my new default branch that I can then not control at all with my own branch protection resource

... It seems like this logic assumes that the Group settings for branch protection are always set to "Fully Protected" which is not the case. I know there are other similar-ish issues open related to adding support for controlling the group level settings but this logic seems to be specific to project imports from what I understand..

Can someone shed some light on why this logic is here and if there is an alternative way I could define my own branch protection rules on a project that uses a template or imported project.. Seems like it should either take the group default branch protection rules into account if it wants to create the rule AND not cause a hard failure when trying to remove the old branch protection rule (in case it doesn't exist).

**Comment by armsnyder** [comment]
This logic was originally added while fixing an issue where the `default_branch` attribute was not being respected, in #583. Unfortunately it has caused other issues like the one you're describing.

**Comment by armsnyder** [comment]
Let's fold the discussion into #759.
