### ISSUE TITLE
403 error when creating gitlab_project from instance template

### ISSUE THREAD

**Issue by whoracle** [gitlabhq/terraform-provider-gitlab#737]
### Terraform Version
1.0.7

### Affected Resource(s)
Please list the resources as a list, for example:
- gitlab_project

### Terraform Configuration Files
```hcl
resource "gitlab_project" "project" {
  name                   = "test"
  namespace_id           = 1
  description            = "test project"
  archived               = false
  initialize_with_readme = false
  default_branch         = "master"

  remove_source_branch_after_merge                 = true
  packages_enabled                                 = false
  lfs_enabled                                      = false
  wiki_enabled                                     = false
  snippets_enabled                                 = false
  pipelines_enabled                                = true
  container_registry_enabled                       = true
  issues_enabled                                   = true
  visibility_level                                 = "internal"
  only_allow_merge_if_all_discussions_are_resolved = false
  only_allow_merge_if_pipeline_succeeds            = true
  import_url                                       = ""
  mirror                                           = false
  mirror_overwrites_diverged_branches              = false
  mirror_trigger_builds                            = false
  only_mirror_protected_branches                   = false
  pages_access_level                               = "disabled"
  merge_method                                     = "ff"
  shared_runners_enabled                           = true
  use_custom_template                              = true
  template_name                                    = "terraform"
}
```

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

https://gist.github.com/whoracle/d9ad4cae5f3e45808995dd0a88653e2c

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
Project should be created from custom instance template.

### Actual Behavior
project gets correctly created from custom instance template (according to GUI), but terraform receives a 403 on https://APIURL/api/v4/projects/:id/import and then considers the resource tainted and endlessly recreates the project on each successive run.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
None

### References
None

**Comment by WarpRat** [comment]
We're seeing the exact same thing. The import API endpoint that the provider is trying to use returns a 403 when called outside terraform as well with any token I've tried. The import status field appears to be available in the `https://APIURL/api/v4/projects/:id` endpoint as "import_status" - that may be a viable work around if the import API endpoint is broken.

**Comment by SeriousSemantics** [comment]
`403 Forbidden` errors may be returned if you have disabled the 'GitLab export' import source. [Relevant GitLab issue here.](https://gitlab.com/gitlab-org/gitlab/-/issues/349082) 

Can you try running again after enabling that source in `Admin Area > Settings > General > Visibility and access controls > Import Sources`

**Comment by whoracle** [comment]
Sorry for the late reply. Enabling the import source in fact fixes this behaviour.
