### ISSUE TITLE
Missing configuration "Enable delayed project deletion"

### ISSUE THREAD

**Issue by thuck** [gitlabhq/terraform-provider-gitlab#738]
Hi;

I was trying to enable the "Enable delayed project deletion", and looks like this is not part of the current `gitlab_group` resource.
Also looks like this is not part of gitlab api, at least I couldn't find in the current documentation,

Best Regards

**Comment by armsnyder** [comment]
Thanks for the issue. I couldn't find this in the API docs, and I didn't see any open issues on gitlab.com for adding this API option. You could open an issue there, and we can re-open this once it's available.

GitLab issues: https://gitlab.com/gitlab-org/gitlab/-/issues
