### ISSUE TITLE
Release request

### ISSUE THREAD

**Issue by dhrapson** [gitlabhq/terraform-provider-gitlab#739]
Hi, Are you planning a v3.8.0 release?
We'd really like to use the gitlab_project.squash_option feature on master
Thanks

**Comment by roidelapluie** [comment]
Hello, yes, it makes sense before we merge the SDK v2 API.

cc @nicholasklick

**Comment by timofurrer** [comment]
Release [v3.8.0](https://github.com/gitlabhq/terraform-provider-gitlab/releases/tag/v3.8.0) has been out for some time. I'm going to close this :)
