### ISSUE TITLE
Users and Group configuration

### ISSUE THREAD

**Issue by jjasghar** [gitlabhq/terraform-provider-gitlab#74]
Hi!

I wasn't sure where to ask this so I'm posting here. I apologize if this is noise, but hopefully yall will point me in the correct direction.

I've been tasked with `GitOps`ing my gitlab.com/group namespace. I'd like to be able to use the terraform provider to just create a MR against this repo, and a human merges it in.

It seems that the `password` is required, and that won't fly in a public readable repo, also people could be using OAuth, with github/twitter/google whatever so I won't even be able to guarantee they'll have a password.

I posted this as a general question here: https://forum.gitlab.com/t/a-repo-to-control-users-and-groups/22443 but any advice would be greatly appreciated.

Thanks again, and I apologize if this was the wrong place to ask.

**Comment by armsnyder** [comment]
Hi @jjasghar . The `password` attribute was made optional in #127, and you can now use the `reset_password` attribute make the user pick a password. Does this fit your use case?

**Comment by armsnyder** [comment]
I'm closing this since I believe the issue was resolved by #127 and did not hear back.
