### ISSUE TITLE
Ability to configure `Packages & Registries: Clean up image tags`

### ISSUE THREAD

**Issue by Skaronator** [gitlabhq/terraform-provider-gitlab#740]
I'd like to see support to configure a cleanup policy for container images with terraform:

![image](https://user-images.githubusercontent.com/2886913/140492316-2913cf6e-e8ec-4d29-9e5a-0a1b06572524.png)

Project -> Settings -> Packages & Registries

### Affected Resource(s)
Please list the resources as a list, for example:

gitlab_project

**Comment by oschrenk** [comment]
See also: https://github.com/gitlabhq/terraform-provider-gitlab/issues/594

**Comment by armsnyder** [comment]
closing as duplicate of #594
