### ISSUE TITLE
[Feature Request] Add minimal acces level to gitlab_group_membership

### ISSUE THREAD

**Issue by KoenR3** [gitlabhq/terraform-provider-gitlab#745]
Gitlab defines a minimal access level but this is not yet reflected in `gitlab_group_membership`.  To allow to assign this role through terraform, it should be added.  Is this possible?  This is currently blocking us from using Terraform for automatic provisioning of our gitlab infrastructure.

https://docs.gitlab.com/ee/user/permissions.html#users-with-minimal-access

**Comment by armsnyder** [comment]
closed via #747
