### ISSUE TITLE
Add `gitlab_project_issue` resource

### ISSUE THREAD

**Issue by mkjmdski** [gitlabhq/terraform-provider-gitlab#746]
Hi :)

It would be great to implement `gitlab_project_issue` or `gitlab_issue` resource. The use case is following:

we are using terraform to provision projects from scratch. As media company we've got kind of the same set of issues that are required at the beginnig of the project. We currently manage this manually or with some extra scripts. Would be good to keep terraform as single source of truth and provision standard issues with terraform too.

**Comment by armsnyder** [comment]
API docs: https://docs.gitlab.com/ee/api/issues.html

**Comment by armsnyder** [comment]
@timofurrer I changed the milestone, since I assume you kept this open to use it for further improvements.

**Comment by timofurrer** [comment]
@armsnyder not sure actually, we can close this since the initial request is solved and it's possible to do what was asked for. 

IMHO, we can close it ...

**Comment by armsnyder** [comment]
Sounds good!

Closed via #891

Released in v3.12.0 of the provider
