### ISSUE TITLE
Updating documentation for new default_branch_protection feature

### ISSUE THREAD

**Issue by mgriffin13** [gitlabhq/terraform-provider-gitlab#752]
In #706, the documentation was created for the new `default_branch_protection` feature, but I think it was incorrectly placed. Currently, the documentation lists the new capability as an `Attribute`, but I really think it should be an `Argument`, right? It took me a couple minutes to find it in the docs after I saw the feature release with v3.8.0

**Comment by QuingKhaos** [comment]
Yes, should be an argument. Wrongly copied&pasted from the data source.

**Comment by callum-stakater** [comment]
i actually feel like this feature is a bit broken, it seems like it needs 2 applies to actually take effect, we manage groups, projects and project scoped branch protection via some modules and even with this new setting `default_branch_protection = 0`  seems you need to plan/apply twice for a new group for it to be in the desired state, if you also tried to create a repo + branch protection then you are stuffed as the repo is still created with the default branch protection

**Comment by armsnyder** [comment]
Closing this since we have switched to auto generated docs for 3.9.0. We can continue discussing the multiple applies issue in #667
