### ISSUE TITLE
Error while using provider on a non yet created GitLab instance

### ISSUE THREAD

**Issue by PhilippeVienne** [gitlabhq/terraform-provider-gitlab#777]
We are provisionning a GitLab Instance and configuring it inside the same terraform module. However the following line:
https://github.com/gitlabhq/terraform-provider-gitlab/blob/8d1e61485686dbb6bad938e47785bb5eeff12d1f/gitlab/config.go#L78
is causing a request to the /user endpoint. Therefore, terraform fails to initialize.

Is it required to do this call?

**Comment by timofurrer** [comment]
AFAIK, this call is only there to let the provider fail during instantiation in case the credentials are invalid - which is rightly so a problem in your case.

I kinda like the "early exit" behavior in most cases, but I agree that it may prevent a few use cases. 
I've proposed a flag to disable that call in #787 .

**Comment by PhilippeVienne** [comment]
I think your solution is clearly the best, thank you for proposal.


Le dim. 23 janv. 2022 à 11:40, Timo Furrer ***@***.***> a
écrit :
