### ISSUE TITLE
Branch_protection documentation is missing one valid value for merge_access_level and push_access_level

### ISSUE THREAD

**Issue by lc-nyovchev** [gitlabhq/terraform-provider-gitlab#778]
### Affected Resource(s)
- branch_protection

### Expected Behavior
Go to the [branch_protection#merge_access_level](https://registry.terraform.io/providers/gitlabhq/gitlab/latest/docs/resources/branch_protection#merge_access_level) or [branch_protection#merge_access_level](https://registry.terraform.io/providers/gitlabhq/gitlab/latest/docs/resources/branch_protection#push_access_level).  It says:

> (Optional) One of five levels of access to the project. Valid values are: no one, developer, maintainer, admin.

Note that it says **"five levels of access"** but only 4 valid values are listed:
- `no one`
- `developer`
- `maintainer`
- `admin`

### Actual Behavior
Should either list the other valid value: e.g `guest` or, if `guest` is not valid, then it should say "One of **four** levels of access to the project"

**Comment by armsnyder** [comment]
The API docs say there are only 4 valid levels: https://docs.gitlab.com/ee/api/protected_branches.html
