### ISSUE TITLE
Feature request: Add support for printing_merge_request_link_enabled

### ISSUE THREAD

**Issue by Nadav-Ruskin** [gitlabhq/terraform-provider-gitlab#782]
Dear maintainers,

GitLab has recently added API support for setting `printing_merge_request_link_enabled`: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/76938

AFAIK it is not supported by this project at the moment. I couldn't find references to it in the code or the documentation https://registry.terraform.io/providers/gitlabhq/gitlab/latest/docs/resources/project

It would be great to support this API call.

**Comment by armsnyder** [comment]
Yep, I see the new `printing_merge_request_link_enabled` field listed in the API docs here: https://docs.gitlab.com/ee/api/projects.html

**Comment by marceloboeira** [comment]
@armsnyder @Nadav-Ruskin I have created a `wip` PR, but from what I can see this also requires a PR to the go client, which at the moment only supports that field on creation, it doesn't return such field on "GET". I'll. follow up there and mention this issue.
