### ISSUE TITLE
Add users to group resource

### ISSUE THREAD

**Issue by tsutsarin-fuib** [gitlabhq/terraform-provider-gitlab#8]
Allow adding users to group and defining their access rights.

**Comment by cjose3** [comment]
+1

**Comment by ericfrederich** [comment]
+1

**Comment by xabim** [comment]
+1

**Comment by sudoapt-getclean** [comment]
This is provided with merge request #61 and will be available in the next release

**Comment by armsnyder** [comment]
Closing this since the `gitlab_group_membership` resource was released.
