### ISSUE TITLE
Dependabot PRs fail with "bad decrypt" in EE test

### ISSUE THREAD

**Issue by armsnyder** [gitlabhq/terraform-provider-gitlab#801]
The Dependabot PRs are regularly failing the EE test with a "bad decrypt" error.

Manually retrying the test works.

See: https://github.com/gitlabhq/terraform-provider-gitlab/runs/4924486251

**Comment by timofurrer** [comment]
I think there was a comment (which I'm unable to find right now) already in some issue, but here again #717 showed again that we should run EE tests on every PR, too and not only branches created in this repository :)

**Comment by armsnyder** [comment]
There's #426 and #313 -- I think there's agreement that we should; we just need a workaround for PR workflows not having access to secrets to decrypt the license file.
