### ISSUE TITLE
Release 3.9.0?

### ISSUE THREAD

**Issue by mkjmdski** [gitlabhq/terraform-provider-gitlab#804]
Hi!

First thanks a lot for a lot pull requests with great features merged over last month :). Do you think it might be possible to release them soon? I can't wait to start managing files inside gitlab repositories with terraform :).

**Comment by timofurrer** [comment]
I think we are all looking forward to that next release and I hope we can get out some frequent releases from now on.

Anyways, @armsnyder and @nagyv what do you think about that? I suggest that we create a milestone for the next release and assign issues and MRs we want to have in there at least.

**Comment by armsnyder** [comment]
I'm not very familiar with our release process so would defer to whatever is most useful to @nagyv. I like monthly releases if we can keep up with it, and I think milestones would help communicate which issues may be blocking a release.

**Comment by nagyv** [comment]
I thought for now dropping the monthly cadence and setting the milestone scope only. Once the marked issues are ready, we create a release.

For 3.9.0, I was thinking that we might be okay already. Releasing it soon would provide feedback on the v2 upgrade, which even if our tests pass I consider risky by nature.

WDYT, would you prefer to add some more features into 3.9.0 or are we good for a new release?

I just created the 3.9.0 milestone. Let's collect here the issues/MRs you'd like to add. 

I know that @PatrickRice-KSC and @beekeep would love https://github.com/gitlabhq/terraform-provider-gitlab/pull/700 to be added.

**Comment by armsnyder** [comment]
@nagyv I agree we can release basically now, after a changelog update. However I added some PRs to the milestone which are ready to merge.

**Comment by timofurrer** [comment]
@nagyv Yes, I'd prefer on-demand releases as well and doing one asap :)

**Comment by Shocktrooper** [comment]
I am also for on-demand releases are we are not making new functionality or changing the way GitLab works like GitLab proper but always just trying to catch up to what the API provides. Also there is a merge conflict but would love to see Protected environments go into the next release as I believe it needs minor adjustments. https://github.com/gitlabhq/terraform-provider-gitlab/pull/750

**Comment by roidelapluie** [comment]
I am also fine with on-demand releases for now.
