### ISSUE TITLE
Broken master because of group variable tests in EE

### ISSUE THREAD

**Issue by timofurrer** [gitlabhq/terraform-provider-gitlab#810]
I suspect that the merge of #717 failed our EE Acceptance Tests, see https://github.com/gitlabhq/terraform-provider-gitlab/runs/4971848088?check_suite_focus=true#step:6:142

It's quite later here already, so I'll keep this as a reminder if it won't be fixed in the meantime .. 

/cc @armsnyder @nagyv

**Comment by armsnyder** [comment]
Yeah, there were EE-only tests added which were not run before merging. I'll take a look and open a PR if there's a clear fix; otherwise will revert and re-open the PR.
