### ISSUE TITLE
Changes to reduce likelihood of merge conflicts with new resources

### ISSUE THREAD

**Issue by armsnyder** [gitlabhq/terraform-provider-gitlab#831]
We often get merge conflicts on new resources/data-sources because they require being added to the `gitlab/provider.go` file.

```go
// provider.go

 ResourcesMap: map[string]*schema.Resource{
	"gitlab_branch_protection":          resourceGitlabBranchProtection(),
	"gitlab_tag_protection":             resourceGitlabTagProtection(),
	...
```

We could eliminate this problem by moving the registration of the new resource into the resource file itself.

Using `gitlab/resource_gitlab_deploy_key.go` as an example:

```go
var _ = registerResource("gitlab_deploy_key", func() *schema.Resource {
	return &schema.Resource{...}
})
```

or

```go
func init() {
	registerResource("gitlab_deploy_key", func() *schema.Resource {
		return &schema.Resource{...}
	})
}
```

instead of the current

```go
func resourceGitlabDeployKey() *schema.Resource {
	return &schema.Resource{...}
}
```

Of course this would introduce more conflicts in the short term.

This also helps with contributors (and maintainers) forgetting to update the main `gitlab/provider.go` file by keeping everything relating to the resource in one place.

**Comment by timofurrer** [comment]
I'm intrigued by the idea! The only downside I see right now is that it's not as as easy as before to immediately see a list of all resources, but I guess that's okay.

The `registerResource` is not something the SDK provides, right? So what was your idea? Adding it to a global map and then using it in the `schema.Provider` `ResourceMap` ?

**Comment by armsnyder** [comment]
Right I was imagining global maps in `provider.go` like

```go
var allResources = map[string]func() *schema.Resource{}
var allDataSources = map[string]func() *schema.Resource{}
```

And yep there would be that downside by decentralizing the resources. If we need a list though, there are plenty of workarounds, like generating the provider schema the way `tfproviderdocs` does.

**Comment by timofurrer** [comment]
Sounds good then! I suggest to address this once the PRs which are currently able to be merged are merged and after 3.9.0 is out :)

**Comment by armsnyder** [comment]
Nice. Yep I can try getting it in quickly after #815 is merged.

**Comment by timofurrer** [comment]
Sure!
