### ISSUE TITLE
[Feature Request] Add support for Group and Project Access Tokens

### ISSUE THREAD

**Issue by deepbrook** [gitlabhq/terraform-provider-gitlab#835]
Ahoi!

GitLab 13.9 introduced Project access tokens, and 14.7 introduced Group Access Tokens. Having a resource to manage these would be splendid. As far as I can tell, the APIs for both allow create/read/delete operations, making an implementation appear straight-forward.

### References
- [Project Access Token Docs](https://docs.gitlab.com/ee/user/project/settings/project_access_tokens.html#project-access-tokens)
- [Project Access Token API Docs](https://docs.gitlab.com/ee/api/project_access_tokens.html)
- [Group Access Token Docs](https://docs.gitlab.com/ee/user/group/settings/group_access_tokens.html#group-access-tokens)
- [Group Access API Docs](https://docs.gitlab.com/ee/api/group_access_tokens.html)

**Comment by timofurrer** [comment]
I've actually started a local branch implementing the Group Access Tokens. However, I'm waiting for https://github.com/xanzy/go-gitlab/issues/1347 to be implemented and released.

The Project Access Token resource is actually going to be released with 3.9.0 (already in master)
