### ISSUE TITLE
Next release: 4.0 or 3.10?

### ISSUE THREAD

**Issue by nagyv** [gitlabhq/terraform-provider-gitlab#845]
Hi there,

We would like to open the discussion around the scope of the next release.

Shall we ship breaking changes or stick with incremental improvements for the next release?

We started to add issues to [this milestone](https://github.com/gitlabhq/terraform-provider-gitlab/milestone/4), while we call it milestone 4.0.0, the question is still open. We can change it to 3.10.0.

**Comment by armsnyder** [comment]
I don't feel any pressure for a new major release, unless I'm forgetting something. 😁 The conversations we've been having about adding field names to match the upstream API (#553), adding new blocks to `gitlab_project` and `gitlab_group` (#792) and looking at GraphQL and partial code generation (#547) all feel like work we can fit into version 3 before we need to remove/break anything.

**Comment by timofurrer** [comment]
Yes, I agree. We can easily go with a 3.10 - I also don't feel any pressure to do that major release.
The ones I've assigned to 4.0.0 were just for the lack of having another one. 

I took the liberty and I created a 3.10 milestone and re-assigned the issues there. I'd still keep the 4.0.0 where we can assign issues for that release, most likely containing those breaking changes in the future.

**Comment by timofurrer** [comment]
Since, we've created the milestones and everyone kinda silently agreed, I'd say we can close this :)

Please, re-open if you don't think so :)
