### ISSUE TITLE
Release 3.9.1

### ISSUE THREAD

**Issue by armsnyder** [gitlabhq/terraform-provider-gitlab#846]
Hi @nagyv, can we release 3.9.1 soon? We had a regression #841 which we fixed in #843. Changelog is already updated.

**Comment by nagyv** [comment]
Pushed tag. Closing.

**Comment by armsnyder** [comment]
@nagyv @timofurrer Could we use `vX.X.X` format for milestones, or is there a particular reason for `X.X.X` format?

It would make the above message prettier and also enable us to work in some more release automation like automatically assigning milestones to closed issues/PRs as in https://github.com/hashicorp/terraform-provider-aws/blob/main/.github/workflows/milestone.yml

Of course we can work around it, just wondering. 😄

**Comment by timofurrer** [comment]
Yes, I agree (I'm ok with either way, as long as it's consistent :) )

**Comment by armsnyder** [comment]
> I'm ok with either way, as long as it's consistent :)
Same, only if we stick with `X.X.X` I would want to edit the milestone notify message.

**Comment by nagyv** [comment]
> @nagyv @timofurrer Could we use `vX.X.X` format for milestones, or is there a particular reason for `X.X.X` format?

Sure. I'll try to remember. :)

I prefixed the two open milestones.
