### ISSUE TITLE
Let's change the default branch to `main`

### ISSUE THREAD

**Issue by timofurrer** [gitlabhq/terraform-provider-gitlab#847]
It's overdue to change the default branch to `main`. 

@nagyv can you change that in the settings?

I can spot a reference to `master` here:

https://github.com/gitlabhq/terraform-provider-gitlab/blob/8cd2568e63320d127d215b1662a926d58186b8a2/.github/workflows/pr-check-conflicts.yml#L10

However, `main` is already included in that list, thus it shouldn't be an immediate problem. However, `master` can be removed :)

... and in the README when referencing the badges.

There is other `master` references in the test examples, which can also be changed independently.

**Comment by armsnyder** [comment]
Incidentally the badges are also referencing workflows that don't exist anymore 🤫
