### ISSUE TITLE
Support `allowed_to_unprotect` field in branch protection resource

### ISSUE THREAD

**Issue by timofurrer** [gitlabhq/terraform-provider-gitlab#878]
### Feature Description

The `gitlab_branch_protection` resource is missing the `allowed_to_unprotect` field.

The goal is to implement this to align with the upstream API.

While at it, it may also make sense to double check the branch protection data sources if they are aligned with upstream. (I quickly checked and I'm not sure if the upstream docs example is complete - it may make sense to quickly manually try what the response is.)

**Comment by beekeep** [comment]
I can take a look at this.

**Comment by timofurrer** [comment]
I'm not too familiar with that API (if I have some time I'll investigate a little), but in the meantime I'd say that this was merely a way to not send an empty request. I suspect that at least one of these optional fields has to be set. (there would be better ways to achieve that though.)
In my experience it's usually the fastest to just explore the API a little using curl. 

You may also join the discord if you quickly want to discuss some behavior of the API :)
