### ISSUE TITLE
README.md is initialised with project but not prepopulated with description

### ISSUE THREAD

**Issue by gthieleb** [gitlabhq/terraform-provider-gitlab#885]
### GitLab Provider version

3.9.1

### GitLab version

GitLab Community Edition 14.7.3

### Terraform version

Terraform v1.1.3 on linux_amd64 + provider registry.terraform.io/gitlabhq/gitlab v3.9.1

### Relevant Terraform Configuration

```hcl
variable projects {
  type = map(object({
    nice_name = string
    visibility_level = string
    parent_group = string
    description = string
    default_branch = string
    pipelines_enabled = bool
    issues_enabled = bool
    packages_enabled = bool
    container_registry_enabled = bool
    wiki_enabled = bool
  }))
  description = "The projects that should be created. The map key is the name of the project. Other values needs to be defined per instance."
  default = {
    s3_accounts_and_buckets = {
      nice_name = ""
      parent_group = "devopssharedprojects"
      visibility_level = "internal"
      description = "This terraform module manages kms encrypted s3 buckets and s3 accounts that can manage that bucket."
      default_branch = "dev"
      pipelines_enabled = false
      issues_enabled = false
      packages_enabled = false
      container_registry_enabled = false
      wiki_enabled = false
    }
}

variable default_initialize_with_readme {
  type = bool
  description = "Should the repo get created with an README file?"
  default = false
}
                  
data "gitlab_group" "by_name" {
  for_each = var.projects

  full_path = each.value.parent_group
}

resource "gitlab_project" "project" {
  for_each = var.projects

  name   = each.value.nice_name != "" ? each.value.nice_name : each.key

  namespace_id = data.gitlab_group.by_name[each.key].id
  description = each.value.description

  visibility_level = each.value.visibility_level
  default_branch = each.value.default_branch

  pipelines_enabled = each.value.pipelines_enabled
  packages_enabled = each.value.packages_enabled
  issues_enabled = each.value.issues_enabled
  container_registry_enabled = each.value.container_registry_enabled
  wiki_enabled = each.value.wiki_enabled

  initialize_with_readme = var.default_initialize_with_readme

}
```

### Description

Creation of a gitlab project with a populated description parameter leads to an empty README.md file.

The default behavior on the UI is that the README is populated with the content of the description.

**Comment by timofurrer** [comment]
Running your code as is, with a small fix (closing `}` is missing in first `variable` block) and using these exact defaults actually produces an empty `README.md`. However, this is to be expected given that the default of `var.default_initialize_with_readme` is set to `false`. 

Changing that default ...

```diff
variable default_initialize_with_readme {
  type = bool
  description = "Should the repo get created with an README file?"
-  default = false
+  default = true
}
```

... will populate the `README.md` with the description.

What's strange though is that the `README.md` is created but empty when `initialize_with_readme` is either omitted or `false`. BUT only if `default_branch` is not `main` ... but it also happens with the GitLab API directly, so not related the provider.

Does that work for you to?

**Comment by gthieleb** [comment]
Hi, thanks for testing this on your side. You are correct the title was wrong. 
The ticket is about that the `README.md` is created but empty and not populated with the content of the description by default (the default behavior of the UI). 

I also want to extend my module to create an .gitignore file using the `gitlab_repository_file` so I am fine with both approaches (if you decide to adapt **either** the UI **or** the API behavior).

**Comment by timofurrer** [comment]
I see, now it makes sense :)

This provider interacts with the GitLab REST API and we usually avoid implementing custom logic to replicate UI or any other behavior. It basically just "wraps" the API :)

> I also want to extend my module to create the .gitignore file using the gitlab_repository_file so I am fine with both approaches (if you decide to adapt either the UI or the API behavior).

I suggest to just set `initialize_with_readme = true` and use `gitlab_repository_file` to manage the `.gitignore` file :)

Since this is not really an issue I'll take the liberty to close this. If you have any more questions or feedback, just let us know here or in the Discord 🎉
