### ISSUE TITLE
Error: unable to get push_access_level: no valid access level found

### ISSUE THREAD

**Issue by Stromweld** [gitlabhq/terraform-provider-gitlab#890]
### GitLab Provider version

3.10.0

### GitLab version

Latest SaaS

### Terraform version

1.0.5

### Relevant Terraform Configuration

```hcl
resource "gitlab_branch_protection" "repo_branch" {
  for_each = var.gitlab_branch_protection

  project            = gitlab_project.repository.id
  branch             = each.key
  push_access_level  = "no one"  
  merge_access_level = "developer"
}
```

### Relevant log output

```shell
module.gitlab_cloud_sub_groups.module.sub_groups["cloud"].module.gitlab_sub_group_1["terraform"].module.gitlab_sub_group_2["AWS"].module.gitlab_sub_group_3["tf_aws_accounts"].module.gitlab_sub_group_4["aws_prd"].module.gitlab_sub_group_5["us-east-1"].module.sub_group_5.gitlab_group.sub_group: Refreshing state... [id=8607374]
╷
│ Error: unable to get push_access_level: no valid access level found
│ 
│   with module.gitlab_chef_cloud_projects.module.projects["xe_informatica_config"].module.repository.gitlab_branch_protection.repo_branch["master"],
│   on modules/projects/Gitlab_project/main.tf line 116, in resource "gitlab_branch_protection" "repo_branch":
│  116: resource "gitlab_branch_protection" "repo_branch" {
│ 
╵
```

### Description

After 3.10.0 update released seeing this error message on state refresh for plans

**Comment by timofurrer** [comment]
Thanks for reporting this! We kinda already had that suspicion ... https://github.com/gitlabhq/terraform-provider-gitlab/pull/881#discussion_r812109889

Can you do me a favor and post the API response here? Just run with `TF_LOG=debug terraform ...`

It's already pretty late here, but I'm going to fix this in a few hours ;)

**Comment by timofurrer** [comment]
@Stromweld it would be great if you could provide a standalone example which we can use to reproduce this. @armsnyder and myself were unable to reproduce this ...

**Comment by armsnyder** [comment]
I couldn't reproduce it with only the provided Terraform configuration, but I did reproduce it by modifying the branch protection upstream in GitLab UI after applying the configuration and then re-planning.

1. Apply the config:
   ```terraform
   terraform {
     required_providers {
       gitlab = {
         source  = "gitlabhq/gitlab"
         version = "= 3.10.0"
       }
     }
   }
   
   provider "gitlab" {
       token = "ACCTEST1234567890123"
       base_url = "http://pc.local:8080/api/v4"
   }
   
   resource "gitlab_branch_protection" "repo_branch" {
     project            = 34
     branch             = "main"
     push_access_level  = "no one"  
     merge_access_level = "developer"
   }
   ```

   ```
   Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
   ```
2. Manually change the project settings to change the "allowed to merge" from the role to a user.
<img width="570" alt="Screen Shot 2022-02-23 at 11 10 15 PM" src="https://user-images.githubusercontent.com/9969202/155475827-d25e5c59-18b3-4f0d-a152-3955ed0fc95b.png">
  
3. `terraform plan`
   ```
      gitlab_branch_protection.repo_branch: Refreshing state... [id=34:main]
   ╷
   │ Error: unable to get merge_access_level: no valid access level found
