### ISSUE TITLE
GitHub -> Discord notifications

### ISSUE THREAD

**Issue by nagyv** [gitlabhq/terraform-provider-gitlab#894]
### Feature Description

I set up a webhook to auto-post a message to the #general Discord channel on new releases. 

Do we want to post any other events to #general or other channels?

Please, add your thought to the issue. I plan to close this issue by the end of February.

### Do you want to implement this?

- [x] I would like to implement this myself 👷

**Comment by nagyv** [comment]
Simple webhooks can't do it, but I'd find it valuable to post a link to issues when a specific label is added, like when the "good for new contributor" label is added. That might help interested users to get involved as contributors.

**Comment by timofurrer** [comment]
@nagyv since we have the desired release notifications now in Discord I think we can close this. Or did you want even more notifications?

**Comment by nagyv** [comment]
Closing.
