### ISSUE TITLE
Cannot download provider 3.10.1

### ISSUE THREAD

**Issue by cmd-werner-diers** [gitlabhq/terraform-provider-gitlab#896]
### GitLab Provider version

3.10.1

### GitLab version

GitLab Enterprise Edition 14.9.0-pre 67dde8cf25d

### Terraform version

1.1.6

### Relevant Terraform Configuration

```hcl
terraform {
  required_providers {
    # Used for gitlab configuration
    gitlab = {
      source  = "gitlabhq/gitlab"
      version = "3.10.1"
    }
  }
}


provider "gitlab" { }
```

### Relevant log output

```shell
❯ tree -a
.
└── versions.tf

0 directories, 1 file


❯ terraform init

Initializing the backend...

Initializing provider plugins...
- Finding gitlabhq/gitlab versions matching "3.10.1"...
╷
│ Error: Failed to query available provider packages
│
│ Could not retrieve the list of available versions for provider gitlabhq/gitlab: no available releases match the given constraints 3.10.1
╵
```

### Description

Current behaviour:
Terraform cannot download the latest provider. 

Expected behaviour:
Terraform successfully installs the provider with the specified version

**Comment by timofurrer** [comment]
@nagyv I can confirm that the 3.10.1 provider hasn't been properly released somehow. Can you please check?

**Comment by timofurrer** [comment]
The pipeline apparently ran: https://github.com/gitlabhq/terraform-provider-gitlab/actions/runs/1891749446

**Comment by nagyv** [comment]
Interesting. 3.10.1 is definitely not available in the Terraform registry: https://registry.terraform.io/providers/gitlabhq/gitlab

**Comment by nagyv** [comment]
I triggered the webhook call for 3.10.1 again

**Comment by armsnyder** [comment]
@nagyv I also tried running `terraform init` using the 3.10.1 version and it is not downloading.

```
Could not retrieve the list of available versions for provider gitlabhq/gitlab: no available releases match the given constraints 3.10.1
```

Looking at our releases, I don't see anything different about the 3.10.1 release, looking at the assets and workflow logs.

Can you double check that our GPG public key still exists at https://registry.terraform.io/settings/gpg-keys ?

**Comment by nagyv** [comment]
> Can you double check that our GPG public key still exists at https://registry.terraform.io/settings/gpg-keys ?

The GPG key is there.

**Comment by floh96** [comment]
@timofurrer @nagyv  the 3.10.1 version is not in the registry, maybe the webhook call needs to be triggered again?

**Comment by timofurrer** [comment]
Yes, we are aware, we would need to backport something and re-tag. I suggest you wait for tomorrows v3.11.0. would that work for you?

**Comment by timofurrer** [comment]
FYI: release v3.10.1 has been re-synced by HashiCorp!
