### ISSUE TITLE
3.10.0 wants to re-activate all the users

### ISSUE THREAD

**Issue by ilpianista** [gitlabhq/terraform-provider-gitlab#897]
### GitLab Provider version

3.10.0

### GitLab version

14.7.1-ee

### Terraform version

1.0.11

### Relevant Terraform Configuration

```hcl
resource "gitlab_user" "user" {
  name        = "Name"
  username    = "username"
  email       = "e@ma.il"
}
```

### Relevant log output

```shell
# gitlab_user.user will be updated in-place
~ resource "gitlab_user" "user" {
      id                = "2"
      name              = "Name"
    ~ state             = "deactivated" -> "active"
      # (8 unchanged attributes hidden)
  }
```

### Description

We just upgraded to 3.10.0 and the provider want to re-activate all the deactivated users.

If I set the `state` field with the value `deactivated`, then I get this error message:

```
expected state to be one of [active blocked], got deactivated
```

**Comment by timofurrer** [comment]
This seems to be related to this change: https://github.com/gitlabhq/terraform-provider-gitlab/pull/762

Actually, from what I can tell, the activate and deactive user APIs have never been implemented properly.

I'm not entirely sure how this "deactivated" state has been set in your case. Was this set outside of terraform?

**Comment by ilpianista** [comment]
> I'm not entirely sure how this "deactivated" state has been set in your case. Was this set outside of terraform?

Yes, we disable the user from the Admin UI because this isn't possible via the provider, but we had to revert the upgrade ATM.

**Comment by timofurrer** [comment]
> Yes, we disable the user from the Admin UI because this isn't possible via the provider, but we had to revert the upgrade ATM.

I see, that makes sense. I'm currently implementing that deactivations are supported to enable your use case.
Manual interactions outside of terraform will sooner or later always cause issues on the tf side ...
