### ISSUE TITLE
Initialize_with_readme project creation timeout

### ISSUE THREAD

**Issue by jacobkretz** [gitlabhq/terraform-provider-gitlab#906]
### GitLab Provider version

3.10.0

### GitLab version

GitLab 14.8

### Terraform version

0.14.10

### Relevant Terraform Configuration

```hcl
resource "gitlab_project" "project" {
  initialize_with_readme                           = true

  name                                             = var.name

}
```

### Relevant log output

```shell
Error: error while waiting for branch main to reach 'protected' status, timeout while waiting for state to become 'true' (last state: 'false', timeout: 2m0s)
```

### Description

When upgrading to 3.10.0 and having initialize_with_readme set to true project creation times out with error above.  Verified 3.9.1 works.  Flipping initialize_with_readme to false will result in a successful project creation.

**Comment by Stromweld** [comment]
I’m seeing the same issue. While TF apply is running and waiting for new repo craeation to complete if you manually go to gitlab and create the branch protection it will complete successfully. I’m our case though then we get error on branch protection resource due to it already existing.

**Comment by armsnyder** [comment]
@jacobkretz Thanks for the report and for verifying that this is a regression between v3.9.1 and v3.10.0. 🙂 

@PatrickRice-KSC Do you think this could be caused by #862? I don't see other PRs in v3.10.0 which touched branch protection in the `gitlab_project` resource.

**Comment by timofurrer** [comment]
Thanks @Stromweld for the valuable information, the "no default branch protection" inherited from the group actually is the problem here. This is a standalone example which can be used to reproduce the issue:

```hcl
resource "gitlab_group" "group" {
  name                      = "issue-906"
  path                      = "issue906"
  default_branch_protection = 0
}

resource "gitlab_project" "project" {
  name                   = "issue-906"
  namespace_id           = gitlab_group.group.id
  initialize_with_readme = true
}
```

**Comment by timofurrer** [comment]
I've pushed a bugfix at #908. @Stromweld @jacobkretz In case you have the chance and are willing to then I would be super happy if you could verify the bugfix on that branch ;)

**Comment by PatrickRice-KSC** [comment]
Thanks for fixing this @timofurrer . Looks like I missed a scenario in my tests for that WaitForState change :(

**Comment by timofurrer** [comment]
@PatrickRice-KSC no worries :) It's especially hard to spot these inherited settings ... there is not much documentation around this ..

**Comment by Stromweld** [comment]
unfortunately I don't have the means to be able to test this fix until it's released.
