### ISSUE TITLE
group and project membership adding ability to add groups instead of just users

### ISSUE THREAD

**Issue by Stromweld** [gitlabhq/terraform-provider-gitlab#909]
### Feature Description

gitlab_group_membership and gitlab_project_membership allow you to add user_id's but not group_id's for group memberships in another group or project.

Please add the ability to add gitlab groups in gitlab_group_membership and gitlab_project_membership.

### Do you want to implement this?

- [ ] I would like to implement this myself 👷

**Comment by sourikghosh** [comment]
Hi, @Stromweld I would like to work on this. Can you give a brief on where to start looking for this change?

**Comment by Stromweld** [comment]
Those look like what I am trying to accomplish. Assumed it'd be apart of the membership resource since UI shows users and groups under members. Thanks for pointing me in the right direction.
