### ISSUE TITLE
Gitlab test instance never comes up healthy with colima hosted docker

### ISSUE THREAD

**Issue by petrmvala** [gitlabhq/terraform-provider-gitlab#912]
### GitLab Provider version

master

### GitLab version

N/A

### Terraform version

N/A

### Relevant Terraform Configuration

```hcl
N/A
```

### Relevant log output

```shell
==> /var/log/gitlab/gitlab-workhorse/current <==
{"correlation_id":"","duration_ms":12,"error":"badgateway: failed to receive response: dial unix /var/opt/gitlab/gitlab-rails/sockets/gitlab.socket: connect: no such file or directory","level":"error","method":"GET","msg":"","time":"2022-03-02T11:52:45Z","uri":""}
{"error":"GetGeoProxyURL: Received HTTP status code: 502","geoProxyBackend":{"Scheme":"","Opaque":"","User":null,"Host":"","Path":"","RawPath":"","ForceQuery":false,"RawQuery":"","Fragment":"","RawFragment":""},"level":"error","msg":"Geo Proxy: Unable to determine Geo Proxy URL. Fallback on cached value.","time":"2022-03-02T11:52:45Z"}
```

### Description

**Go version**
`go version go1.17.6 darwin/amd64`

**Setup**
```
brew install colima docker docker-compose docker-credential-helper
rm ~/.docker/config.json   # if needed
colima start
make testacc-up
```

**Expectation**
Gitlab instance comes up

**Reality**
```
./scripts/await-healthy.sh
Waiting for GitLab container to become healthy..............................................................................................................................................................................................................................................................................................................................
```
It is never healthy

**Comment by timofurrer** [comment]
I'm not sure if this issue really belongs here or to some place where the docker image is actually being maintained. The `await-healthy.sh` script doesn't seem to be an issue here I guess ...

**Comment by jtymes** [comment]
I'm wondering if this has to do with Colima using QEMU, as Docker Desktop on M1 (which uses QEMU) also does not start the GitLab omnibus containers ([issue](https://gitlab.com/gitlab-org/omnibus-gitlab/-/issues/6659)).

**Comment by timofurrer** [comment]
@jtymes I think I remember that @petrmvala mentioned that he's using an Intel Mac on Discord though ...

**Comment by jtymes** [comment]
Right but both Docker for M1 and Colima use QEMU. I can try reproducing it on my work laptop this week.

**Comment by petrmvala** [comment]
Correct, I'm running on this
```
Hardware Overview:

  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro16,2
  Processor Name:	Quad-Core Intel Core i5
  Processor Speed:	2 GHz
  Number of Processors:	1
  Total Number of Cores:	4
  L2 Cache (per Core):	512 KB
  L3 Cache:	6 MB
  Hyper-Threading Technology:	Enabled
  Memory:	16 GB
```

**Comment by jtymes** [comment]
I also receive an error when running with Colima on my Intel Mac. It appears to fail on running a `rake` task. I don't know that there is anything that can be done with the provider to help. 

```
There was an error running gitlab-ctl reconfigure:

execute[clear the gitlab-rails cache] (gitlab::gitlab-rails line 451) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received ''
---- Begin output of /opt/gitlab/bin/gitlab-rake cache:clear ----
STDOUT:
STDERR:
---- End output of /opt/gitlab/bin/gitlab-rake cache:clear ----
Ran /opt/gitlab/bin/gitlab-rake cache:clear returned
```

**Comment by timofurrer** [comment]
Since we have a working GitPod integration (see #936) now and there is no indication that we can fix something in the provider to make this work on every platform and setup ... is it okay for you if we close this issue?

**Comment by petrmvala** [comment]
Yes, thank you!
