### ISSUE TITLE
Squash commit message template

### ISSUE THREAD

**Issue by sasa-fajkovic** [gitlabhq/terraform-provider-gitlab#928]
### Feature Description

Gitlab supports changing the default [template for squash commit messages](https://docs.gitlab.com/ee/user/project/merge_requests/commit_templates.html#default-template-for-squash-commits) (Settings > General > Merge Requests > Squash commit message template)

It seems that there is no support for this in terraform at the moment. 

### Do you want to implement this?

- [ ] I would like to implement this myself 👷

**Comment by timofurrer** [comment]
Thanks for the report! I'm working on this in #917
