### ISSUE TITLE
Remove parallelism limitation in `gitlab_repository_file` resource

### ISSUE THREAD

**Issue by timofurrer** [gitlabhq/terraform-provider-gitlab#940]
At the moment we have the limitation that if a terraform module / run contains more than one `gitlab_repository_file` resource the entire terraform `apply` / `destroy` has to be run with `-parallelism=1` for reliable success:

https://github.com/gitlabhq/terraform-provider-gitlab/blob/b1521811a1e99391801e69b19287565a4918257d/internal/provider/resource_gitlab_repository_file.go#L21

If it's run in parallel you'll experience something like this:

```
Error: somefile.yaml failed to delete repository file: 
(400 Bad Request) DELETE https://gitlab.com/api/v4/projects/30716/repository/files/vsomefile.yaml: 400 
{message: 9:Could not update refs/heads/master. Please refresh and try again..}
```

The root cause cannot be fixed in the provider, because the GitLab upstream API has this limitation that parallel changes to the repository are not allowed.

Any clever ideas on how to mitigate / remove this limitations? Maybe retries with a timeout and random wait time in between for that particular error? 

/cc @armsnyder

**Comment by timofurrer** [comment]
Maybe we could implement some "global state" in the provider and queue the API calls for that resource ...

**Comment by gthieleb** [comment]
Hi, just stumbled about this issue today. 
Will an additional `ReadContext` applied after a Update/Create/Delete opration help with refreshing the internal object `refs`?

**Comment by timofurrer** [comment]
What exactly do you mean?
The problem spawns across multiple tf resources, because it's the underlying Git repository in GitLab which needs a refresh ...
