### ISSUE TITLE
Mistake in release note

### ISSUE THREAD

**Issue by Moon1706** [gitlabhq/terraform-provider-gitlab#943]
### GitLab Provider version

v3.12.0

### GitLab version

it doesn't matter

### Terraform version

it doesn't matter

### Relevant Terraform Configuration

```hcl
it doesn't matter
```

### Relevant log output

```shell
it doesn't matter
```

### Description

Hello! In [this release](https://github.com/gitlabhq/terraform-provider-gitlab/releases/tag/v3.12.0) was duplicated new data source. If I right understand instead `gitlab_project_issue` should be `gitlab_project_tag`.

**Comment by timofurrer** [comment]
thanks for the report 🎉 

Not quite, there is such a release, but the tag resource was just missing in the list. I've fixed it: https://github.com/gitlabhq/terraform-provider-gitlab/releases/tag/v3.12.0
