### ISSUE TITLE
Possibility to manage the AutoDevops feature

### ISSUE THREAD

**Issue by gthieleb** [gitlabhq/terraform-provider-gitlab#946]
### Feature Description

Currently when the pipeline is enabled this also imply the enablement of the AutoDevops feature. For a project that currently does not ship with a .gitlab-ci.yml file this means that on every `git push` some pipeline tasks are started and strange artifacts are created. It would be great to have the possibility to disable the `AutoDevopsFeature`. The appropriate way would be an optional attribute in the `gitlab_project` resource.

### Do you want to implement this?

- [ ] I would like to implement this myself 👷

**Comment by timofurrer** [comment]
This will be addressed in https://github.com/gitlabhq/terraform-provider-gitlab/pull/917 with the `auto_devops_enabled` and `auto_devops_deploy_strategy` attributes. I assume that this would solve your issue, right?

**Comment by gthieleb** [comment]
Hi, @timofurrer sounds good that this is already in progress. Do you plan to make it dependent on the `enable_pipeline` attribute? My usecase would be to make it possible to enable the pipeline but disable `autodevops` in the same terraform run. Will this be possible?

**Comment by timofurrer** [comment]
@gthieleb which `enable_pipeline` are you referring to? There is no such field for the [Project API](https://docs.gitlab.com/ee/api/projects.html#create-project).

**Comment by gthieleb** [comment]
Hi, i am refering the attribute ‘pipeline_enabled‘ from the ‘gitlab_project‘ resource of the provider.

**Comment by timofurrer** [comment]
Oh damn, looked accidentally in the group resource 🙈  ... From the provider side those don't collide and we don't implement special behavior for them (as of now at least ...). That being said, you can do something like this:

```hcl
resource "gitlab_project" "example" {
  name = "example"
  pipelines_enabled = true
  auto_devops_enabled = false
```
