### ISSUE TITLE
Display gitlab_repository_file diff as decoded base64

### ISSUE THREAD

**Issue by mkjmdski** [gitlabhq/terraform-provider-gitlab#956]
### Feature Description

Is it possible in terms of terraform to use some kind of "diff plugin" to display base64 encoded files in decoded format? At this point any diff on gitlab_repository_file is unreadable for human. Once again thanks for implementing that :).

**Comment by timofurrer** [comment]
@mkjmdski I've addressed in #972. I think the only way to achieve this is to allow to specify plan text as `content` and automatically encode it to base64. I've implemented it in a backwards-compatible way.

I'm open to feedback if you want to try it out :)
