### ISSUE TITLE
Support true topic deletion

### ISSUE THREAD

**Issue by jtymes** [gitlabhq/terraform-provider-gitlab#966]
### Feature Description

Topic deletion landed in [14.9](https://docs.gitlab.com/ee/api/topics.html#delete-a-project-topic).

@timofurrer I'm assuming you'll want this one since you implemented it all the way so far, but I'm also willing to give it a try. 

### Do you want to implement this?

- [ ] I would like to implement this myself 👷

**Comment by timofurrer** [comment]
I actually have that already implemented on a branch 😅
