### ISSUE TITLE
Move `beekeep` and `PatrickRice-KSC` to triage role

### ISSUE THREAD

**Issue by nagyv** [gitlabhq/terraform-provider-gitlab#975]
### Feature Description

@beekeep and @PatrickRice-KSC expressed interest in becoming maintainers of the project.

As they become more active lately, I suggest giving them a "Triage" role. (See the GitHub roles at https://docs.github.com/en/organizations/managing-access-to-your-organizations-repositories/repository-roles-for-an-organization )

The Triage role will allow them to become more active in reviews without the possibility of merging code. This allows greater involvement for them and more collaboration opportunities for all of us.

Please, vote with likes / unlikes or just share your opinion.

### Do you want to implement this?

- [X] I would like to implement this myself 👷

**Comment by DonNicoJs** [comment]
@nagyv Good for me! 👍

**Comment by PatrickRice-KSC** [comment]
excited to be able to help out more 😄

**Comment by nagyv** [comment]
As all the current maintainers voted 👍  , I am moving on with the changes.

@PatrickRice-KSC @beekeep welcome to the maintainer team!

**Comment by timofurrer** [comment]
Welcome folks 💃🎉

**Comment by PatrickRice-KSC** [comment]
Thanks all!

**Comment by beekeep** [comment]
Thank you!  Looking forwarding to it!
