### ISSUE TITLE
Allow executable file to be pushed in using gitlab_repository_file resource

### ISSUE THREAD

**Issue by IrfanAnsari** [gitlabhq/terraform-provider-gitlab#981]
### Feature Description

I am using Gitlab provider to create a template project and require one of the files to be checked and pushed in as executable. 

gitlab_repository_file resource accepts chmod and values either in number or letters to suggest it's executable file something like
```
resource gitlab_repository_file "executable_file" {
     chmod = "+x"
}
```

### Do you want to implement this?

- [ ] I would like to implement this myself 👷

**Comment by timofurrer** [comment]
This would indeed be a nice feature. However, the [upstream GitLab API](https://docs.gitlab.com/ee/api/repository_files.html#create-new-file-in-repository) doesn't support that :'(

**Comment by timofurrer** [comment]
I'll take a look what that would mean to implement in GitLab itself ... I'll come back in a few days with some more information ..

**Comment by PatrickRice-KSC** [comment]
@timofurrer  - I wonder if we should be using the "commits" api instead behind the scenes here. There is a "chmod" action in that API that we could use for this, and using the "commits" API doesn't seem to preclude committing just one file.

https://docs.gitlab.com/ee/api/commits.html#create-a-commit-with-multiple-files-and-actions

**Comment by timofurrer** [comment]
I'm not sure about mixing APIs in resources. I'm open for discussing the details of having a commit resource like proposed in

* https://github.com/gitlabhq/terraform-provider-gitlab/issues/241

in addition to the `gitlab_repository_files` resource. WDYT? 

However, in general I currently struggle to understand what exactly would be managed in terraform using the commit API - would it just "revert" a commit in a destroy? what if it doesn't apply? There are some open questions for me there ...

**Comment by timofurrer** [comment]
For transparency: I'm working on getting an `execute_filemode` flag into the Repository Files API, much like it already exists for the Commits API. Let's see if we can get this into GitLab 14.10. Here is the Draft MR:

* https://gitlab.com/gitlab-org/gitlab/-/merge_requests/83499/

**Comment by timofurrer** [comment]
FYI: GitLab 14.10 will include this change (already available on .com) and I've created the integration into the provider in #1039, stay tuned for the next release @IrfanAnsari 🎉
