### ISSUE TITLE
Move `jtymes` to triage role

### ISSUE THREAD

**Issue by nagyv** [gitlabhq/terraform-provider-gitlab#985]
### Feature Description

@jtymes to become a triage-role member of the project.

As he become more active lately, I suggest giving him a "Triage" role. (See the GitHub roles at https://docs.github.com/en/organizations/managing-access-to-your-organizations-repositories/repository-roles-for-an-organization )

The Triage role will allow him to become more active in reviews without the possibility of merging code. This allows greater involvement for them and more collaboration opportunities for all of us. This allows him to become a maintainer in the following step.

The current maintainers already agreed on turning Jeremy into a triage-maintainer. @jtymes are you interested?

### Do you want to implement this?

- [X] I would like to implement this myself 👷

**Comment by nagyv** [comment]
As @jtymes agreed. I am moving forward with this.

**Comment by jtymes** [comment]
I am interested! Glad to help out where I can.
