### ISSUE TITLE
Is it possible to pull mirror a repo using username / password, or by using a single SSH key and not generate one for each project?

### ISSUE THREAD

**Issue by rj93** [gitlabhq/terraform-provider-gitlab#986]
I am trying to mirror ~100 repos and do not want to have to configure them all individually. 

I have looked through the docs, and there isn't much there, and have tried the following:

```
resource "gitlab_project" "example" {
  name        = "example"
  description = "My awesome codebase"

  mirror = true
  import_url = "https://<username>:<password>@external.gitrepo.com/example.git"
  mirror_trigger_builds = false
}

```

But it errors out with a 500 from the server.

I have checked and `git clone https://<username>:<password>@external.gitrepo.com/example.git` works locally. 

I noticed in the UI that when you mirror a repo if you add the mirror URL as `https://<username>:<password>@external.gitrepo.com/example.git` it also doesn't work, but you instead have to use `https://<username>@external.gitrepo.com/example.git` and specify the password in a separate field. This field doesn't appear to exist on the `gitlab_project` resource though.

Is there any way I can do with without either:
1. adding them all manually
2. adding the ssh keys that are generated manually to the external host?

**Comment by timofurrer** [comment]
> But it errors out with a 500 from the server.

What's the error message you are getting?

Have you tried using a personal access token with the scape `api` as described in the [docs](https://docs.gitlab.com/ee/api/projects.html#configure-pull-mirroring-for-a-project) ?

I've tried it locally with the example you've provided and it works for me.

The thing is that this `pull mirroring` works with the API and the API doesn't allow password for authentication.
That also explains why your tests using `git clone` worked fine.

Let me know if the PAT works :)

**Comment by rj93** [comment]
Hi @timofurrer,

The error I am getting from terraform is:

```
2022-03-29T13:29:38.657+0100 [INFO]  plugin.terraform-provider-gitlab_v3.12.0: 2022/03/29 13:29:38 [DEBUG] GitLab API Response Details:
---[ RESPONSE ]--------------------------------------
HTTP/2.0 500 Internal Server Error
Content-Length: 39
Cache-Control: no-cache
Content-Type: application/json
Date: Tue, 29 Mar 2022 12:29:38 GMT
Server: nginx
Vary: Origin
X-Request-Id: 01FZATECH4FGAYX0SA5JKX8KV7
X-Runtime: 0.031066

{
 "message": "500 Internal Server Error"
}
```

The PAT token that terraform is using has every permissions granted:
<img width="634" alt="Screenshot 2022-03-29 at 13 35 00" src="https://user-images.githubusercontent.com/6817539/160612384-1091032c-5e94-4c0e-a7e0-043cb2201834.png">

It also is able to create repositories without mirroring enabled, so don't think it's a permissions issue.

But from your comment stating that the `/projects` API not supporting username/password authentication explains why this won't work, but looking at the [API documentation](https://docs.gitlab.com/ee/api/projects.html#configure-pull-mirroring-for-a-project) it appears it is a supported format:

> URL of remote repository being mirrored (with user:token if needed).

The password I'm using has to include special characters, but I just tried it with only alphas and am now getting this error:

```
2022-03-29T13:46:51.182+0100 [INFO]  plugin.terraform-provider-gitlab_v3.12.0: 2022/03/29 13:46:51 [DEBUG] GitLab API Response Details:
---[ RESPONSE ]--------------------------------------
HTTP/2.0 422 Unprocessable Entity
Content-Length: 136
Cache-Control: no-cache
Content-Type: application/json
Date: Tue, 29 Mar 2022 12:46:51 GMT
Server: nginx
Vary: Origin
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Request-Id: 01FZAVDVHTHKVX5HYSWJPHMSNB
X-Runtime: 1.389137

{
 "message": "https://my_custom_user:test@external.gitrepo.com/example.git is not a valid HTTP Git repository"
}
```

**Comment by rj93** [comment]
Actually having re-read the docs and your comment, did you mean to include the PAT token in the import URL? 

The host (on-prem BitBucket) of the git repo I am trying to clone is public, but requires username / password authentication to access so I only have the password as provided by the vendor. 

I have also tried encoding the password I have available, and am now getting the same `https://my_custom_user:encodedpassword@external.gitrepo.com/example.git is not a valid HTTP Git repository` error.

**Comment by rj93** [comment]
Figured it out now, thanks @timofurrer. I didn't realise BitBucket also had PATs. I requested one there and am now able to use `https://my_custom_user:bitbucket_pat@external.gitrepo.com/example.git` as my import_url.
