### ISSUE TITLE
Feature Request: gitlab_service_external_wiki

### ISSUE THREAD

**Issue by SeameX** [gitlabhq/terraform-provider-gitlab#996]
### Feature Description

Hello,

we use confluence as wiki for our projects. It would be awesome if the integration could be configured via terraform. At the moment we use null resources & curl. Ressource `gitlab_service_external_wiki` is needed :)

https://docs.gitlab.com/ee/api/integrations.html#external-wiki

Best regards

SeameX

### Do you want to implement this?

- [ ] I would like to implement this myself 👷

**Comment by jtymes** [comment]
I'm wondering with all the integrations (including #995) that are available if it makes sense to have separate resources for them all, or a single resource that can accept blocks for each. @timofurrer WDYT? 

```terraform
resource "gitlab_project_integration" "myproject_integrations" {
    project = "myproject"

    external_wiki {
        external_wiki_url = "https://my.wiki.com"
    }
    
    jenkins {
        jenkins_url = "https://jenkins.mycorp.com"
        ...
    }
}
```

This would only support _project_ integrations. Group integrations also exist, but apparently do not have an API exposed. See [issue](https://gitlab.com/gitlab-org/gitlab/-/issues/328496).

**Comment by Shocktrooper** [comment]
@jtymes I feel like this might be a lot more work than it initially appears.  Not to mention the resulting `gitlab_project_integration.go` and accompanying test file would be monstrous considering all of the available integrations. We would also have to handle all of the integrations API caveats in single giant methods in the provider create/read/update.

**Comment by Shocktrooper** [comment]
Also @timofurrer This resource would also need an update to go-gitlab to change the part of the url `services` to integrations.  I'm wondering if we just make an upstream ticket to change all of them over at the same time

**Comment by jtymes** [comment]
Yeah, it will definitely be a lot of work 😄. It would be incremental, starting with the integrations people have requested. I'm less concerned about what the upstream naming is (service/integration), since we can either make that change ahead of time or migrate it later on without an impact on state.

**Comment by PatrickRice-KSC** [comment]
I do feel like it's a ton of new resources, but I think the APIs are different enough that in most cases overloading into a single resource would be more confusing than it would produce benefit :-/

For example, if we combine the EWM and Drone integrations into one resource, the resulting resource would need to have the superset of attributes for the integrations, and thus they would essentially all need the `optional: true`. That means that in a lot of cases terraform would have issues finding issues during either `terraform validate` or during plan time unless we wrote some pretty brutal validation logic into the resource. I am also a bit worried about the cognitive complexity it would take to review such code as well 😖 

What we could maybe do is create some shared "createIntegration" and "createIntegrationBasicTest" functions that accepted structs of attributes to remove some of the backend logic required to implement some of the resources, but still implement them as individual resources so we could rely on the native TF validation, and keep the tests simple too.

**Comment by SeameX** [comment]
Thanks guys that was pretty fast <3

**Comment by jtymes** [comment]
> For example, if we combine the EWM and Drone integrations into one resource, the resulting resource would need to have the superset of attributes for the integrations, and thus they would essentially all need the `optional: true`. 

I'm not quite sure what you mean. The schema would have top-level aggregate types, like `jira`, that would be optional, but those would have their own schemas that could require fields. An example of this would be `push_rules` in `gitlab_resource_project`. There would not be a superset; that _would_ be chaotic. 

Anyway, I'm good with individual resources. It will be interesting to handle if/when they add support for group- and instance-level integrations.

**Comment by armsnyder** [comment]
I get the idea of having each integration be a block. Some effects of modeling the resource this way which may or may not be desired are:
- If you import the resource, you are importing all integrations. So if you then destroyed it, you would disable all integrations.
- If someone adds an integration out-of-band, and then you re-run `terraform apply`, it would deactivate their integration.

I think having separate resources is better, unless some folks in the community want the above behavior.
